import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:drift/drift.dart' as drift;
import 'package:dmx/core/services/database_service.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/permission_service.dart';
import 'package:dmx/features/downloads/models/download_task.dart';
import 'package:dmx/core/services/youtube_service.dart';
import 'package:dmx/features/downloads/provider/download_provider.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';

class MockConnectivityPlatform extends ConnectivityPlatform {
  static List<ConnectivityResult> results = [ConnectivityResult.wifi];

  @override
  Future<List<ConnectivityResult>> checkConnectivity() async {
    return results;
  }

  @override
  Stream<List<ConnectivityResult>> get onConnectivityChanged {
    return Stream.value(results);
  }
}

class FakeDownloadEngine extends DownloadEngine {
  final startedUrls = <String>[];

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? referer,
    String? customUserAgent,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
    CancelToken? cancelToken,
  }) async {
    return DownloadMetadata(
      fileName: requestedFileName ?? 'file.zip',
      category: 'Archive',
      fileSize: 100,
      supportsResume: true,
    );
  }

  @override
  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    bool isRetry = false,
    String? referer,
    String? customUserAgent,
    String? cookies,
    String? oauthToken,
    bool bypassSSL = false,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
  }) {
    startedUrls.add(url);
    final completer = Completer<void>();
    cancelToken.whenCancel.then((_) {
      if (!completer.isCompleted) {
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: url),
            type: DioExceptionType.cancel,
          ),
        );
      }
    });
    return completer.future;
  }
}

class FakePermissionService extends PermissionService {
  @override
  Future<String> defaultDownloadDirectory() async => 'build/test_downloads';

  @override
  Future<bool> ensureStorageAccess() async => true;
}

Future<(DatabaseService, SettingsProvider)> _setupServices() async {
  SharedPreferences.setMockInitialValues({});
  if (!Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
    await Hive.openBox<dynamic>(DatabaseService.downloadsBoxName);
  }
  await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();

  final database = DatabaseService.forSubclass();
  await database.init(testPath: 'build/test_hive_provider');
  final settings = SettingsProvider();
  await settings.load();
  return (database, settings);
}

void main() {
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    drift.driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
    Hive.init('build/test_hive_provider');
    ConnectivityPlatform.instance = MockConnectivityPlatform();

    // Register mock handlers for platform channels
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('com.example.dmx/widget'),
      (methodCall) async => null,
    );
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('plugins.it_nomads.com/flutter_secure_storage'),
      (methodCall) async {
        switch (methodCall.method) {
          case 'read':
            return null;
          case 'write':
          case 'delete':
          case 'containsKey':
          case 'readAll':
          default:
            return null;
        }
      },
    );
  });

  tearDown(() async {
    if (Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
      await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();
    }
  });

  test('load converts stale downloading tasks to paused', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    await database.saveTask(
      DownloadTask(
        id: 'stale',
        fileName: 'stale.zip',
        url: 'https://example.com/stale.zip',
        fileSize: 100,
        downloadedBytes: 10,
        category: 'Archive',
        status: DownloadStatus.downloading,
        savePath: 'build',
        localFilePath: 'build/stale.zip',
        tempFilePath: 'build/stale.zip.dmxpart',
        threadCount: 2,
        chunks: const [0.1, 0.1],
        createdAt: now,
        updatedAt: now,
      ),
    );

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    // Disable auto-resume so the test verifies orphan-pausing behavior
    settings.autoStart = false;
    await provider.load();

    expect(provider.tasks.single.status, DownloadStatus.paused);
    expect(provider.tasks.single.speed, 0);
  });

  test('addDownload respects maxDownloads and queues overflow', () async {
    final (database, settings) = await _setupServices();
    await settings.setMaxDownloads(1);
    final engine = FakeDownloadEngine();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: engine,
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: 'one.zip',
      url: 'https://example.com/one.zip',
      size: 0,
      category: '',
      savePath: '',
    );
    await provider.addDownload(
      name: 'two.zip',
      url: 'https://example.com/two.zip',
      size: 0,
      category: '',
      savePath: '',
    );

    await Future<void>.delayed(const Duration(milliseconds: 50));

    expect(provider.downloadingTasksCount, 1);
    expect(provider.queuedTasksCount, 1);
    expect(engine.startedUrls, ['https://example.com/one.zip']);
  });

  test('addDownloadsBatch enqueues multiple tasks in one call', () async {
    final (database, settings) = await _setupServices();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    final ids = await provider.addDownloadsBatch([
      const DownloadAddSpec(
        name: 'one.zip',
        url: 'https://example.com/one.zip',
        size: 0,
        category: 'Archive',
        savePath: '',
      ),
      const DownloadAddSpec(
        name: 'two.zip',
        url: 'https://example.com/two.zip',
        size: 0,
        category: 'Archive',
        savePath: '',
      ),
    ]);

    expect(ids.length, 2);
    expect(provider.tasks.length, 2);
    expect(
        provider.tasks.map((task) => task.url),
        containsAll([
          'https://example.com/one.zip',
          'https://example.com/two.zip',
        ]));
  });

  test(
    'updateTaskThreadCount on task with zero progress only resizes chunks',
    () async {
      final (database, settings) = await _setupServices();
      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      settings.autoStart = false;
      await provider.load();

      await provider.addDownload(
        name: 'test.zip',
        url: 'https://example.com/test.zip',
        size: 100,
        category: '',
        savePath: '',
        threadCount: 2,
      );

      final taskId = provider.tasks.first.id;
      expect(provider.tasks.first.threadCount, 2);
      expect(provider.tasks.first.chunks.length, 2);

      await provider.pauseTask(taskId);
      await Future.delayed(const Duration(milliseconds: 50));

      await provider.updateTaskThreadCount(taskId, 5);
      expect(provider.tasks.first.threadCount, 5);
      expect(provider.tasks.first.chunks.length, 5);
      expect(provider.tasks.first.downloadedBytes, 0);
    },
  );

  test(
    'updateTaskThreadCount on task with non-zero progress resets progress and chunks',
    () async {
      final (database, settings) = await _setupServices();
      final now = DateTime.now();
      final task = DownloadTask(
        id: 'active_task',
        fileName: 'active.zip',
        url: 'https://example.com/active.zip',
        fileSize: 100,
        downloadedBytes: 50,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: 'build',
        localFilePath: 'build/active.zip',
        tempFilePath: 'build/active.zip.dmxpart',
        threadCount: 2,
        chunks: const [0.5, 0.5],
        createdAt: now,
        updatedAt: now,
      );
      await database.saveTask(task);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      await provider.load();

      expect(provider.tasks.first.downloadedBytes, 50);
      expect(provider.tasks.first.threadCount, 2);

      await provider.updateTaskThreadCount('active_task', 4);
      expect(provider.tasks.first.threadCount, 4);
      expect(provider.tasks.first.chunks.length, 4);
      expect(provider.tasks.first.downloadedBytes, 0);
      expect(provider.tasks.first.status, DownloadStatus.paused);
    },
  );

  test(
    'load with pauseOrphanDownloads=false preserves active downloads',
    () async {
      final (database, settings) = await _setupServices();
      final now = DateTime.now();
      await database.saveTask(
        DownloadTask(
          id: 'active',
          fileName: 'active.zip',
          url: 'https://example.com/active.zip',
          fileSize: 100,
          downloadedBytes: 10,
          category: 'Archive',
          status: DownloadStatus.downloading,
          savePath: 'build',
          localFilePath: 'build/active.zip',
          tempFilePath: 'build/active.zip.dmxpart',
          threadCount: 2,
          chunks: const [0.1, 0.1],
          createdAt: now,
          updatedAt: now,
        ),
      );

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      // Disable auto-resume to verify pause-orphan behavior in isolation
      settings.autoStart = false;
      await provider.load();
      expect(provider.tasks.single.status, DownloadStatus.paused);

      // Simulate a fresh provider reload (e.g. pull-to-refresh).
      await provider.load(pauseOrphanDownloads: false);
      expect(
        provider.tasks.single.status,
        DownloadStatus.paused,
        reason: 'No active stream → still paused on subsequent load',
      );

      // Now add a fake active stream; reload should not pause it.
      final second = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      settings.autoStart = false;
      await second.load();
      // No active stream from outside; the cancelTokens map is empty. So
      // the "in-flight" condition can't be triggered from outside. The
      // important regression test is the previous assertion (downloads
      // started by a previous load are not silently paused on a user
      // refresh).
    },
  );

  test(
      'retryTask does not zero downloadedBytes or chunks when .dmxstate exists',
      () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();

    final stateFile = File('build/resume.zip.dmxpart.dmxstate');
    await stateFile.parent.create(recursive: true);
    await stateFile.writeAsString(jsonEncode({
      'totalSize': 200,
      'threadCount': 2,
      'progress': [40, 40],
    }));

    final task = DownloadTask(
      id: 'retry_target',
      fileName: 'resume.zip',
      url: 'https://example.com/resume.zip',
      fileSize: 200,
      downloadedBytes: 80,
      category: 'Archive',
      status: DownloadStatus.failed,
      savePath: 'build',
      localFilePath: 'build/resume.zip',
      tempFilePath: 'build/resume.zip.dmxpart',
      threadCount: 2,
      chunks: const [0.4, 0.4],
      createdAt: now,
      updatedAt: now,
    );
    await database.saveTask(task);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    settings.autoStart = false;
    await provider.load();

    await provider.retryTask('retry_target');
    expect(
      provider.tasks.first.downloadedBytes,
      80,
      reason: 'retry must preserve the on-disk resume state from .dmxstate',
    );

    if (await stateFile.exists()) await stateFile.delete();
  });

  test('categorySizes ignores failed and unknown categories', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    final tasks = [
      DownloadTask(
        id: 'a',
        fileName: 'a.mp4',
        url: 'https://x/a.mp4',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Video',
        status: DownloadStatus.failed,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
      ),
      DownloadTask(
        id: 'b',
        fileName: 'b.mp4',
        url: 'https://x/b.mp4',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Video',
        status: DownloadStatus.queued,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
      ),
      DownloadTask(
        id: 'c',
        fileName: 'c.mp4',
        url: 'https://x/c.mp4',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Alien', // unknown category
        status: DownloadStatus.completed,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [1.0],
        createdAt: now,
        updatedAt: now,
      ),
    ];
    for (final t in tasks) {
      await database.saveTask(t);
    }

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    final sizes = provider.categorySizes;
    expect(
      sizes['Video'] ?? 0.0,
      lessThan(0.001),
      reason: 'Failed/queued tasks must not contribute to disk usage',
    );
    expect(
      sizes.containsKey('Alien'),
      false,
      reason: 'Unknown categories must not be silently dropped into the map',
    );
  });

  test(
    'updateTorrentTaskFiles updates torrent selection and file size correctly',
    () async {
      final (database, settings) = await _setupServices();
      final now = DateTime.now();
      final task = DownloadTask(
        id: 'torrent_test',
        fileName: 'test.torrent',
        url: 'file:///path/test.torrent',
        fileSize: 300,
        downloadedBytes: 0,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
        torrentFiles: const [
          {'name': 'file1.txt', 'length': 100, 'selected': true},
          {'name': 'file2.txt', 'length': 200, 'selected': true},
        ],
      );
      await database.saveTask(task);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      await provider.load();

      expect(provider.tasks.first.fileSize, 300);

      // Unselect file1.txt
      final updatedFiles = [
        {'name': 'file1.txt', 'length': 100, 'selected': false},
        {'name': 'file2.txt', 'length': 200, 'selected': true},
      ];
      await provider.updateTorrentTaskFiles('torrent_test', updatedFiles);

      expect(provider.tasks.first.torrentFiles![0]['selected'], false);
      expect(provider.tasks.first.fileSize, 200); // 300 - 100
    },
  );

  test(
    'DownloadProvider handles 403 Forbidden error and does not retry',
    () async {
      final (database, settings) = await _setupServices();
      await settings.setAutoRetryEnabled(true);
      await settings.setMaxDownloads(2);

      final errorResponse = Response(
        requestOptions: RequestOptions(path: 'https://example.com/403.zip'),
        statusCode: 403,
        statusMessage: DownloadStatusMessages.forbidden,
      );

      final badEngine = FakeDownloadEngine403(errorResponse);
      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: badEngine,
        permissionService: FakePermissionService(),
      );
      await provider.load();

      await provider.addDownload(
        name: '403.zip',
        url: 'https://example.com/403.zip',
        size: 0,
        category: '',
        savePath: '',
      );

      // Wait for the async task to complete and fail
      await Future<void>.delayed(const Duration(milliseconds: 100));

      expect(provider.tasks.first.status, DownloadStatus.failed);
      expect(
        provider.tasks.first.errorMessage,
        contains('403 Forbidden: Access denied'),
      );
    },
  );

  test(
    'load() auto-resume logic honors user pauses and wifi-waiting constraints',
    () async {
      final (database, settings) = await _setupServices();
      await settings.setAutoStart(true);
      await settings.setWifiOnly(false);

      // Create 3 tasks: 1 orphaned, 1 user-paused, 1 wifi-waiting
      final orphanTask = DownloadTask(
        id: '1',
        fileName: 'orphan.zip',
        url: 'http://a.com',
        fileSize: 100,
        downloadedBytes: 50,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: [0.5],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        errorMessage:
            'Paused because XDM was closed during a foreground download.',
      );
      final userPausedTask = DownloadTask(
        id: '2',
        fileName: 'user.zip',
        url: 'http://b.com',
        fileSize: 100,
        downloadedBytes: 50,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: [0.5],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        pausedByUser: true,
      );
      final wifiWaitingTask = DownloadTask(
        id: '3',
        fileName: 'wifi.zip',
        url: 'http://c.com',
        fileSize: 100,
        downloadedBytes: 50,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: [0.5],
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        errorMessage: 'Waiting for WiFi connection',
      );

      await database.saveTask(orphanTask);
      await database.saveTask(userPausedTask);
      await database.saveTask(wifiWaitingTask);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      await provider.load(pauseOrphanDownloads: false);
      // Wait briefly for the queue to pump
      await Future<void>.delayed(const Duration(milliseconds: 100));

      // The orphan task should be queued/downloading
      final t1 = provider.tasks.firstWhere((t) => t.id == '1');
      expect(
        t1.status,
        anyOf(DownloadStatus.queued, DownloadStatus.downloading),
      );

      // The user-paused task should remain paused
      final t2 = provider.tasks.firstWhere((t) => t.id == '2');
      expect(t2.status, DownloadStatus.paused);

      // The wifi-waiting task should remain paused (since wifi is simulated as available but task is explicitly waiting, actually the checkWifiOnly constraint might resume it if it's connected, wait, MockConnectivityPlatform returns wifi, so _resumeWaitingForWifi will unpause it!)
      // Wait, let's verify wifi task: _resumeWaitingForWifi sets it to queued if it was waiting for WiFi.
      // If we want it to stay paused, we should return mobile data in MockConnectivityPlatform, but it returns wifi.
      // Let's assert it got resumed because wifi is available.
      final t3 = provider.tasks.firstWhere((t) => t.id == '3');
      expect(
        t3.status,
        anyOf(DownloadStatus.queued, DownloadStatus.downloading),
      );
    },
  );

  test('pauseAllTasks pauses all non-completed/non-failed tasks', () async {
    final (database, settings) = await _setupServices();

    final t1 = DownloadTask(
      id: 'task_running',
      fileName: 'run.zip',
      url: 'https://example.com/run.zip',
      fileSize: 100,
      downloadedBytes: 10,
      category: 'Archive',
      status: DownloadStatus.downloading,
      savePath: 'build',
      localFilePath: 'build/run.zip',
      tempFilePath: 'build/run.zip.dmxpart',
      threadCount: 1,
      chunks: const [0.1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final t2 = DownloadTask(
      id: 'task_queued',
      fileName: 'queued.zip',
      url: 'https://example.com/queued.zip',
      fileSize: 100,
      downloadedBytes: 0,
      category: 'Archive',
      status: DownloadStatus.queued,
      savePath: 'build',
      localFilePath: 'build/queued.zip',
      tempFilePath: 'build/queued.zip.dmxpart',
      threadCount: 1,
      chunks: const [0.0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await database.saveTask(t1);
    await database.saveTask(t2);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    expect(
        provider.tasks[0].status,
        anyOf(DownloadStatus.paused, DownloadStatus.downloading,
            DownloadStatus.queued));

    await provider.pauseAllTasks();

    expect(provider.tasks.firstWhere((t) => t.id == 'task_running').status,
        DownloadStatus.paused);
    expect(provider.tasks.firstWhere((t) => t.id == 'task_queued').status,
        DownloadStatus.paused);
  });

  test('resumeAllTasks resumes paused tasks', () async {
    final (database, settings) = await _setupServices();

    final t1 = DownloadTask(
      id: 'paused_1',
      fileName: 'p1.zip',
      url: 'https://example.com/p1.zip',
      fileSize: 100,
      downloadedBytes: 10,
      category: 'Archive',
      status: DownloadStatus.paused,
      savePath: 'build',
      localFilePath: 'build/p1.zip',
      tempFilePath: 'build/p1.zip.dmxpart',
      threadCount: 1,
      chunks: const [0.1],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      pausedByUser: true,
    );

    await database.saveTask(t1);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    expect(provider.tasks.first.status, DownloadStatus.paused);

    await provider.resumeAllTasks();
    await Future<void>.delayed(const Duration(milliseconds: 50));

    expect(provider.tasks.first.status,
        anyOf(DownloadStatus.queued, DownloadStatus.downloading));
  });

  test('retryTask reads .dmxstate, not pre-allocated file length', () async {
    final tempFile = File('build/test_retry_prealloc.dmxpart');
    await tempFile.create(recursive: true);
    final raf = await tempFile.open(mode: FileMode.write);
    await raf.setPosition(99);
    await raf.writeByte(0);
    await raf.close();
    expect(tempFile.lengthSync(), 100);

    final stateFile = File('build/test_retry_prealloc.dmxpart.dmxstate');
    await stateFile
        .writeAsString('{"totalSize":100,"threadCount":2,"progress":[0,0]}');

    final (database, settings) = await _setupServices();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
    );

    final task = DownloadTask(
      id: 'prealloc-test-1',
      fileName: 'test.mp4',
      url: 'https://example.com/test.mp4',
      fileSize: 100,
      downloadedBytes: 100,
      category: 'Video',
      status: DownloadStatus.failed,
      savePath: 'build',
      localFilePath: 'build/test.mp4',
      tempFilePath: 'build/test_retry_prealloc.dmxpart',
      threadCount: 2,
      chunks: const [0.0, 0.0],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await database.saveTask(task);
    await provider.load();
    await provider.retryTask('prealloc-test-1');

    final updated = provider.tasks.firstWhere((t) => t.id == 'prealloc-test-1');
    expect(updated.downloadedBytes, 0);

    try {
      await tempFile.delete();
    } catch (_) {}
    try {
      if (await stateFile.exists()) await stateFile.delete();
    } catch (_) {}
  });

  test(
      'load() invalidates filteredTasks cache so tasks loaded from DB appear in filteredTasks immediately',
      () async {
    final (database, settings) = await _setupServices();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
    );

    final pausedTask = DownloadTask(
      id: 'load-cache-test-1',
      fileName: 'test.zip',
      url: 'https://example.com/test.zip',
      fileSize: 1000,
      downloadedBytes: 0,
      threadCount: 1,
      chunks: const [0.0],
      category: 'Archive',
      status: DownloadStatus.paused,
      savePath: 'build',
      localFilePath: 'build/test.zip',
      tempFilePath: 'build/test.dmxpart',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
    await database.saveTask(pausedTask);

    // Access filteredTasks BEFORE load() to simulate initial Flutter frame building with empty tasks
    expect(provider.filteredTasks, isEmpty);

    // Now call load()
    await provider.load();

    // filteredTasks MUST now reflect the task loaded from DB
    expect(provider.filteredTasks.length, 1);
    expect(provider.filteredTasks.first.id, 'load-cache-test-1');
  });

  group('Download Lifecycle Audit Fixes', () {
    test('cancelTask sets pausedByUser true and _autoResumeIncomplete skips it',
        () async {
      final (database, settings) = await _setupServices();
      final task = DownloadTask(
        id: 'cancel-audit-1',
        fileName: 'cancel.zip',
        url: 'https://example.com/cancel.zip',
        fileSize: 1000,
        downloadedBytes: 200,
        threadCount: 1,
        chunks: const [0.2],
        category: 'Archive',
        status: DownloadStatus.downloading,
        savePath: 'build',
        localFilePath: 'build/cancel.zip',
        tempFilePath: 'build/cancel.dmxpart',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      await database.saveTask(task);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      await provider.load();

      await provider.cancelTask('cancel-audit-1');

      final cancelledTask =
          provider.tasks.firstWhere((t) => t.id == 'cancel-audit-1');
      expect(cancelledTask.status, DownloadStatus.failed);
      expect(cancelledTask.errorMessage, 'Transfer cancelled.');
      expect(cancelledTask.pausedByUser, isTrue);
    });

    test('resumeTask on completed seeding torrent re-enables seeding',
        () async {
      final (database, settings) = await _setupServices();
      final task = DownloadTask(
        id: 'seeding-resume-1',
        fileName: 'torrent.iso',
        url: 'magnet:?xt=urn:btih:1234567890abcdef1234567890abcdef12345678',
        fileSize: 1000,
        downloadedBytes: 1000,
        threadCount: 1,
        chunks: const [1.0],
        category: 'Archive',
        status: DownloadStatus.completed,
        savePath: 'build',
        localFilePath: 'build/torrent.iso',
        tempFilePath: 'build/torrent.dmxpart',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        seedingEnabled: false,
      );
      await database.saveTask(task);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      await provider.load();

      await provider.resumeTask('seeding-resume-1');

      final resumed =
          provider.tasks.firstWhere((t) => t.id == 'seeding-resume-1');
      expect(resumed.seedingEnabled, isTrue);
    });

    test('torrentBytesFromFiles handles null/unset selected flag consistently',
        () {
      final files = [
        {
          'name': 'a.txt',
          'downloadedBytes': 100,
          'length': 200,
          'selected': true
        },
        {'name': 'b.txt', 'downloadedBytes': 300, 'length': 400},
        {
          'name': 'c.txt',
          'downloadedBytes': 500,
          'length': 600,
          'selected': false
        },
      ];

      final downloaded = DownloadProvider.torrentBytesFromFiles(files);
      final total = DownloadProvider.torrentSelectedFilesTotalSize(files);

      expect(downloaded, 400);
      expect(total, 600);
    });

    test('reconcileChunks handles thread count redistribution & scaling', () {
      final rescaled = DownloadProvider.reconcileChunks(
        stateChunks: [0.2, 0.2],
        actualBytesOnDisk: 500,
        fileSize: 1000,
        threadCount: 2,
      );
      expect(rescaled, [0.5, 0.5]);

      final redistributed = DownloadProvider.reconcileChunks(
        stateChunks: [0.5, 0.5, 0.5, 0.5],
        actualBytesOnDisk: 500,
        fileSize: 1000,
        threadCount: 2,
      );
      expect(redistributed, [0.5, 0.5]);
    });

    test('Bug 3: _autoResumeIncomplete wifi-only and waiting-network pauses', () async {
      MockConnectivityPlatform.results = [ConnectivityResult.none];
      addTearDown(() {
        MockConnectivityPlatform.results = [ConnectivityResult.wifi];
      });

      final (database, settings) = await _setupServices();
      final now = DateTime.now();

      final task1 = DownloadTask(
        id: 'user_paused',
        fileName: 'a.zip',
        url: 'https://example.com/a.zip',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
        pausedByUser: true,
      );

      final task2 = DownloadTask(
        id: 'waiting_wifi',
        fileName: 'b.zip',
        url: 'https://example.com/b.zip',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
        pausedByUser: false,
        errorMessage: DownloadStatusMessages.waitingWifi,
      );

      final task3 = DownloadTask(
        id: 'waiting_network',
        fileName: 'c.zip',
        url: 'https://example.com/c.zip',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
        pausedByUser: false,
        errorMessage: DownloadStatusMessages.waitingNetwork,
      );

      final task4 = DownloadTask(
        id: 'normal_paused',
        fileName: 'd.zip',
        url: 'https://example.com/d.zip',
        fileSize: 100,
        downloadedBytes: 10,
        category: 'Archive',
        status: DownloadStatus.paused,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.1],
        createdAt: now,
        updatedAt: now,
        pausedByUser: false,
      );

      await database.saveTask(task1);
      await database.saveTask(task2);
      await database.saveTask(task3);
      await database.saveTask(task4);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      settings.autoStart = true;
      await provider.load();

      expect(provider.tasks.firstWhere((t) => t.id == 'user_paused').status, DownloadStatus.paused);
      expect(provider.tasks.firstWhere((t) => t.id == 'waiting_wifi').status, DownloadStatus.paused);
      expect(provider.tasks.firstWhere((t) => t.id == 'waiting_network').status, DownloadStatus.paused);
      expect(provider.tasks.firstWhere((t) => t.id == 'normal_paused').status, DownloadStatus.queued);
    });

    test('Bug 4: retryTask resets metadata when isUnrecoverable is true', () async {
      final (database, settings) = await _setupServices();
      final now = DateTime.now();

      final task = DownloadTask(
        id: 'retry_unrecoverable',
        fileName: 'checksum_fail.zip',
        url: 'https://example.com/file.zip',
        fileSize: 1000,
        downloadedBytes: 500,
        videoStreamSize: 800,
        audioSize: 200,
        audioDownloadedBytes: 100,
        category: 'Archive',
        status: DownloadStatus.failed,
        errorMessage: 'Checksum verification failed',
        savePath: 'build',
        localFilePath: 'build/file.zip',
        tempFilePath: 'build/file.zip.dmxpart',
        threadCount: 2,
        chunks: const [0.5, 0.5],
        createdAt: now,
        updatedAt: now,
      );
      await database.saveTask(task);

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      settings.autoStart = false;
      await provider.load();

      await provider.retryTask('retry_unrecoverable');

      final updatedTask = provider.tasks.firstWhere((t) => t.id == 'retry_unrecoverable');
      expect(updatedTask.downloadedBytes, 0);
      expect(updatedTask.videoStreamSize, 0);
      expect(updatedTask.audioDownloadedBytes, 0);
    });

    test('Bug 6: youtubeStreamIdentityChanged detects actual stream changes', () {
      const urlOld = 'https://r5---sn-5uaezney.googlevideo.com/videoplayback?expire=1627000000&itag=22&mime=video%2Fmp4';
      const urlNewSame = 'https://r5---sn-5uaezney.googlevideo.com/videoplayback?expire=1627050000&itag=22&mime=video%2Fmp4';
      const urlNewDiffItag = 'https://r5---sn-5uaezney.googlevideo.com/videoplayback?expire=1627050000&itag=137&mime=video%2Fmp4';
      const urlNewDiffHost = 'https://r1---sn-abc.googlevideo.com/videoplayback?expire=1627050000&itag=22&mime=video%2Fmp4';

      expect(DownloadProvider.youtubeStreamIdentityChanged(urlOld, urlNewSame), isFalse);
      expect(DownloadProvider.youtubeStreamIdentityChanged(urlOld, urlNewDiffItag), isTrue);
      expect(DownloadProvider.youtubeStreamIdentityChanged(urlOld, urlNewDiffHost), isTrue);
    });

    test('Bug 6 & 7: retryTask YouTube refresh handles same-identity and different-identity', () async {
      final (database, settings) = await _setupServices();
      final now = DateTime.now();

      // Create dummy files for same-identity retry
      final tempVideoSame = File('build/yt_same.mp4.dmxpart');
      final tempStateSame = File('build/yt_same.mp4.dmxpart.dmxstate');
      await tempVideoSame.create(recursive: true);
      await tempVideoSame.writeAsBytes(List.filled(500, 0));
      await tempStateSame.create(recursive: true);
      await tempStateSame.writeAsString(jsonEncode({
        'totalSize': 1000,
        'threadCount': 1,
        'progress': [500],
      }));

      final taskSame = DownloadTask(
        id: 'yt_same_task',
        fileName: 'yt_same.mp4',
        url: 'https://googlevideo.com/playback?expire=1000&itag=22&mime=video%2Fmp4', // expired
        fileSize: 1000,
        downloadedBytes: 500,
        category: 'Video',
        status: DownloadStatus.failed,
        savePath: 'build',
        localFilePath: 'build/yt_same.mp4',
        tempFilePath: 'build/yt_same.mp4.dmxpart',
        threadCount: 1,
        chunks: const [0.5],
        createdAt: now,
        updatedAt: now,
        youtubeQualityPreset: '720p',
        downloadPageUrl: 'https://youtube.com/watch?v=same',
      );
      await database.saveTask(taskSame);

      // Create dummy files for diff-identity retry
      final tempVideoDiff = File('build/yt_diff.mp4.dmxpart');
      final tempStateDiff = File('build/yt_diff.mp4.dmxpart.dmxstate');
      await tempVideoDiff.create(recursive: true);
      await tempVideoDiff.writeAsBytes(List.filled(500, 0));
      await tempStateDiff.create(recursive: true);
      await tempStateDiff.writeAsString(jsonEncode({
        'totalSize': 1000,
        'threadCount': 1,
        'progress': [500],
      }));

      final taskDiff = DownloadTask(
        id: 'yt_diff_task',
        fileName: 'yt_diff.mp4',
        url: 'https://googlevideo.com/playback?expire=1000&itag=22&mime=video%2Fmp4', // expired
        fileSize: 1000,
        downloadedBytes: 500,
        category: 'Video',
        status: DownloadStatus.failed,
        savePath: 'build',
        localFilePath: 'build/yt_diff.mp4',
        tempFilePath: 'build/yt_diff.mp4.dmxpart',
        threadCount: 1,
        chunks: const [0.5],
        createdAt: now,
        updatedAt: now,
        youtubeQualityPreset: '720p',
        downloadPageUrl: 'https://youtube.com/watch?v=diff',
      );
      await database.saveTask(taskDiff);

      // Stub YoutubeService.getFreshStreams
      YoutubeService.mockGetFreshStreams = (pageUrl, {preferredType}) async {
        if (pageUrl.contains('same')) {
          // returns same itag/mime, different signature/expire
          return {
            'url': 'https://googlevideo.com/playback?expire=999999&itag=22&mime=video%2Fmp4',
            'audioUrl': null,
          };
        } else {
          // returns different itag
          return {
            'url': 'https://googlevideo.com/playback?expire=999999&itag=137&mime=video%2Fmp4',
            'audioUrl': null,
          };
        }
      };

      final provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: FakeDownloadEngine(),
        permissionService: FakePermissionService(),
      );
      settings.autoStart = false;
      await provider.load();

      // Retry same task -> should preserve downloadedBytes and files
      await provider.retryTask('yt_same_task');
      final updatedSame = provider.tasks.firstWhere((t) => t.id == 'yt_same_task');
      expect(updatedSame.downloadedBytes, 500);
      expect(await tempVideoSame.exists(), isTrue);

      // Retry diff task -> should reset downloadedBytes to 0 and delete files
      await provider.retryTask('yt_diff_task');
      final updatedDiff = provider.tasks.firstWhere((t) => t.id == 'yt_diff_task');
      expect(updatedDiff.downloadedBytes, 0);
      expect(await tempVideoDiff.exists(), isFalse);
      expect(await tempStateDiff.exists(), isFalse);

      // Cleanup
      if (await tempVideoSame.exists()) await tempVideoSame.delete();
      if (await tempStateSame.exists()) await tempStateSame.delete();
      YoutubeService.mockGetFreshStreams = null;
    });
  });
}

class FakeDownloadEngine403 extends DownloadEngine {
  final Response response;
  FakeDownloadEngine403(this.response);

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? referer,
    String? customUserAgent,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
    CancelToken? cancelToken,
  }) async {
    return const DownloadMetadata(
      fileName: '403.zip',
      category: 'Archive',
      fileSize: 0,
      supportsResume: false,
    );
  }

  @override
  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    bool isRetry = false,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    bool bypassSSL = false,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
  }) async {
    throw DioException(
      requestOptions: response.requestOptions,
      type: DioExceptionType.badResponse,
      response: response,
      message: 'Server returned status code 403',
    );
  }
}
