import 'dart:async';

import 'package:dio/dio.dart';
import 'package:dmx/core/services/database_service.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/permission_service.dart';
import 'package:dmx/features/downloads/models/download_task.dart';
import 'package:dmx/features/downloads/provider/download_provider.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';

class MockConnectivityPlatform extends ConnectivityPlatform {
  @override
  Future<List<ConnectivityResult>> checkConnectivity() async {
    return [ConnectivityResult.wifi];
  }

  @override
  Stream<List<ConnectivityResult>> get onConnectivityChanged {
    return Stream.value([ConnectivityResult.wifi]);
  }
}

class FakeDownloadEngine extends DownloadEngine {
  final startedUrls = <String>[];

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? referer,
    String? customUserAgent,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
  }) async {
    return DownloadMetadata(
      fileName: requestedFileName ?? 'file.zip',
      category: 'Archive',
      fileSize: 100,
      supportsResume: true,
    );
  }

  @override
  Future<void> download({
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    String? referer,
    String? customUserAgent,
    String? cookies,
    String? oauthToken,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
  }) {
    startedUrls.add(url);
    final completer = Completer<void>();
    cancelToken.whenCancel.then((_) {
      if (!completer.isCompleted) {
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: url),
            type: DioExceptionType.cancel,
          ),
        );
      }
    });
    return completer.future;
  }
}

class FakePermissionService extends PermissionService {
  @override
  Future<String> defaultDownloadDirectory() async => 'build/test_downloads';

  @override
  Future<bool> ensureStorageAccess() async => true;
}

Future<(DatabaseService, SettingsProvider)> _setupServices() async {
  SharedPreferences.setMockInitialValues({});
  if (!Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
    await Hive.openBox<dynamic>(DatabaseService.downloadsBoxName);
  }
  await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();

  final database = DatabaseService();
  await database.init(testPath: 'build/test_hive_provider');
  final settings = SettingsProvider();
  await settings.load();
  return (database, settings);
}

void main() {
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    Hive.init('build/test_hive_provider');
    ConnectivityPlatform.instance = MockConnectivityPlatform();

    // Register mock handlers for platform channels
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('com.example.dmx/widget'),
      (methodCall) async => null,
    );
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('plugins.it_nomads.com/flutter_secure_storage'),
      (methodCall) async {
        switch (methodCall.method) {
          case 'read':
            return null;
          case 'write':
          case 'delete':
          case 'containsKey':
          case 'readAll':
          default:
            return null;
        }
      },
    );
  });

  tearDown(() async {
    if (Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
      await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();
    }
  });

  test('load converts stale downloading tasks to paused', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    await database.saveTask(
      DownloadTask(
        id: 'stale',
        fileName: 'stale.zip',
        url: 'https://example.com/stale.zip',
        fileSize: 100,
        downloadedBytes: 10,
        category: 'Archive',
        status: DownloadStatus.downloading,
        savePath: 'build',
        localFilePath: 'build/stale.zip',
        tempFilePath: 'build/stale.zip.dmxpart',
        threadCount: 2,
        chunks: const [0.1, 0.1],
        createdAt: now,
        updatedAt: now,
      ),
    );

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    // Disable auto-resume so the test verifies orphan-pausing behavior
    settings.autoStart = false;
    await provider.load();

    expect(provider.tasks.single.status, DownloadStatus.paused);
    expect(provider.tasks.single.speed, 0);
  });

  test('addDownload respects maxDownloads and queues overflow', () async {
    final (database, settings) = await _setupServices();
    await settings.setMaxDownloads(1);
    final engine = FakeDownloadEngine();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: engine,
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: 'one.zip',
      url: 'https://example.com/one.zip',
      size: 0,
      category: '',
      savePath: '',
    );
    await provider.addDownload(
      name: 'two.zip',
      url: 'https://example.com/two.zip',
      size: 0,
      category: '',
      savePath: '',
    );

    await Future<void>.delayed(const Duration(milliseconds: 50));

    expect(provider.downloadingTasksCount, 1);
    expect(provider.queuedTasksCount, 1);
    expect(engine.startedUrls, ['https://example.com/one.zip']);
  });


  test('updateTaskThreadCount on task with zero progress only resizes chunks', () async {
    final (database, settings) = await _setupServices();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    settings.autoStart = false;
    await provider.load();

    await provider.addDownload(
      name: 'test.zip',
      url: 'https://example.com/test.zip',
      size: 100,
      category: '',
      savePath: '',
      threadCount: 2,
    );

    final taskId = provider.tasks.first.id;
    expect(provider.tasks.first.threadCount, 2);
    expect(provider.tasks.first.chunks.length, 2);

    await provider.updateTaskThreadCount(taskId, 5);
    expect(provider.tasks.first.threadCount, 5);
    expect(provider.tasks.first.chunks.length, 5);
    expect(provider.tasks.first.downloadedBytes, 0);
  });

  test('updateTaskThreadCount on task with non-zero progress resets progress and chunks', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    final task = DownloadTask(
      id: 'active_task',
      fileName: 'active.zip',
      url: 'https://example.com/active.zip',
      fileSize: 100,
      downloadedBytes: 50,
      category: 'Archive',
      status: DownloadStatus.paused,
      savePath: 'build',
      localFilePath: 'build/active.zip',
      tempFilePath: 'build/active.zip.dmxpart',
      threadCount: 2,
      chunks: const [0.5, 0.5],
      createdAt: now,
      updatedAt: now,
    );
    await database.saveTask(task);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    expect(provider.tasks.first.downloadedBytes, 50);
    expect(provider.tasks.first.threadCount, 2);

    await provider.updateTaskThreadCount('active_task', 4);
    expect(provider.tasks.first.threadCount, 4);
    expect(provider.tasks.first.chunks.length, 4);
    expect(provider.tasks.first.downloadedBytes, 0);
    expect(provider.tasks.first.status, DownloadStatus.paused);
  });

  test('load with pauseOrphanDownloads=false preserves active downloads', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    await database.saveTask(
      DownloadTask(
        id: 'active',
        fileName: 'active.zip',
        url: 'https://example.com/active.zip',
        fileSize: 100,
        downloadedBytes: 10,
        category: 'Archive',
        status: DownloadStatus.downloading,
        savePath: 'build',
        localFilePath: 'build/active.zip',
        tempFilePath: 'build/active.zip.dmxpart',
        threadCount: 2,
        chunks: const [0.1, 0.1],
        createdAt: now,
        updatedAt: now,
      ),
    );

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    // Disable auto-resume to verify pause-orphan behavior in isolation
    settings.autoStart = false;
    await provider.load();
    expect(provider.tasks.single.status, DownloadStatus.paused);

    // Simulate a fresh provider reload (e.g. pull-to-refresh).
    await provider.load(pauseOrphanDownloads: false);
    expect(
      provider.tasks.single.status,
      DownloadStatus.paused,
      reason: 'No active stream → still paused on subsequent load',
    );

    // Now add a fake active stream; reload should not pause it.
    final second = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    settings.autoStart = false;
    await second.load();
    // No active stream from outside; the cancelTokens map is empty. So
    // the "in-flight" condition can't be triggered from outside. The
    // important regression test is the previous assertion (downloads
    // started by a previous load are not silently paused on a user
    // refresh).
  });

  test('retryTask does not zero downloadedBytes or chunks', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    final task = DownloadTask(
      id: 'retry_target',
      fileName: 'resume.zip',
      url: 'https://example.com/resume.zip',
      fileSize: 200,
      downloadedBytes: 80,
      category: 'Archive',
      status: DownloadStatus.failed,
      savePath: 'build',
      localFilePath: 'build/resume.zip',
      tempFilePath: 'build/resume.zip.dmxpart',
      threadCount: 2,
      chunks: const [0.4, 0.4],
      createdAt: now,
      updatedAt: now,
    );
    await database.saveTask(task);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    settings.autoStart = false;
    await provider.load();

    await provider.retryTask('retry_target');
    expect(provider.tasks.first.downloadedBytes, 80,
        reason: 'retry must preserve the on-disk resume state');
    expect(provider.tasks.first.chunks, [0.4, 0.4]);
    expect(provider.tasks.first.status, anyOf(
      DownloadStatus.queued,
      DownloadStatus.downloading,
    ));
  });

  test('categorySizes ignores failed and unknown categories', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    final tasks = [
      DownloadTask(
        id: 'a',
        fileName: 'a.mp4',
        url: 'https://x/a.mp4',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Video',
        status: DownloadStatus.failed,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
      ),
      DownloadTask(
        id: 'b',
        fileName: 'b.mp4',
        url: 'https://x/b.mp4',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Video',
        status: DownloadStatus.queued,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [0.0],
        createdAt: now,
        updatedAt: now,
      ),
      DownloadTask(
        id: 'c',
        fileName: 'c.mp4',
        url: 'https://x/c.mp4',
        fileSize: 100,
        downloadedBytes: 0,
        category: 'Alien', // unknown category
        status: DownloadStatus.completed,
        savePath: '',
        localFilePath: '',
        tempFilePath: '',
        threadCount: 1,
        chunks: const [1.0],
        createdAt: now,
        updatedAt: now,
      ),
    ];
    for (final t in tasks) {
      await database.saveTask(t);
    }

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    final sizes = provider.categorySizes;
    expect(sizes['Video'] ?? 0.0, lessThan(0.001),
        reason: 'Failed/queued tasks must not contribute to disk usage');
    expect(sizes.containsKey('Alien'), false,
        reason: 'Unknown categories must not be silently dropped into the map');
  });

  test('updateTorrentTaskFiles updates torrent selection and file size correctly', () async {
    final (database, settings) = await _setupServices();
    final now = DateTime.now();
    final task = DownloadTask(
      id: 'torrent_test',
      fileName: 'test.torrent',
      url: 'file:///path/test.torrent',
      fileSize: 300,
      downloadedBytes: 0,
      category: 'Archive',
      status: DownloadStatus.paused,
      savePath: '',
      localFilePath: '',
      tempFilePath: '',
      threadCount: 1,
      chunks: const [0.0],
      createdAt: now,
      updatedAt: now,
      torrentFiles: const [
        {'name': 'file1.txt', 'length': 100, 'selected': true},
        {'name': 'file2.txt', 'length': 200, 'selected': true},
      ],
    );
    await database.saveTask(task);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    expect(provider.tasks.first.fileSize, 300);

    // Unselect file1.txt
    final updatedFiles = [
      {'name': 'file1.txt', 'length': 100, 'selected': false},
      {'name': 'file2.txt', 'length': 200, 'selected': true},
    ];
    await provider.updateTorrentTaskFiles('torrent_test', updatedFiles);

    expect(provider.tasks.first.torrentFiles![0]['selected'], false);
    expect(provider.tasks.first.fileSize, 200); // 300 - 100
  });

  test('DownloadProvider handles 403 Forbidden error and does not retry', () async {
    final (database, settings) = await _setupServices();
    await settings.setAutoRetryEnabled(true);
    await settings.setMaxDownloads(2);

    final errorResponse = Response(
      requestOptions: RequestOptions(path: 'https://example.com/403.zip'),
      statusCode: 403,
      statusMessage: DownloadStatusMessages.forbidden,
    );
    
    final badEngine = FakeDownloadEngine403(errorResponse);
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: badEngine,
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: '403.zip',
      url: 'https://example.com/403.zip',
      size: 0,
      category: '',
      savePath: '',
    );

    // Wait for the async task to complete and fail
    await Future<void>.delayed(const Duration(milliseconds: 100));

    expect(provider.tasks.first.status, DownloadStatus.failed);
    expect(provider.tasks.first.errorMessage, contains('403 Forbidden: Access denied'));
  });

  test('load() auto-resume logic honors user pauses and wifi-waiting constraints', () async {
    final (database, settings) = await _setupServices();
    await settings.setAutoStart(true);
    await settings.setWifiOnly(false);

    // Create 3 tasks: 1 orphaned, 1 user-paused, 1 wifi-waiting
    final orphanTask = DownloadTask(
      id: '1', fileName: 'orphan.zip', url: 'http://a.com', fileSize: 100, downloadedBytes: 50,
      category: 'Archive', status: DownloadStatus.paused, savePath: '', localFilePath: '', tempFilePath: '',
      threadCount: 1, chunks: [0.5], createdAt: DateTime.now(), updatedAt: DateTime.now(),
      errorMessage: 'Paused because XDM was closed during a foreground download.',
    );
    final userPausedTask = DownloadTask(
      id: '2', fileName: 'user.zip', url: 'http://b.com', fileSize: 100, downloadedBytes: 50,
      category: 'Archive', status: DownloadStatus.paused, savePath: '', localFilePath: '', tempFilePath: '',
      threadCount: 1, chunks: [0.5], createdAt: DateTime.now(), updatedAt: DateTime.now(),
      pausedByUser: true,
    );
    final wifiWaitingTask = DownloadTask(
      id: '3', fileName: 'wifi.zip', url: 'http://c.com', fileSize: 100, downloadedBytes: 50,
      category: 'Archive', status: DownloadStatus.paused, savePath: '', localFilePath: '', tempFilePath: '',
      threadCount: 1, chunks: [0.5], createdAt: DateTime.now(), updatedAt: DateTime.now(),
      errorMessage: 'Waiting for WiFi connection',
    );

    await database.saveTask(orphanTask);
    await database.saveTask(userPausedTask);
    await database.saveTask(wifiWaitingTask);

    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load(pauseOrphanDownloads: false);
    // Wait briefly for the queue to pump
    await Future<void>.delayed(const Duration(milliseconds: 100));

    // The orphan task should be queued/downloading
    final t1 = provider.tasks.firstWhere((t) => t.id == '1');
    expect(t1.status, anyOf(DownloadStatus.queued, DownloadStatus.downloading));

    // The user-paused task should remain paused
    final t2 = provider.tasks.firstWhere((t) => t.id == '2');
    expect(t2.status, DownloadStatus.paused);

    // The wifi-waiting task should remain paused (since wifi is simulated as available but task is explicitly waiting, actually the checkWifiOnly constraint might resume it if it's connected, wait, MockConnectivityPlatform returns wifi, so _resumeWaitingForWifi will unpause it!)
    // Wait, let's verify wifi task: _resumeWaitingForWifi sets it to queued if it was waiting for WiFi.
    // If we want it to stay paused, we should return mobile data in MockConnectivityPlatform, but it returns wifi.
    // Let's assert it got resumed because wifi is available.
    final t3 = provider.tasks.firstWhere((t) => t.id == '3');
    expect(t3.status, anyOf(DownloadStatus.queued, DownloadStatus.downloading));
  });
}

class FakeDownloadEngine403 extends DownloadEngine {
  final Response response;
  FakeDownloadEngine403(this.response);

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? referer,
    String? customUserAgent,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
  }) async {
    return DownloadMetadata(
      fileName: '403.zip',
      category: 'Archive',
      fileSize: 0,
      supportsResume: false,
    );
  }

  @override
  Future<void> download({
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
  }) async {
    throw DioException(
      requestOptions: response.requestOptions,
      type: DioExceptionType.badResponse,
      response: response,
      message: 'Server returned status code 403',
    );
  }
}
