import 'dart:async';
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:dmx/core/services/database_service.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/permission_service.dart';
import 'package:dmx/features/downloads/models/download_task.dart';
import 'package:dmx/features/downloads/provider/download_provider.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';


import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';



late String uniqueHivePath;

class MockConnectivityPlatform extends ConnectivityPlatform {
  @override
  Future<List<ConnectivityResult>> checkConnectivity() async {
    return [ConnectivityResult.wifi];
  }

  @override
  Stream<List<ConnectivityResult>> get onConnectivityChanged {
    return Stream.value([ConnectivityResult.wifi]);
  }
}

class FakeDownloadEngine extends DownloadEngine {
  final startedUrls = <String>[];
  final knownFileSizes = <String, int>{};

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? customUserAgent,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
  }) async {
    return DownloadMetadata(
      fileName: requestedFileName ?? 'file.zip',
      category: 'Archive',
      fileSize: 100,
      supportsResume: true,
    );
  }

  @override
  Future<void> download({
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    String? customUserAgent,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    List<Map<String, dynamic>>? torrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
  }) {
    startedUrls.add(url);
    knownFileSizes[url] = knownFileSize;
    final completer = Completer<void>();
    
    Timer(const Duration(milliseconds: 10), () {
      onProgress(DownloadProgress(
        downloadedBytes: 50,
        fileSize: knownFileSize,
        speed: 1000,
        eta: 1,
      ));
    });

    Timer(const Duration(milliseconds: 20), () {
      onProgress(DownloadProgress(
        downloadedBytes: knownFileSize,
        fileSize: knownFileSize,
        speed: 1000,
        eta: 0,
      ));
      try {
        final f = File(tempFilePath);
        f.createSync(recursive: true);
        f.writeAsBytesSync(List.filled(10, 0));
      } catch (_) {}
      if (!completer.isCompleted) {
        completer.complete();
      }
    });

    cancelToken.whenCancel.then((_) {
      if (!completer.isCompleted) {
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: url),
            type: DioExceptionType.cancel,
          ),
        );
      }
    });
    return completer.future;
  }
}

class FakePermissionService extends PermissionService {
  @override
  Future<String> defaultDownloadDirectory() async => 'build/test_downloads';

  @override
  Future<bool> ensureStorageAccess() async => true;
}

Future<(DatabaseService, SettingsProvider)> _setupServices() async {
  SharedPreferences.setMockInitialValues({});
  if (!Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
    await Hive.openBox<dynamic>(DatabaseService.downloadsBoxName);
  }
  await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();

  final database = DatabaseService();
  await database.init();
  final settings = SettingsProvider();
  await settings.load();
  return (database, settings);
}

void main() {
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    uniqueHivePath = 'build/test_hive_int_${DateTime.now().microsecondsSinceEpoch}';
    try {
      final dir = Directory(uniqueHivePath);
      if (dir.existsSync()) {
        dir.deleteSync(recursive: true);
      }
    } catch (_) {}
    Hive.init(uniqueHivePath);
    ConnectivityPlatform.instance = MockConnectivityPlatform();



    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('com.example.dmx/widget'),
      (methodCall) async => null,
    );
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('plugins.it_nomads.com/flutter_secure_storage'),
      (methodCall) async {
        switch (methodCall.method) {
          case 'read':
            return null;
          case 'write':
          case 'delete':
          case 'containsKey':
          case 'readAll':
          default:
            return null;
        }
      },
    );
  });

  tearDown(() async {
    if (Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
      await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();
    }
  });

  tearDownAll(() async {
    await Hive.close();
    try {
      final dir = Directory(uniqueHivePath);
      if (dir.existsSync()) {
        dir.deleteSync(recursive: true);
      }
    } catch (_) {}
  });

  test('DownloadProvider full download flow and pause/resume', () async {
    final (database, settings) = await _setupServices();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: 'test_flow.zip',
      url: 'https://example.com/test_flow.zip',
      size: 100,
      category: 'Archive',
      savePath: 'build/test_downloads',
    );

    expect(provider.tasks.length, 1);
    final taskId = provider.tasks.first.id;
    expect(provider.tasks.first.status, anyOf(DownloadStatus.downloading, DownloadStatus.queued));

    await provider.pauseTask(taskId);
    expect(provider.tasks.first.status, DownloadStatus.paused);

    await provider.resumeTask(taskId);
    expect(provider.tasks.first.status, anyOf(DownloadStatus.downloading, DownloadStatus.queued));

    for (int i = 0; i < 50; i++) {
      if (provider.tasks.first.status == DownloadStatus.completed) {
        break;
      }
      await Future.delayed(const Duration(milliseconds: 5));
    }
    expect(provider.tasks.first.status, DownloadStatus.completed);
  });

  test('DownloadProvider YouTube merge flow', () async {
    final (database, settings) = await _setupServices();
    final engine = FakeDownloadEngine();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: engine,
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: 'youtube_video.mp4',
      url: 'https://example.com/video',
      size: 100,
      category: 'Video',
      savePath: 'build/test_downloads',
      mergedAudioUrl: 'https://example.com/audio',
      audioSize: 50,
    );

    expect(provider.tasks.length, 1);

    // Wait for the video download phase, then audio phase, then merge phase
    for (int i = 0; i < 100; i++) {
      if (provider.tasks.first.status == DownloadStatus.failed ||
          provider.tasks.first.status == DownloadStatus.completed) {
        break;
      }
      await Future.delayed(const Duration(milliseconds: 10));
    }

    // In a test environment without real ffmpeg binary, the merge phase will throw an exception
    // (FFmpeg merge failed).
    // The provider should catch this and transition the task to failed.
    expect(provider.tasks.first.status, DownloadStatus.failed);
    expect(engine.knownFileSizes['https://example.com/video'], 50,
        reason: 'Combined tasks must request only the video stream length.');
    expect(provider.tasks.first.errorMessage, contains('FFmpeg merge failed'));
  });

}
