import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';
import 'package:dio/dio.dart';
import 'package:dmx/core/services/database_service.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/permission_service.dart';
import 'package:dmx/features/downloads/models/download_task.dart';
import 'package:dmx/features/downloads/provider/download_provider.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:drift/drift.dart' as drift;
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

late String uniqueHivePath;

class MockConnectivityPlatform extends ConnectivityPlatform {
  @override
  Future<List<ConnectivityResult>> checkConnectivity() async {
    return [ConnectivityResult.wifi];
  }

  @override
  Stream<List<ConnectivityResult>> get onConnectivityChanged {
    return Stream.value([ConnectivityResult.wifi]);
  }
}

class FakeDownloadEngine extends DownloadEngine {
  final startedUrls = <String>[];
  final knownFileSizes = <String, int>{};

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? referer,
    String? customUserAgent,
    String? cookies,
    String? oauthToken,
    CancelToken? cancelToken,
  }) async {
    return DownloadMetadata(
      fileName: requestedFileName ?? 'file.zip',
      category: 'Archive',
      fileSize: 100,
      supportsResume: true,
    );
  }

  @override
  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    bool isRetry = false,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    int? metadataTimeoutSeconds,
  }) {
    startedUrls.add(url);
    knownFileSizes[url] = knownFileSize;
    final completer = Completer<void>();
    var cancelled = false;

    void writeOutput(String path, int size) {
      if (path.isEmpty) return;
      try {
        final f = File(path);
        f.createSync(recursive: true);
        f.writeAsBytesSync(List.filled(size > 0 ? size : 10, 0));
        File('$path.dmxstate').writeAsStringSync(
          jsonEncode({
            'chunks': [
              {'downloaded': size > 0 ? size : 10},
            ],
          }),
        );
      } catch (_) {}
    }

    if (cancelToken.isCancelled) {
      cancelled = true;
      completer.completeError(
        DioException(
          requestOptions: RequestOptions(path: url),
          type: DioExceptionType.cancel,
        ),
      );
      return completer.future;
    }

    Timer(const Duration(milliseconds: 10), () {
      if (cancelled) return;
      onProgress(DownloadProgress(
        downloadedBytes: (knownFileSize / 2).round(),
        fileSize: knownFileSize,
        speed: 1000,
        eta: 1,
        cycleState: CycleState.downloading,
      ));
    });

    Timer(const Duration(milliseconds: 50), () {
      if (cancelled || completer.isCompleted) return;
      onProgress(DownloadProgress(
        downloadedBytes: knownFileSize,
        fileSize: knownFileSize,
        speed: 1000,
        eta: 0,
        cycleState: CycleState.downloading,
      ));
      writeOutput(tempFilePath, knownFileSize);
      writeOutput(localFilePath, knownFileSize);
      if (!completer.isCompleted) {
        completer.complete();
      }
    });

    cancelToken.whenCancel.then((_) {
      cancelled = true;
      if (!completer.isCompleted) {
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: url),
            type: DioExceptionType.cancel,
          ),
        );
      }
    });
    return completer.future;
  }
}

class FakePermissionService extends PermissionService {
  @override
  Future<String> defaultDownloadDirectory() async => 'build/test_downloads';

  @override
  Future<bool> ensureStorageAccess() async => true;
}

Future<(DatabaseService, SettingsProvider)> _setupServices() async {
  SharedPreferences.setMockInitialValues({});
  ConnectivityPlatform.instance = MockConnectivityPlatform();
  final path = '${uniqueHivePath}_${DateTime.now().microsecondsSinceEpoch}';
  final database = DatabaseService.forSubclass();
  await database.init(testPath: path);
  final settings = SettingsProvider();
  await settings.load();
  settings.autoRetryEnabled = false;
  settings.retryDelaySeconds = 0;
  await settings.setMaxDownloads(5);
  return (database, settings);
}

void main() {
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    drift.driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
    uniqueHivePath =
        'build/test_hive_int_${DateTime.now().microsecondsSinceEpoch}';
    try {
      final dir = Directory(uniqueHivePath);
      if (dir.existsSync()) {
        dir.deleteSync(recursive: true);
      }
    } catch (_) {}
    Hive.init(uniqueHivePath);
    ConnectivityPlatform.instance = MockConnectivityPlatform();

    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('com.xdm.downloadmanager/widget'),
      (methodCall) async => null,
    );
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('plugins.it_nomads.com/flutter_secure_storage'),
      (methodCall) async {
        switch (methodCall.method) {
          case 'read':
            return null;
          case 'write':
          case 'delete':
          case 'containsKey':
          case 'readAll':
          default:
            return null;
        }
      },
    );
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(
      const MethodChannel('flutter.arthenica.com/ffmpeg_kit'),
      (methodCall) async {
        debugPrint('FFMPEG_KIT_MOCK: ${methodCall.method} called');
        if (methodCall.method == 'getLogLevel') {
          return 0;
        }
        return null;
      },
    );
  });

  tearDown(() async {
    if (Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
      await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();
    }
  });

  tearDownAll(() async {
    await Hive.close();
    try {
      final dir = Directory(uniqueHivePath);
      if (dir.existsSync()) {
        dir.deleteSync(recursive: true);
      }
    } catch (_) {}
  });

  test('DownloadProvider full download flow and pause/resume', () async {
    final (database, settings) = await _setupServices();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: FakeDownloadEngine(),
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: 'test_flow.zip',
      url: 'https://example.com/test_flow.zip',
      size: 100,
      category: 'Archive',
      savePath: 'build/test_downloads',
    );

    expect(provider.tasks.length, 1);
    final taskId = provider.tasks.first.id;
    for (int i = 0; i < 100; i++) {
      if (provider.tasks.first.status == DownloadStatus.downloading) {
        break;
      }
      await Future.delayed(const Duration(milliseconds: 5));
    }
    expect(provider.tasks.first.status, DownloadStatus.downloading);

    await provider.pauseTask(taskId);
    expect(provider.tasks.first.status, DownloadStatus.paused);

    await Future.delayed(const Duration(milliseconds: 600));
    await provider.resumeTask(taskId);
    expect(provider.tasks.first.status,
        anyOf(DownloadStatus.downloading, DownloadStatus.queued));

    for (int i = 0; i < 200; i++) {
      if (provider.tasks.first.status == DownloadStatus.completed) {
        break;
      }
      await Future.delayed(const Duration(milliseconds: 10));
    }
    expect(provider.tasks.first.status, DownloadStatus.completed);
  });

  test('DownloadProvider YouTube merge flow', () async {
    final (database, settings) = await _setupServices();
    final engine = FakeDownloadEngine();
    final provider = DownloadProvider(
      databaseService: database,
      settingsProvider: settings,
      downloadEngine: engine,
      permissionService: FakePermissionService(),
    );
    await provider.load();

    await provider.addDownload(
      name: 'youtube_video.mp4',
      url: 'https://example.com/video',
      size: 100,
      category: 'Video',
      savePath: 'build/test_downloads',
      mergedAudioUrl: 'https://example.com/audio',
      audioSize: 50,
    );

    expect(provider.tasks.length, 1);

    // Wait for the video download phase, then audio phase, then merge phase
    for (int i = 0; i < 1000; i++) {
      if (provider.tasks.first.status == DownloadStatus.failed ||
          provider.tasks.first.status == DownloadStatus.completed) {
        break;
      }
      await Future.delayed(const Duration(milliseconds: 10));
    }

    // In a test environment without real ffmpeg binary, the merge phase will fail.
    // The provider sets status to failed with ffmpegMergeFailed message.
    expect(provider.tasks.first.status, DownloadStatus.failed);
    expect(provider.tasks.first.errorMessage,
        contains(DownloadStatusMessages.ffmpegMergeFailed));
    expect(engine.knownFileSizes['https://example.com/video'], 50,
        reason: 'Combined tasks must request only the video stream length.');
  });
}
