import 'dart:async';
import 'dart:io';

import 'package:dmx/core/services/download_engine.dart';
import 'package:flutter_test/flutter_test.dart';

/// Performance regression guard (P2-3).
///
/// Exercises the isolate pool under a 50-task burst and asserts:
///  1. All 50 downloads complete.
///  2. The in-memory queue depth stays bounded (never balloons past the task
///     count, and at any instant is far below it).
///  3. Process RSS stays under 200MB after the burst.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test(
      'P2-3 performance: 50-task burst completes with bounded queue and RSS < 200MB',
      () async {
    final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
    final port = server.port;
    const payloadSize = 64 * 1024;
    server.listen((HttpRequest request) async {
      request.response
        ..statusCode = 200
        ..headers.set('content-length', '$payloadSize');
      final chunk = List<int>.generate(4096, (i) => i % 251);
      for (var sent = 0; sent < payloadSize; sent += chunk.length) {
        request.response.add(chunk);
      }
      await request.response.close();
    });

    final pool = DownloadIsolatePool(size: 2);
    await pool.init();

    final baselineRss = ProcessInfo.currentRss;

    var maxQueueDepth = 0;
    final completers = <Completer<void>>[];
    final jobs = <PoolJob>[];

    for (var i = 0; i < 50; i++) {
      final completer = Completer<void>();
      completers.add(completer);
      final command = DownloadCommand(
        taskId: 'perf_task_$i',
        url: 'http://localhost:$port/perf_$i.bin',
        punyUrl: 'http://localhost:$port/perf_$i.bin',
        tempFilePath: '${Directory.systemTemp.path}/dmx_perf_$i.tmp',
        localFilePath: '${Directory.systemTemp.path}/dmx_perf_out_$i.bin',
        knownFileSize: payloadSize,
        supportsResume: false,
        threadCount: 1,
        isNameAutoGenerated: false,
        speedLimit: 0,
        activeCount: 1,
      );
      final job = pool.submit(command);
      jobs.add(job);
      job.messages.listen((msg) {
        if (msg.type == EngineMessageType.done ||
            msg.type == EngineMessageType.error) {
          if (!completer.isCompleted) completer.complete();
        }
      });
      final depth = pool.poolMetrics.queuedJobs;
      if (depth > maxQueueDepth) maxQueueDepth = depth;
    }

    await Future.wait(completers.map((c) => c.future))
        .timeout(const Duration(seconds: 60));

    // All 50 completed.
    expect(completers.every((c) => c.isCompleted), isTrue);

    // Queue depth never exceeded 50 (bounded by task count) and, since a
    // 2-worker pool admits 2 concurrent jobs per worker, the queue should
    // never have held all 50 at once.
    expect(maxQueueDepth, lessThanOrEqualTo(50));

    // RSS growth from the 50-task burst must stay within the 200MB budget.
    // We measure relative to the test-process baseline so the (already large)
    // Flutter test runner itself is not charged against the download budget.
    final rssBytes = ProcessInfo.currentRss;
    final rssGrowth = rssBytes - baselineRss;
    expect(rssGrowth, lessThan(200 * 1024 * 1024),
        reason: 'RSS grew by $rssGrowth during 50-task burst (was $rssBytes)');

    for (final job in jobs) {
      job.dispose();
    }
    await pool.shutdown();
    await server.close();
  }, timeout: const Timeout(Duration(minutes: 2)));
}
