import 'dart:async';

import 'package:dio/dio.dart';
import 'package:dmx/core/domain/resume_identity.dart';
import 'package:dmx/core/domain/transfer_result.dart';
import 'package:dmx/core/services/database_service.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/download_journal.dart';
import 'package:dmx/core/services/engine/download_progress_handler.dart';
import 'package:dmx/core/services/logging_service.dart';
import 'package:dmx/core/services/metadata_probe_service.dart';
import 'package:dmx/core/services/power_monitor.dart';
import 'package:dmx/core/services/site_intelligence/site_intelligence_service.dart';
import 'package:dmx/core/services/yt_counterpart_coordinator.dart';
import 'package:dmx/core/utils/url_utils.dart';
import 'package:dmx/features/downloads/models/download_task.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:flutter/foundation.dart';
import 'package:get_it/get_it.dart';

/// Orchestrates HTTP multi-threaded downloads, managing mirrors, retries, and YT sync.
/// Moved to feature domain layer for Clean Architecture.
class HttpDownloadOrchestrator {
  static final _log = LoggingService.logger('HttpDownloadOrchestrator');
  final MetadataProbeService _metadataService;
  final YtCounterpartCoordinator _ytCoordinator;
  final SettingsProvider _settings;

  HttpDownloadOrchestrator(
    this._metadataService,
    this._ytCoordinator,
    this._settings,
  );

  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required DownloadIsolatePool pool,
    int threadCount = 0,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    String? authUsername,
    String? authPassword,
    Map<String, String>? customHeaders,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    bool isRetry = false,
  }) async {
    final int defaultCount = _settings.effectiveDefaultThreadCount;
    final int effectiveThreadCount =
        (threadCount > 0 ? threadCount : defaultCount)
            .clamp(1, PowerMonitor.maxAllowedThreads);

    int resolvedFileSize = knownFileSize;
    bool resolvedSupportsResume = supportsResume;
    String? resolvedFileName;

    if (resolvedFileSize == 0 && isNameAutoGenerated) {
      try {
        final meta = await _metadataService.resolveMetadata(
          url: url,
          customUserAgent: customUserAgent,
          referer: referer,
          cookies: cookies,
          oauthToken: oauthToken,
          cancelToken: cancelToken,
        );
        resolvedFileSize = meta.fileSize;
        resolvedSupportsResume = meta.supportsResume;
        resolvedFileName = meta.fileName;
      } catch (e) {
        debugPrint('[HttpOrchestrator] resolveMetadata failed: $e');
      }
    }

    int alreadyOnDisk = 0;
    String activeDownloadUrl = url;
    List<String>? effectiveMirrors = mirrorUrls;

    if (resolvedFileSize > 0) {
      try {
        final state = await StateStore.loadOrCreate(
          tempFilePath,
          url: url,
          threadCount: effectiveThreadCount,
          knownFileSize: resolvedFileSize,
        );
        alreadyOnDisk = state.state.downloadedBytes;

        // Resume identity validation against fresh probe
        final isYouTubeUrl = url.contains('.googlevideo.com') ||
            url.contains('youtube.com') ||
            ytStreamKind != null;
        final storedIdentity = state.state.resumeIdentity;
        if (alreadyOnDisk > 0 && storedIdentity != null && !isYouTubeUrl) {
          final candidateMirrors = [url, ...?mirrorUrls];
          bool identityMatched = false;
          String? matchingUrl;
          final validMirrors = <String>[];

          for (final candidate in candidateMirrors) {
            try {
              final headMeta = await _metadataService.resolveMetadata(
                url: candidate,
                customUserAgent: customUserAgent,
                referer: referer,
                cookies: cookies,
                oauthToken: oauthToken,
                cancelToken: cancelToken,
              );
              final candidateIdentity = ResumeIdentity(
                normalizedUrl: ResumeIdentity.normalizeUrl(candidate),
                etag: headMeta.etag,
                lastModified: headMeta.lastModified,
                contentLength: headMeta.fileSize > 0 ? headMeta.fileSize : null,
                supportsRanges: headMeta.supportsResume,
              );
              final valResult =
                  storedIdentity.validateAgainst(candidateIdentity);
              if (valResult.isValid) {
                if (!identityMatched) {
                  identityMatched = true;
                  matchingUrl = candidate;
                } else {
                  validMirrors.add(candidate);
                }
              } else {
                _log.warning(
                    'Resume identity mismatch on $candidate: ${valResult.mismatchReason}');
              }
            } catch (e) {
              _log.fine('Candidate mirror probe failed for $candidate: $e');
            }
          }

          if (!identityMatched) {
            onProgress(DownloadProgress(
              downloadedBytes: alreadyOnDisk,
              fileSize: resolvedFileSize,
              speed: 0,
              eta: null,
              statusMessage: 'Refreshing link…',
              cycleState: CycleState.updatingLinks,
              pauseReason: PauseReason.urlExpired,
            ));
            throw const UrlExpiredException(
                'Remote resource changed or URL expired for resume.');
          } else {
            activeDownloadUrl = matchingUrl!;
            effectiveMirrors = validMirrors;
          }
        }
      } catch (e, st) {
        if (e is UrlExpiredException) rethrow;
        LoggingService.logger('HttpDownloadOrchestrator')
            .warning('Resume check failed', e, st);
      }
    }

    final punyUrl = convertIdnToPunycode(activeDownloadUrl);
    bool urlExpiresHint = false;
    try {
      if (GetIt.instance.isRegistered<SiteIntelligenceService>()) {
        final analysis = GetIt.instance<SiteIntelligenceService>()
            .analyzeUrl(activeDownloadUrl);
        urlExpiresHint = analysis.isExpiredOrSigned ||
            (analysis.profile?.urlsExpire == true);
      }
    } catch (e, st) {
      _log.fine('Failed to pre-compute urlExpiresHint: $e', e, st);
    }

    final command = DownloadCommand(
      taskId: taskId,
      url: activeDownloadUrl,
      punyUrl: punyUrl,
      tempFilePath: tempFilePath,
      localFilePath: localFilePath,
      knownFileSize: resolvedFileSize,
      supportsResume: resolvedSupportsResume,
      threadCount: effectiveThreadCount,
      customUserAgent: customUserAgent,
      referer: referer,
      cookies: cookies,
      oauthToken: oauthToken,
      authUsername: authUsername,
      authPassword: authPassword,
      customHeaders: customHeaders,
      httpsOnly: _settings.httpsOnly,
      // Only HTTP CONNECT proxies apply to dart:io HTTP downloads; SOCKS5 is
      // libtorrent-only, so anything other than 'http' is passed as null here.
      proxyType: _settings.proxyType == 'http' ? 'http' : null,
      proxyHost: _settings.proxyType == 'http' ? _settings.proxyHost : null,
      proxyPort: _settings.proxyType == 'http' ? _settings.proxyPort : null,
      proxyUsername:
          _settings.proxyType == 'http' ? _settings.proxyUsername : null,
      proxyPassword:
          _settings.proxyType == 'http' ? _settings.proxyPassword : null,
      diskWriteBatching: _settings.diskWriteBatching,
      isNameAutoGenerated:
          resolvedFileName != null ? false : isNameAutoGenerated,
      initialSpeedLimit: _settings.effectiveSpeedLimitBytesPerSecond,
      initialActiveCount: 1,
      mirrorUrls: effectiveMirrors,
      adaptiveThreads: adaptiveThreads,
      speedLimitKbps: speedLimitKbps,
      resolvedFileName: resolvedFileName,
      ytStreamKind: ytStreamKind,
      ytCounterpartSize: ytCounterpartSize,
      ytCounterpartDownloadedBytes: ytCounterpartDownloadedBytes,
      ytCounterpartTaskId: _ytCoordinator.getCounterpartId(taskId),
      throttleFactor: PowerMonitor.throttleFactor,
      urlExpiresHint: urlExpiresHint,
      // FIX(P2.5): Thread stall timeout + resume integrity check to worker.
      stalledTimeoutMinutes: _settings.downloadStalledTimeoutMinutes,
      resumeIntegrityCheck: _settings.resumeIntegrityCheck,
      initialDownloadedBytes: alreadyOnDisk,
    );

    final progressHandler = DownloadProgressHandler(
      taskId: taskId,
      onProgress: onProgress,
      cancelToken: cancelToken,
      resolvedFileName: resolvedFileName,
      resolvedSupportsResume: resolvedSupportsResume,
      ytStreamKind: ytStreamKind,
      ytCounterpartSize: ytCounterpartSize,
      ytCounterpartDownloadedBytes: ytCounterpartDownloadedBytes,
      isTorrent: false,
      getEffectiveIntervalMs: () => 500, // Throttling interval
      lastDownloadedBytes: alreadyOnDisk,
      lastFileSize: resolvedFileSize,
    );

    final job = pool.submit(command);
    final completer = Completer<void>();

    PauseReason? getStructuredPauseReason() {
      final err = cancelToken.cancelError;
      final r = err?.error ?? err?.message;
      if (r is PauseReason) return r;
      if (r is String) return PauseReason.fromName(r);
      return null;
    }

    if (cancelToken.isCancelled) {
      final reason = getStructuredPauseReason();
      try {
        DownloadJournal.flushAndSyncForFile(tempFilePath);
      } catch (_) {}
      job.cancel(reason);
      throw DioException(
        requestOptions: RequestOptions(path: punyUrl),
        type: DioExceptionType.cancel,
        message: 'Download cancelled',
      );
    }

    unawaited(cancelToken.whenCancel.then((_) async {
      if (!completer.isCompleted) {
        final reason = getStructuredPauseReason();
        try {
          await DownloadJournal.flushAndSyncForFile(tempFilePath);
          final existing = await StateStore.loadOrCreate(
            tempFilePath,
            url: activeDownloadUrl,
            threadCount: effectiveThreadCount,
            knownFileSize: resolvedFileSize,
          );
          existing.state.status = DmxStateStatus.paused;
          existing.state.pauseReason = reason;
          await StateStore.save(tempFilePath, existing.state,
              durable: true, taskId: taskId);
        } catch (_) {}

        job.cancel(reason);
        if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: punyUrl),
            type: DioExceptionType.cancel,
            message: 'Download cancelled',
          ),
        );
      }
    }));

    final sub = job.messages.listen((message) async {
      switch (message.type) {
        case EngineMessageType.progress:
          final data = message.data;
          int? ytCpOverride;
          if (ytStreamKind != null) {
            final downloaded = (data['downloadedBytes'] as num?)?.toInt() ?? 0;
            _ytCoordinator.updateLiveBytes(taskId, downloaded);
            final cpId = _ytCoordinator.getCounterpartId(taskId);
            if (cpId != null) {
              ytCpOverride = _ytCoordinator.getLiveBytes(cpId);
            }
          }
          try {
            await progressHandler.handleWorkerProgress(
              data,
              ytCounterpartDownloadedOverride: ytCpOverride,
            );
          } catch (e, st) {
            if (!completer.isCompleted) {
              completer.completeError(e, st);
            }
          }
          break;
        case EngineMessageType.done:
          progressHandler.markDone();
          if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
          if (!completer.isCompleted) completer.complete();
          break;
        case EngineMessageType.error:
          if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
          final errData = message.data;
          final dlBytes = (errData['downloadedBytes'] as num?)?.toInt() ??
              progressHandler.lastDownloadedBytes;
          final pReason =
              PauseReason.fromName(errData['errorType'] as String?) ??
                  PauseReason.networkLost;

          // Immediately persist failure state without debounce
          unawaited(DatabaseService.instance.getTask(taskId).then((t) {
            if (t != null) {
              return DatabaseService.instance.saveTask(t.copyWith(
                status: DownloadStatus.failed,
                downloadedBytes: dlBytes,
                pauseReason: pReason,
              ));
            }
          }).catchError((_) {}));

          if (!completer.isCompleted) {
            completer.completeError(_mapWorkerError(errData, punyUrl));
          }
          break;
        case EngineMessageType.hello:
        case EngineMessageType.idle:
        case EngineMessageType.limits:
        case EngineMessageType.job:
        case EngineMessageType.cancel:
        case EngineMessageType.shutdown:
        case EngineMessageType.ack:
          break;
      }
    });

    try {
      await completer.future;
    } finally {
      progressHandler.dispose();
      await sub.cancel();
      job.dispose();
    }
  }

  Exception _mapWorkerError(Map<String, dynamic> data, String url) {
    final result = TransferResult.fromMap(data);
    final msg = result.message ?? 'Unknown error';
    final status = result.httpStatus;
    final taxonomy = result.taxonomyCode;

    if (result.isCancelled || taxonomy == 'cancelled' || taxonomy == 'cancel') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.cancel,
        message: msg,
      );
    }
    if (taxonomy == 'disk' || taxonomy == 'diskFull') {
      return const InsufficientStorageException();
    }
    if (taxonomy == 'integrity') {
      return DownloadIntegrityException(msg);
    }
    if (taxonomy == 'urlExpired' ||
        (taxonomy == 'auth' && data['refreshAllMirrors'] == true)) {
      return UrlExpiredException(
        msg,
        refreshAllMirrors: data['refreshAllMirrors'] == true,
      );
    }
    if (taxonomy == 'timeout' || taxonomy == 'connectionTimeout') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.connectionTimeout,
        message: msg,
      );
    }
    if (taxonomy == 'receiveTimeout') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.receiveTimeout,
        message: msg,
      );
    }
    if (taxonomy == 'sendTimeout') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.sendTimeout,
        message: msg,
      );
    }
    if (taxonomy == 'network' || taxonomy == 'connectionError') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.connectionError,
        message: msg,
      );
    }
    if (status != null && status >= 400) {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.badResponse,
        response: Response(
          requestOptions: RequestOptions(path: url),
          statusCode: status,
          statusMessage: msg,
        ),
        message: msg,
      );
    }

    return DioException(
      requestOptions: RequestOptions(path: url),
      type: DioExceptionType.unknown,
      error: msg,
    );
  }
}
