import 'dart:async';
import 'package:dio/dio.dart';
import '../domain/engine_types.dart';

/// Abstract interface for Download Engines (M-ARCH-04).
abstract class IDownloadEngine {
  /// Primary execution method using the [DownloadRequest] parameter object.
  Future<void> downloadRequest(DownloadRequest request);

  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 0,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    String? authUsername,
    String? authPassword,
    Map<String, String>? customHeaders,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    bool isRetry = false,
    int? metadataTimeoutSeconds,
  });

  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    CancelToken? cancelToken,
  });

  Future<void> close();

  void forceCancelJob(String taskId);

  Future<bool> hasEnoughDiskSpace(String targetDirectory, int requiredBytes);

  String buildTempFilePath(String savePath, String fileName);

  void updateSpeedLimit(int bytesPerSecond, int activeCount);
}
