part of 'download_engine.dart';

// ═══════════════════════════════════════════════════════════════════════════
// VERSIONED ISOLATE PROTOCOL
//
// Every message is a self-describing envelope {proto, type, taskId, seq,
// data}. tryDecode REJECTS unknown protocol versions and malformed payloads
// (returns null → dropped + logged), so a garbled or version-skewed message
// can never reach task state.
// ═══════════════════════════════════════════════════════════════════════════

class EngineMessage {
  EngineMessage._(this.type, this.taskId, this.data, this.seq);

  static const int protocolVersion = 1;

  final String type;
  final String taskId;
  final Map<String, dynamic> data;
  final int seq;

  static Map<String, dynamic> encode({
    required String type,
    required String taskId,
    int seq = 0,
    Map<String, dynamic>? data,
  }) =>
      {
        'proto': protocolVersion,
        'type': type,
        'taskId': taskId,
        'seq': seq,
        if (data != null) 'data': data,
      };

  static EngineMessage? tryDecode(dynamic raw) {
    try {
      if (raw is! Map) return null;
      if (raw['proto'] != protocolVersion) return null;
      final type = raw['type'];
      final taskId = raw['taskId'];
      if (type is! String || taskId is! String) return null;
      final data = raw['data'];
      return EngineMessage._(
        type,
        taskId,
        data is Map ? Map<String, dynamic>.from(data) : <String, dynamic>{},
        (raw['seq'] as num?)?.toInt() ?? 0,
      );
    } catch (_) {
      return null;
    }
  }
}

/// Everything a worker isolate needs. Crosses the isolate boundary as a Map
/// (explicit serialization, no shared-object assumptions).
class DownloadCommand {
  const DownloadCommand({
    required this.taskId,
    required this.url,
    required this.punyUrl,
    required this.tempFilePath,
    required this.localFilePath,
    required this.knownFileSize,
    required this.supportsResume,
    required this.threadCount,
    this.enableProxy = false,
    this.bypassSSL = true,
    this.isNameAutoGenerated = false,
    this.adaptiveThreads = false,
    this.initialSpeedLimit = 0,
    this.initialActiveCount = 1,
    this.speedLimitKbps = 0,
    int? speedLimit,
    int? activeCount,
    this.customUserAgent,
    this.referer,
    this.proxyAddress,
    this.proxyHost,
    this.proxyPort,
    this.proxyUsername,
    this.proxyPassword,
    this.cookies,
    this.oauthToken,
    this.mirrorUrls,
    this.resolvedFileName,
    this.ytStreamKind,
    this.ytCounterpartSize,
    this.ytCounterpartDownloadedBytes,
  });

  final String taskId;
  final String url;
  final String punyUrl;
  final String tempFilePath;
  final String localFilePath;
  final int knownFileSize;
  final bool supportsResume;
  final int threadCount;
  final String? customUserAgent;
  final String? referer;
  final bool enableProxy;
  final String? proxyAddress;
  final String? proxyHost;
  final int? proxyPort;
  final String? proxyUsername;
  final String? proxyPassword;
  final bool bypassSSL;
  final String? cookies;
  final String? oauthToken;
  final bool isNameAutoGenerated;
  final int initialSpeedLimit;
  final int initialActiveCount;
  final int speedLimitKbps;
  final List<String>? mirrorUrls;
  final bool adaptiveThreads;
  final String? resolvedFileName;
  final YtStreamKind? ytStreamKind;
  final int? ytCounterpartSize;
  final int? ytCounterpartDownloadedBytes;

  Map<String, dynamic> toMap() => {
        'taskId': taskId,
        'url': url,
        'punyUrl': punyUrl,
        'tempFilePath': tempFilePath,
        'localFilePath': localFilePath,
        'knownFileSize': knownFileSize,
        'supportsResume': supportsResume,
        'threadCount': threadCount,
        'customUserAgent': customUserAgent,
        'referer': referer,
        'enableProxy': enableProxy,
        'proxyAddress': proxyAddress,
        'proxyHost': proxyHost,
        'proxyPort': proxyPort,
        'proxyUsername': proxyUsername,
        'proxyPassword': proxyPassword,
        'bypassSSL': bypassSSL,
        'cookies': cookies,
        'oauthToken': oauthToken,
        'isNameAutoGenerated': isNameAutoGenerated,
        'initialSpeedLimit': initialSpeedLimit,
        'initialActiveCount': initialActiveCount,
        'speedLimitKbps': speedLimitKbps,
        'mirrorUrls': mirrorUrls,
        'adaptiveThreads': adaptiveThreads,
        'resolvedFileName': resolvedFileName,
        if (ytStreamKind != null) 'ytStreamKind': ytStreamKind!.name,
        if (ytCounterpartSize != null) 'ytCounterpartSize': ytCounterpartSize,
        if (ytCounterpartDownloadedBytes != null)
          'ytCounterpartDownloadedBytes': ytCounterpartDownloadedBytes,
      };

  static DownloadCommand fromMap(Map<String, dynamic> m) => DownloadCommand(
        taskId: m['taskId'] as String,
        url: m['url'] as String,
        punyUrl: m['punyUrl'] as String,
        tempFilePath: m['tempFilePath'] as String,
        localFilePath: m['localFilePath'] as String,
        knownFileSize: (m['knownFileSize'] as num?)?.toInt() ?? 0,
        supportsResume: m['supportsResume'] as bool? ?? false,
        threadCount: (m['threadCount'] as num?)?.toInt() ?? 1,
        customUserAgent: m['customUserAgent'] as String?,
        referer: m['referer'] as String?,
        enableProxy: m['enableProxy'] as bool? ?? false,
        proxyAddress: m['proxyAddress'] as String?,
        proxyHost: m['proxyHost'] as String?,
        proxyPort: (m['proxyPort'] as num?)?.toInt(),
        proxyUsername: m['proxyUsername'] as String?,
        proxyPassword: m['proxyPassword'] as String?,
        bypassSSL: m['bypassSSL'] as bool? ?? true,
        cookies: m['cookies'] as String?,
        oauthToken: m['oauthToken'] as String?,
        isNameAutoGenerated: m['isNameAutoGenerated'] as bool? ?? false,
        initialSpeedLimit: (m['initialSpeedLimit'] as num?)?.toInt() ?? 0,
        initialActiveCount: (m['initialActiveCount'] as num?)?.toInt() ?? 1,
        speedLimitKbps: (m['speedLimitKbps'] as num?)?.toInt() ?? 0,
        mirrorUrls: (m['mirrorUrls'] as List?)?.cast<String>(),
        adaptiveThreads: m['adaptiveThreads'] as bool? ?? false,
        resolvedFileName: m['resolvedFileName'] as String?,
        ytStreamKind: m['ytStreamKind'] != null
            ? YtStreamKind.values.firstWhere(
                (k) => k.name == m['ytStreamKind'],
                orElse: () => YtStreamKind.combined,
              )
            : null,
        ytCounterpartSize: (m['ytCounterpartSize'] as num?)?.toInt(),
        ytCounterpartDownloadedBytes:
            (m['ytCounterpartDownloadedBytes'] as num?)?.toInt(),
      );
}

// ── Pool ────────────────────────────────────────────────────────────────────

class DownloadIsolatePool {
  DownloadIsolatePool({int size = 4, bool powerAware = false})
      : _size = size,
        _powerAware = powerAware;

  final int _size;
  final bool _powerAware;
  final List<_Worker> _workers = [];
  final List<PoolJob> _queue = [];
  bool _shuttingDown = false;
  int _seq = 0;

  /// Up to two concurrent jobs per worker isolate at full power; drop to one
  /// when battery saver is in aggressive mode.
  int get maxJobsPerWorker =>
      PowerMonitor.batterySaverMode == BatterySaverMode.aggressive ? 1 : 2;

  /// Effective pool capacity surface. In power-aware mode an aggressive
  /// battery collapse is reflected even before isolates are physically
  /// re-spawned.
  int get workerCount {
    final live = _workers.length;
    if (live <= 0) return 0;
    if (_powerAware &&
        PowerMonitor.batterySaverMode == BatterySaverMode.aggressive) {
      return 1;
    }
    return live;
  }

  Future<void> init() async {
    for (var i = 0; i < _size; i++) {
      _workers.add(await _spawnWorker(i));
    }
  }

  Future<_Worker> _spawnWorker(int index) async {
    final inbox = ReceivePort();
    final errorPort = ReceivePort();
    final isolate = await Isolate.spawn(
      _workerEntry,
      inbox.sendPort,
      errorsAreFatal: true,
      onError: errorPort.sendPort,
      debugName: 'dmx-engine-worker-$index',
    );
    final worker =
        _Worker(isolate: isolate, inbox: inbox, errorPort: errorPort);
    inbox.listen((dynamic msg) => _onWorkerMessage(worker, msg));
    errorPort.listen((dynamic err) => _onWorkerCrash(worker, err));
    return worker;
  }

  PoolJob submit(DownloadCommand command, {int priority = 0}) {
    if (_shuttingDown || _workers.isEmpty) {
      throw const IsolateSpawnTimeoutException();
    }
    final job = PoolJob._(this, command, _seq++);
    if (_shuttingDown) {
      scheduleMicrotask(() =>
          job._deliverError('workerDied', 'Engine is shutting down', null));
      return job;
    }
    _dispatch(job, priority);
    return job;
  }

  void _dispatch(PoolJob job, int priority) {
    job.priority = priority;
    final slots = maxJobsPerWorker;
    _Worker? worker;
    for (final w in _workers) {
      if (!w.dead && w.commandPort != null && w.activeJobs < slots) {
        worker = w;
        break;
      }
    }
    if (worker == null) {
      _queue.add(job);
      return;
    }
    worker.activeJobs++;
    worker.pending.add(job);
    job._worker = worker;
    worker.commandPort?.send({
      't': 'job',
      'jobId': job.command.taskId,
      'reply': job._incoming.sendPort,
      'cmd': job.command.toMap(),
    });
  }

  void _onWorkerMessage(_Worker worker, dynamic msg) {
    if (msg is! Map) return;
    switch (msg['t']) {
      case 'hello':
        worker.commandPort = msg['port'] as SendPort;
        // Drain anything queued before the worker said hello — highest priority
        // first, up to that worker's available slots.
        _drain();
      case 'idle':
        worker.activeJobs = (worker.activeJobs - 1).clamp(0, 1 << 30);
        final doneId = msg['jobId'];
        worker.pending.removeWhere((j) => j.command.taskId == doneId);
        _drain();
      case 'limits':
        break;
    }
  }

  void _drain() {
    if (_queue.isEmpty) return;
    var idx = 0;
    while (idx < _queue.length) {
      final slots = maxJobsPerWorker;
      _Worker? worker;
      for (final w in _workers) {
        if (!w.dead && w.commandPort != null && w.activeJobs < slots) {
          worker = w;
          break;
        }
      }
      if (worker == null) return;
      final job = _removeHighestPriority();
      if (job == null) return;
      worker.activeJobs++;
      worker.pending.add(job);
      job._worker = worker;
      worker.commandPort!.send({
        't': 'job',
        'jobId': job.command.taskId,
        'reply': job._incoming.sendPort,
        'cmd': job.command.toMap(),
      });
      idx++;
    }
  }

  /// Returns the queued job with the highest priority, breaking ties by
  /// submission order (earliest first).
  PoolJob? _removeHighestPriority() {
    if (_queue.isEmpty) return null;
    var best = 0;
    for (var i = 1; i < _queue.length; i++) {
      final a = _queue[best];
      final b = _queue[i];
      if (b.priority > a.priority ||
          (b.priority == a.priority && b.seq < a.seq)) {
        best = i;
      }
    }
    return _queue.removeAt(best);
  }

  void _onWorkerCrash(_Worker worker, dynamic err) {
    worker.dead = true;
    final jobs = List<PoolJob>.from(worker.pending);
    worker.pending.clear();
    worker.activeJobs = 0;
    // Surface the crash as a task-level error — never a silent stall.
    for (final job in jobs) {
      job._deliverError('workerDied', 'Worker isolate died: $err', null);
    }
    worker.inbox.close();
    worker.errorPort.close();
    worker.isolate.kill(priority: Isolate.immediate);
    if (!_shuttingDown) {
      _workers.remove(worker);
      _spawnWorker(_workers.length).then((w) {
        _workers.add(w);
        _drain();
      });
    }
  }

  void _cancelJob(PoolJob job) {
    job._worker?.commandPort
        ?.send({'t': 'cancel', 'jobId': job.command.taskId});
  }

  void updateSpeedLimit(int bytesPerSecond, int activeCount) {
    for (final w in _workers) {
      w.commandPort
          ?.send({'t': 'limits', 'bps': bytesPerSecond, 'active': activeCount});
    }
  }

  Future<void> shutdown() async {
    _shuttingDown = true;
    _queue.clear();
    for (final w in _workers) {
      w.commandPort?.send({'t': 'shutdown'});
      await Future<void>.delayed(const Duration(milliseconds: 50));
      w.inbox.close();
      w.errorPort.close();
      w.isolate.kill(priority: Isolate.beforeNextEvent);
    }
    _workers.clear();
  }

  Future<void> drain({Duration? timeout}) async {
    await shutdown();
  }

  void onMemoryPressure() {
    if (_workers.length > 1) {
      final w = _workers.removeLast();
      w.inbox.close();
      w.errorPort.close();
      w.isolate.kill(priority: Isolate.immediate);
    }
  }
}

class _Worker {
  _Worker({
    required this.isolate,
    required this.inbox,
    required this.errorPort,
  });
  final Isolate isolate;
  final ReceivePort inbox;
  final ReceivePort errorPort;
  SendPort? commandPort;
  final List<PoolJob> pending = [];
  int activeJobs = 0;
  bool dead = false;
}

class PoolJob {
  PoolJob._(this._pool, this.command, this._seq) {
    messages = _incoming
        .map(EngineMessage.tryDecode)
        .where((m) {
          if (m == null) {
            debugPrint('[DMX-Pool] dropped undecodable engine message');
            return false;
          }
          return true;
        })
        .cast<EngineMessage>()
        .asBroadcastStream();
  }

  final DownloadIsolatePool _pool;
  final DownloadCommand command;
  final int _seq;
  int priority = 0;
  int get seq => _seq;
  final ReceivePort _incoming = ReceivePort();
  _Worker? _worker;
  late final Stream<EngineMessage> messages;
  bool _disposed = false;

  void cancel() => _pool._cancelJob(this);

  void _deliverError(String type, String message, int? status) {
    if (_disposed) return;
    _incoming.sendPort.send(EngineMessage.encode(
      type: 'error',
      taskId: command.taskId,
      data: {'errorType': type, 'errorMessage': message, 'errorStatus': status},
    ));
  }

  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _incoming.close();
  }
}

// ── Worker isolate entry ────────────────────────────────────────────────────

/// Per-isolate globals updated by pool control messages.
int _workerGlobalLimitBps = 0;
int _workerGlobalActive = 1;

/// Running jobs inside this isolate, keyed by taskId (for cancel routing).
final Map<String, HttpTransferJob> _runningJobs = {};

Future<void> _workerEntry(SendPort poolPort) async {
  final cmdPort = ReceivePort();
  poolPort.send({'t': 'hello', 'port': cmdPort.sendPort});
  await for (final dynamic raw in cmdPort) {
    if (raw is! Map) continue;
    switch (raw['t']) {
      case 'job':
        final jobId = raw['jobId'] as String;
        final reply = raw['reply'] as SendPort;
        final cmd = DownloadCommand.fromMap(
            Map<String, dynamic>.from(raw['cmd'] as Map));
        final job = HttpTransferJob(cmd, reply);
        _runningJobs[jobId] = job;
        Future(() async {
          try {
            await job.run();
          } catch (e) {
            job.sendUnhandledError(e);
          } finally {
            _runningJobs.remove(jobId);
            poolPort.send({'t': 'idle', 'jobId': jobId});
          }
        });
      case 'cancel':
        _runningJobs[raw['jobId'] as String]?.requestCancel();
      case 'limits':
        _workerGlobalLimitBps = (raw['bps'] as num?)?.toInt() ?? 0;
        _workerGlobalActive =
            ((raw['active'] as num?)?.toInt() ?? 1).clamp(1, 1000);
      case 'shutdown':
        cmdPort.close();
        return;
    }
  }
}

// ── The transfer job (chunk execution) ─────────────────────────────────────

class _RangeUnsupportedException implements Exception {}

class _FileChangedOnServerException implements Exception {
  @override
  String toString() => 'File changed on server. Restart required.';
}

class HttpTransferJob {
  HttpTransferJob(this.cmd, this.out);

  final DownloadCommand cmd;
  final SendPort out;
  final CancelToken _cancelToken = CancelToken();
  int _seq = 0;
  bool _cancelRequested = false;
  TransferState? _state;
  int? _lastEta;
  int _lastStateSaveMs = 0;
  int _lastReportMs = 0;
  int _bytesSinceSave = 0;
  final Stopwatch _stopwatch = Stopwatch();
  final Queue<_SpeedSample> _speedSamples = Queue();

  static const int _stateSaveIntervalMs = 2000;
  // FIX H-2: Lower byte threshold to reduce worst-case loss window
  static const int _stateSaveByteThreshold = 256 * 1024; // 256 KB

  void requestCancel() {
    _cancelRequested = true;
    if (!_cancelToken.isCancelled) _cancelToken.cancel('paused');
  }

  void _send(String type, [Map<String, dynamic>? data]) {
    out.send(EngineMessage.encode(
        type: type, taskId: cmd.taskId, seq: _seq++, data: data));
  }

  void sendUnhandledError(Object e) {
    if (e is DioException && e.type == DioExceptionType.cancel) {
      _send('error', {
        'errorType': 'cancel',
        'errorMessage': e.message ?? 'cancelled',
      });
      return;
    }
    if (e is DownloadIntegrityException) {
      _send('error', {'errorType': 'integrity', 'errorMessage': e.message});
      return;
    }
    if (e is InsufficientStorageException ||
        (e is PositionalFileWriterException && _looksLikeDiskFull(e.message))) {
      _send('error', {'errorType': 'diskFull', 'errorMessage': e.toString()});
      return;
    }
    if (e is _FileChangedOnServerException) {
      _send('error', {
        'errorType': 'fileChanged',
        'errorMessage': 'File changed on server. Restart required.',
      });
      return;
    }
    // FIX-3A: Catch the typed URL expiry exception so the orchestrator
    // knows to refresh the link and retry, rather than treating it as a
    // user cancel.
    if (e is UrlExpiredException) {
      _send('error', {
        'errorType': 'urlExpired',
        'errorMessage': e.message,
        // FIX-URL-EXPIRY-ALL-MIRRORS: YouTube/signed-URL mirrors all
        // expire together. The orchestrator uses this flag to refresh
        // every mirror URL before re-submitting the job.
        'refreshAllMirrors': true,
      });
      return;
    }
    if (e is DioException) {
      _send('error', {
        'errorType': switch (e.type) {
          DioExceptionType.cancel => 'cancel',
          DioExceptionType.badResponse => 'badResponse',
          DioExceptionType.connectionTimeout => 'connectionTimeout',
          DioExceptionType.receiveTimeout => 'receiveTimeout',
          DioExceptionType.sendTimeout => 'sendTimeout',
          DioExceptionType.connectionError => 'connectionError',
          _ => 'uncaught',
        },
        'errorMessage': e.message ?? e.toString(),
        'errorStatus': e.response?.statusCode,
      });
      return;
    }
    _send('error', {'errorType': 'uncaught', 'errorMessage': e.toString()});
  }

  static bool _looksLikeDiskFull(String msg) {
    final m = msg.toLowerCase();
    return m.contains('enospc') || m.contains('no space left');
  }

  Future<void> run() async {
    _stopwatch.start();
    final dio = buildTransferDio(
      url: cmd.punyUrl,
      customUserAgent: cmd.customUserAgent,
      referer: cmd.referer,
      enableProxy: cmd.enableProxy,
      proxyAddress: cmd.proxyAddress,
      proxyHost: cmd.proxyHost,
      proxyPort: cmd.proxyPort,
      proxyUsername: cmd.proxyUsername,
      proxyPassword: cmd.proxyPassword,
      bypassSSL: cmd.bypassSSL,
      cookies: cmd.cookies,
      oauthToken: cmd.oauthToken,
    );
    _send('ack');
    try {
      // 1. Load/migrate/reconcile state — BEFORE any byte moves and BEFORE
      //    any percentage is emitted.
      final load = await StateStore.loadOrCreate(
        cmd.tempFilePath,
        url: cmd.url,
        threadCount: cmd.threadCount,
        knownFileSize: cmd.knownFileSize,
      );
      _state = load.state;
      // FIX H-R1: If the persisted chunk count differs from the requested
      // thread count, redistribute saved progress proportionally so the
      // user does not lose downloaded bytes.
      if (_state!.chunks.isNotEmpty &&
          _state!.chunks.length != cmd.threadCount &&
          _state!.downloadedBytes > 0) {
        final savedBytes = _state!.downloadedBytes;
        final total = _state!.totalSize;
        final newChunks = ChunkScheduler.plan(
          totalSize: total,
          threadCount: cmd.threadCount,
        );
        // FIX-4: Previous code distributed evenly, which can OVER-allocate
        // bytes to early chunks (clamping hides the loss) and UNDER-allocate
        // to the last chunk. Use a running-byte cursor instead so the sum of
        // newChunks[i].downloaded EXACTLY equals savedBytes (when total allows).
        var remaining = savedBytes;
        for (var i = 0; i < newChunks.length; i++) {
          final capacity =
              newChunks[i].size >= 0 ? newChunks[i].size : remaining;
          final take = remaining.clamp(0, capacity);
          newChunks[i].downloaded = take;
          remaining -= take;
        }
        _state!.chunks = newChunks;
        debugPrint(
          '[FIX-4/H-R1] Redistributed $savedBytes bytes from '
          '${load.state.chunks.length} → ${cmd.threadCount} chunks '
          '(leftover=$remaining)',
        );
      }
      if (_state!.totalSize <= 0 && cmd.knownFileSize > 0) {
        _state!.totalSize = cmd.knownFileSize;
      }
      _state!.status = DmxStateStatus.active;
      await StateStore.save(cmd.tempFilePath, _state!); // transition save

      // 2. Resume identity verification (size + ETag/Last-Modified).
      if (_state!.downloadedBytes > 0 && cmd.supportsResume) {
        await _verifyServerIdentity(dio);
      }

      // 3. Execute.
      final multiThread = _state!.totalSize > 0 &&
          cmd.supportsResume &&
          cmd.threadCount > 1 &&
          _state!.totalSize >= ChunkScheduler.minSizeForMultithread;
      if (multiThread) {
        try {
          await _runMultiThreaded(dio);
        } on _RangeUnsupportedException {
          debugPrint('[DMX-Job] Range unsupported → single-stream fallback');
          _resetToSingleStream();
          await _runSingleStream(dio);
        }
      } else {
        await _runSingleStream(dio);
      }

      // 4. Completion: verify, rename, clean state, final report.
      await _finalize(dio);
      _send('done');
    } finally {
      dio.close(force: true);
    }
  }

  /// Detects the two resume-hostile server changes BEFORE trusting saved
  /// bytes: (a) total size drift beyond tolerance → hard fail with the exact
  /// phrase the provider's retry path recognizes; (b) identity (ETag/LM)
  /// rotation with unchanged size → visible restart from zero.
  Future<void> _verifyServerIdentity(Dio dio) async {
    try {
      final response = await dio.get<ResponseBody>(
        cmd.punyUrl,
        cancelToken: _cancelToken,
        options: Options(
          responseType: ResponseType.stream,
          followRedirects: true,
          headers: {'Range': 'bytes=0-0'},
          validateStatus: (_) => true,
        ),
      );
      if (response.statusCode == 206 || response.statusCode == 200) {
        final contentRange = response.headers.value('content-range');
        int? serverTotal;
        if (contentRange != null) {
          serverTotal = int.tryParse(
              RegExp(r'/(\d+)').firstMatch(contentRange)?.group(1) ?? '');
        }
        serverTotal ??= int.tryParse(
            response.headers.value(Headers.contentLengthHeader) ?? '');
        final newEtag = response.headers.value('etag');
        final newLm = response.headers.value('last-modified');
        await response.data?.stream.listen((_) {}).cancel();

        if (serverTotal != null && serverTotal > 0 && _state!.totalSize > 0) {
          final tolerance =
              (_state!.totalSize * 0.001).clamp(2048.0, 10 * 1024 * 1024);
          if ((serverTotal - _state!.totalSize).abs() > tolerance) {
            for (var i = 0; i < _state!.chunks.length; i++) {
              _state!.chunks[i] = ChunkState(
                  start: _state!.chunks[i].start, end: _state!.chunks[i].end);
            }
            // FIX F4: Delete temp file on size change so single-stream doesn't resume stale bytes
            try {
              final f = File(cmd.tempFilePath);
              if (await f.exists()) await f.delete();
            } catch (_) {}
            await StateStore.save(cmd.tempFilePath, _state!);
            throw _FileChangedOnServerException();
          }
        }
        final oldIdentity = _firstNonEmpty(_state!.etag, _state!.lastModified);
        final newIdentity = _firstNonEmpty(newEtag, newLm);
        if (oldIdentity != null &&
            newIdentity != null &&
            oldIdentity != newIdentity) {
          // Same size, new resource identity: stored bytes no longer belong
          // to this resource. Restart loudly (status message), never pretend.
          debugPrint('[DMX-Job] resource identity changed — restarting');
          for (final c in _state!.chunks) {
            c.downloaded = 0;
          }
          // FIX F4: Delete temp file on identity change
          try {
            final f = File(cmd.tempFilePath);
            if (await f.exists()) await f.delete();
          } catch (_) {}
          _state!.etag = newEtag;
          _state!.lastModified = newLm;
          _state!.migrationNote =
              '${_state!.migrationNote ?? ''} identity_restart'.trim();
          await StateStore.save(cmd.tempFilePath, _state!);
          _emitProgress(0,
              statusMessage: 'Source changed on server — restarting');
        } else {
          _state!.etag ??= newEtag;
          _state!.lastModified ??= newLm;
        }
      }
    } on _FileChangedOnServerException {
      rethrow;
    } on DioException catch (e) {
      // FIX-9: On YouTube / signed-URL downloads, a 401/403 during the
      // identity probe means the URL has expired. Surface as UrlExpired
      // so the orchestrator refreshes streams and re-submits — never
      // silently "continue" with no usable resume data.
      final status = e.response?.statusCode;
      final host = Uri.tryParse(cmd.punyUrl)?.host.toLowerCase() ?? '';
      final isYtOrSigned = host.endsWith('.googlevideo.com') ||
          host.contains('youtube.com') ||
          host.contains('youtu.be') ||
          cmd.url.contains('expire=') ||
          cmd.url.contains('signature=');
      if (isYtOrSigned && (status == 401 || status == 403)) {
        // FIX-YT-UPDATING: Emit a progress update with 'updating_links'
        // cycle state BEFORE throwing so the UI shows "Updating links…"
        // during the URL refresh window instead of a generic error.
        _emitProgress(0, statusMessage: 'Updating links (URL expired)…');
        throw UrlExpiredException(
          'YouTube / signed URL expired during identity probe (HTTP $status).',
        );
      }
      debugPrint('[DMX-Job] identity probe failed (continuing): $e');
    } catch (e) {
      debugPrint('[DMX-Job] identity probe failed (continuing): $e');
    }
  }

  void _resetToSingleStream() {
    final st = _state!;
    for (final c in st.chunks) {
      c.downloaded = 0;
    }
    st.chunks = ChunkScheduler.singleStream(st.totalSize);
    st.threadCount = 1;
    // FIX F3: Remove pre-allocated temp file so single-stream does not treat its length as completed progress
    try {
      final f = File(cmd.tempFilePath);
      if (f.existsSync()) f.deleteSync();
    } catch (_) {}
  }

  // ── Multi-threaded execution ─────────────────────────────────────────────

  Future<void> _runMultiThreaded(Dio dio) async {
    final st = _state!;
    if (st.chunks.isEmpty) {
      st.chunks = ChunkScheduler.plan(
          totalSize: st.totalSize, threadCount: cmd.threadCount);
    }

    PositionalFileWriter writer;
    final hasPriorBytes = st.downloadedBytes > 0;
    if (hasPriorBytes && await File(cmd.tempFilePath).exists()) {
      writer = await PositionalFileWriter.openForResume(cmd.tempFilePath,
          threadCount: st.threadCount, totalSize: st.totalSize);
    } else {
      writer = await PositionalFileWriter.open(cmd.tempFilePath,
          totalSize: st.totalSize, threadCount: st.threadCount);
      for (final c in st.chunks) {
        c.downloaded = 0;
      }
    }

    final governor = BandwidthGovernor(_effectiveGlobalLimit());
    governor.registerConsumer();
    if (cmd.speedLimitKbps > 0) {
      governor.setTaskLimit(cmd.taskId, cmd.speedLimitKbps * 125);
    }

    // Optional spot-check of resumed bytes against the server.
    if (hasPriorBytes && SettingsProvider.instance.resumeIntegrityCheck) {
      await _spotCheckResumedBytes(dio, st, writer);
    }

    final failover = MirrorFailover([cmd.punyUrl, ...?cmd.mirrorUrls]);
    final work = ChunkScheduler.pendingWork(st.chunks);

    try {
      await Future.wait(work.map((chunk) => _runChunk(
            dio: dio,
            chunk: chunk,
            writer: writer,
            governor: governor,
            failover: failover,
          )));
      await writer.flushAll();

      // Completion verification: chunk sum is the authoritative source.
      // diskLen is unreliable for pre-allocated files (always equals totalSize).
      final sum = st.downloadedBytes;
      if (st.totalSize > 0 && sum < st.totalSize) {
        throw DownloadIntegrityException(
            'Chunk sum $sum < expected ${st.totalSize}');
      }
      // Note: diskLen check is informational only for pre-allocated files.
      final diskLen = await writer.length();
      if (st.totalSize > 0 && diskLen < st.totalSize) {
        throw DownloadIntegrityException(
            'On-disk size $diskLen < expected ${st.totalSize}');
      }
    } catch (e) {
      // Persist whatever IS proven before surfacing the error — retry picks
      // up the surviving chunks.
      if (e is DioException && e.type == DioExceptionType.cancel) {
        st.status = DmxStateStatus.paused;
      } else if (e is! _RangeUnsupportedException) {
        // FIX-11: Tag the state with whether resume is still safe. If at
        // least one chunk has proven bytes, the next start can resume from
        // those chunks. If all chunks are zero (e.g., integrity exception
        // before any byte moved), mark as "restartRequired" so the
        // orchestrator does NOT attempt a no-op resume.
        final anyProven = st.chunks.any((c) => c.downloaded > 0);
        st.status = DmxStateStatus.failed;
        st.migrationNote =
            '${st.migrationNote ?? ''} ${anyProven ? 'resumable' : 'restartRequired'}'
                .trim();
      }
      try {
        await writer.flushAll();
        await StateStore.save(cmd.tempFilePath, st);
      } catch (_) {}
      rethrow;
    } finally {
      governor.removeTaskLimit(cmd.taskId);
      governor.unregisterConsumer();
      await writer.close();
    }
  }

  Future<void> _runChunk({
    required Dio dio,
    required ChunkState chunk,
    required PositionalFileWriter writer,
    required BandwidthGovernor governor,
    required MirrorFailover failover,
  }) async {
    var attempts = 0;
    const maxAttempts = 3;
    var activeUrl = failover.activeUrl;

    while (!chunk.isComplete) {
      _throwIfCancelled();
      attempts++;
      try {
        final resumeFrom = chunk.downloaded;
        final absStart = chunk.start + resumeFrom;
        final headers = <String, dynamic>{
          'Range': chunk.end < 0
              ? 'bytes=$absStart-'
              : 'bytes=$absStart-${chunk.end}',
        };
        if (resumeFrom > 0) {
          final ifRange = _firstNonEmpty(_state!.etag, _state!.lastModified);
          if (ifRange != null) headers['If-Range'] = ifRange;
        }
        final response = await dio.get<ResponseBody>(
          activeUrl,
          cancelToken: _cancelToken,
          options: Options(
            responseType: ResponseType.stream,
            followRedirects: true,
            headers: headers,
            validateStatus: (_) => true,
          ),
        );

        if (response.statusCode == 200) {
          await response.data?.stream.listen((_) {}).cancel();
          if (resumeFrom > 0) {
            // The orchestrator's one-shot restart path keys on this exact
            // phrase — preserve it.
            throw DioException(
              requestOptions: response.requestOptions,
              type: DioExceptionType.badResponse,
              response: response,
              message: 'Server rejected resume: expected HTTP 206. Got 200.',
            );
          }
          throw _RangeUnsupportedException();
        }
        if (response.statusCode == 416) {
          await response.data?.stream.listen((_) {}).cancel();
          if (chunk.downloaded >= chunk.size) {
            chunk.downloaded = chunk.size;
            break;
          }
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'HTTP 416: invalid byte range for chunk.',
          );
        }
        if (response.statusCode != 206) {
          await response.data?.stream.listen((_) {}).cancel();
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'Server returned ${response.statusCode} instead of 206.',
          );
        }
        final contentType =
            response.headers.value('content-type')?.toLowerCase() ?? '';
        if (contentType.contains('text/html') ||
            contentType.contains('application/xhtml')) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'HTML_INSTEAD_OF_MEDIA',
          );
        }

        _validateContentRange(
          response.headers.value('content-range'),
          expectedStart: absStart,
          expectedEnd: chunk.end,
          expectedTotal: _state!.totalSize,
        );
        _state!.etag ??= response.headers.value('etag');
        _state!.lastModified ??= response.headers.value('last-modified');

        final stream = response.data?.stream;
        if (stream == null) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            message: 'Empty response body.',
          );
        }

        var sessionBytes = 0;
        await for (final piece in stream) {
          _throwIfCancelled();
          final sleepMs =
              await governor.acquire(piece.length, taskId: cmd.taskId);
          if (sleepMs > 0) {
            await _cancellableDelay(Duration(milliseconds: sleepMs));
            _throwIfCancelled();
          }
          final pos = chunk.start + resumeFrom + sessionBytes;
          await writer.write(-1, pos, piece);
          sessionBytes += piece.length;
          if (chunk.size >= 0 && (resumeFrom + sessionBytes) > chunk.size) {
            // Server sent more bytes than requested — truncate to prevent overwrite
            break;
          }
          chunk.downloaded = resumeFrom + sessionBytes;
          _bytesSinceSave += piece.length;
          await _throttledSaveAndReport(writer);
        }
        failover.reportSuccess();
        attempts = 0;
        if (chunk.isComplete) {
          // FIX H-2: Force save at every chunk boundary completion
          try {
            await writer.flushAll();
            await StateStore.save(cmd.tempFilePath, _state!);
          } catch (e) {
            debugPrint('[DMX] H-2: chunk-boundary save failed: $e');
          }
        }
      } on DioException catch (e) {
        if (e.type == DioExceptionType.cancel) rethrow;
        if (e.message == 'HTML_INSTEAD_OF_MEDIA') rethrow;
        if (e.message?.startsWith('Server rejected resume') == true) rethrow;
        final status = e.response?.statusCode;
        // FIX-3: 401/403 on signed/YouTube URLs usually means the URL has
        // expired. Surface a dedicated error type so the orchestrator can
        // refresh the link (yt-streams / signed-URL re-issue) and retry the
        // SAME chunk from the SAME byte offset — never losing progress.
        if (status == 401 || status == 403) {
          final bodyText = (e.response?.data?.toString() ?? '').toLowerCase();
          final host = Uri.tryParse(cmd.punyUrl)?.host.toLowerCase() ?? '';
          final isLikelyExpired = host.endsWith('.googlevideo.com') ||
              host.contains('youtube.com') ||
              host.contains('youtu.be') ||
              bodyText.contains('expired') ||
              bodyText.contains('token') ||
              bodyText.contains('signature') ||
              bodyText.contains('forbidden') ||
              cmd.url.contains('expire=') ||
              cmd.url.contains('signature=');
          if (isLikelyExpired) {
            // FIX-3B: Throw the typed exception so sendUnhandledError() can
            // map it to 'urlExpired'. The orchestrator catches this, refreshes
            // the URL, and re-submits the job WITHOUT losing chunk progress.
            // FIX-URL-EXPIRY-ALL-MIRRORS: For YouTube / signed URLs, every
            // mirror shares the same expiry signature — flag this so the
            // orchestrator refreshes ALL mirrors in one pass.
            // FIX-YT-UPDATING: Emit progress with 'updating_links' cycle
            // state before throwing so the UI shows the correct status
            // during the URL refresh window.
            _emitProgress(0, statusMessage: 'Updating links (URL expired)…');
            throw _UrlExpiredException(
              'Download URL expired (HTTP $status). Refresh required.',
            );
          }
        }
        if (status != null &&
            status >= 400 &&
            status < 500 &&
            status != 408 &&
            status != 429) {
          rethrow; // 4xx (except timeouts/429) won't heal by retrying.
        }
        if (attempts >= maxAttempts) {
          final next = failover.advance();
          if (next != null) {
            activeUrl = next;
            attempts = 0;
            debugPrint('[DMX-Job] failing over to mirror: $next');
            _emitProgress(_stopwatch.elapsedMilliseconds,
                statusMessage: 'Retrying (mirror failover)…');
            continue;
          }
          rethrow;
        }
        _emitProgress(_stopwatch.elapsedMilliseconds,
            statusMessage: 'Retrying…');
        await _cancellableDelay(
            Duration(seconds: (attempts * attempts * 2) + Random().nextInt(3)));
      } on PositionalFileWriterException {
        rethrow;
      } catch (e) {
        if (attempts >= maxAttempts) rethrow;
        await _cancellableDelay(Duration(seconds: attempts * 2));
      }
    }
  }

  Future<void> _spotCheckResumedBytes(
      Dio dio, TransferState st, PositionalFileWriter writer) async {
    const sampleSize = 64 * 1024;
    for (final chunk in st.chunks) {
      if (chunk.downloaded <= 0 || chunk.isComplete) continue;
      _throwIfCancelled();
      final start = chunk.start;
      final len = min(sampleSize, chunk.downloaded);
      try {
        final diskBytes = await writer.readRange(start, len);
        final response = await dio.get<ResponseBody>(
          cmd.punyUrl,
          cancelToken: _cancelToken,
          options: Options(
            responseType: ResponseType.stream,
            headers: {'Range': 'bytes=$start-${start + len - 1}'},
            validateStatus: (_) => true,
          ),
        );
        if (response.statusCode != 206 || response.data == null) {
          chunk.downloaded = 0;
          continue;
        }
        final builder = BytesBuilder(copy: false);
        await for (final b in response.data!.stream) {
          builder.add(b);
        }
        final netBytes = builder.takeBytes();
        if (netBytes.length != diskBytes.length ||
            !listEquals(netBytes, diskBytes)) {
          chunk.downloaded = 0;
          debugPrint('[DMX-Job] spot-check mismatch → chunk reset');
        }
      } catch (_) {
        // Probe failure is not fatal; keep stored progress.
      }
    }
  }

  // ── Single-stream execution ──────────────────────────────────────────────

  Future<void> _runSingleStream(Dio dio) async {
    final st = _state!;
    if (st.chunks.isEmpty) {
      st.chunks = ChunkScheduler.singleStream(st.totalSize);
    }
    final chunk = st.chunks.first;

    final tempFile = File(cmd.tempFilePath);
    await tempFile.parent.create(recursive: true);

    // Single-thread: the file itself is the byte source of truth.
    // FIX-1: When temp file length >= totalSize, do not trust it blindly —
    // the temp may be the result of a crashed write or a stale pre-allocated
    // file. Validate via the saved state first; if no usable state, force a
    // fresh restart so the byte source of truth is the network, not disk.
    final stateFile = File(StateStore.pathFor(cmd.tempFilePath));
    final hasUsableState = await stateFile.exists() &&
        st.downloadedBytes > 0 &&
        st.chunks.isNotEmpty;

    if (await tempFile.exists()) {
      final len = await tempFile.length();
      if (st.totalSize > 0 && len >= st.totalSize) {
        if (hasUsableState && st.isComplete) {
          chunk.downloaded = st.totalSize;
          _emitProgress(0, statusMessage: 'Completed');
          return;
        }
        // FIX-1: state missing/incomplete but file is full → corrupt or
        // stale. Truncate to zero and re-download to guarantee integrity.
        debugPrint(
            '[DMX-Job] FIX-1: temp file full but state unusable — restarting single-stream');
        chunk.downloaded = 0;
        await tempFile.delete();
        try {
          await StateStore.remove(cmd.tempFilePath);
        } catch (_) {}
        st.chunks = ChunkScheduler.singleStream(st.totalSize);
      } else if (cmd.supportsResume) {
        chunk.downloaded = st.totalSize > 0 ? len.clamp(0, st.totalSize) : len;
      } else {
        chunk.downloaded = 0;
        await tempFile.delete();
      }
    }

    final governor = BandwidthGovernor(_effectiveGlobalLimit());
    governor.registerConsumer();
    if (cmd.speedLimitKbps > 0) {
      governor.setTaskLimit(cmd.taskId, cmd.speedLimitKbps * 125);
    }

    // FIX-2: Single-stream resume spot-check — parity with multi-thread.
    // Validates the first 64 KB of the resumed prefix against the server so
    // a truncated/modified temp file is detected BEFORE we append more bytes
    // and corrupt the final output.
    if (chunk.downloaded > 0 &&
        cmd.supportsResume &&
        SettingsProvider.instance.resumeIntegrityCheck &&
        await tempFile.exists()) {
      try {
        const sampleSize = 64 * 1024;
        final len = min(sampleSize, chunk.downloaded);
        final raf = await tempFile.open(mode: FileMode.read);
        try {
          final diskBytes = await raf.read(len);
          final response = await dio.get<ResponseBody>(
            cmd.punyUrl,
            cancelToken: _cancelToken,
            options: Options(
              responseType: ResponseType.stream,
              headers: {'Range': 'bytes=0-${len - 1}'},
              validateStatus: (_) => true,
            ),
          );
          if (response.statusCode == 206 && response.data != null) {
            final builder = BytesBuilder(copy: false);
            await for (final b in response.data!.stream) {
              builder.add(b);
            }
            final netBytes = builder.takeBytes();
            if (netBytes.length != diskBytes.length ||
                !listEquals(netBytes, diskBytes)) {
              debugPrint(
                  '[DMX-Job] FIX-2: single-stream spot-check mismatch — restarting');
              chunk.downloaded = 0;
              await tempFile.delete();
              try {
                await StateStore.remove(cmd.tempFilePath);
              } catch (_) {}
              st.chunks = ChunkScheduler.singleStream(st.totalSize);
            }
          } else {
            await response.data?.stream.listen((_) {}).cancel();
          }
        } finally {
          await raf.close();
        }
      } catch (e) {
        debugPrint('[DMX-Job] FIX-2: spot-check probe failed (continuing): $e');
      }
    }

    var attempts = 0;
    const maxAttempts = 3;
    final failover = MirrorFailover([cmd.punyUrl, ...?cmd.mirrorUrls]);
    var activeUrl = failover.activeUrl;

    while (!st.isComplete || st.totalSize <= 0) {
      _throwIfCancelled();
      attempts++;
      IOSink? sink;
      try {
        final resumeFrom = chunk.downloaded;
        final headers = <String, dynamic>{};
        if (resumeFrom > 0 && cmd.supportsResume) {
          headers['Range'] = 'bytes=$resumeFrom-';
          final ifRange = _firstNonEmpty(st.etag, st.lastModified);
          if (ifRange != null) headers['If-Range'] = ifRange;
        }
        final response = await dio.get<ResponseBody>(
          activeUrl,
          cancelToken: _cancelToken,
          options: Options(
            responseType: ResponseType.stream,
            followRedirects: true,
            headers: headers,
            validateStatus: (_) => true,
          ),
        );

        if (response.statusCode == 416) {
          await response.data?.stream.listen((_) {}).cancel();
          if (st.totalSize > 0 && chunk.downloaded >= st.totalSize) break;
          chunk.downloaded = 0;
          if (await tempFile.exists()) await tempFile.delete();
          continue;
        }
        if (response.statusCode == 200 && resumeFrom > 0) {
          await response.data?.stream.listen((_) {}).cancel();
          for (final p in [
            '${cmd.tempFilePath}.dmxstate',
            '${cmd.tempFilePath}.dmxstate.tmp',
          ]) {
            try {
              final f = File(p);
              if (await f.exists()) await f.delete();
            } catch (_) {}
          }
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'Server rejected resume: expected HTTP 206. Got 200.',
          );
        }
        if (response.statusCode != 200 && response.statusCode != 206) {
          await response.data?.stream.listen((_) {}).cancel();
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'Server returned status code ${response.statusCode}',
          );
        }
        final contentType =
            response.headers.value('content-type')?.toLowerCase() ?? '';
        if (contentType.contains('text/html') ||
            contentType.contains('application/xhtml')) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'HTML_INSTEAD_OF_MEDIA',
          );
        }

        final isPartial = response.statusCode == 206;
        if (resumeFrom > 0 && !isPartial) {
          // Server ignored Range on a fresh 200 → restart cleanly.
          chunk.downloaded = 0;
          if (await tempFile.exists()) await tempFile.delete();
        }
        if (isPartial) {
          final contentRange = response.headers.value('content-range');
          if (contentRange != null) {
            _validateContentRange(
              contentRange,
              expectedStart: chunk.downloaded,
              expectedEnd: st.totalSize > 0 ? st.totalSize - 1 : -1,
              expectedTotal: st.totalSize,
              allowUnknown: chunk.downloaded == 0,
            );
          }
        }

        st.etag ??= response.headers.value('etag');
        st.lastModified ??= response.headers.value('last-modified');
        final contentLength = int.tryParse(
                response.headers.value(Headers.contentLengthHeader) ?? '') ??
            0;
        if (contentLength > 0) {
          final actual = (isPartial ? chunk.downloaded : 0) + contentLength;
          if (st.totalSize <= 0 || actual != st.totalSize) {
            st.totalSize = actual;
            chunk.end = actual - 1;
          }
        }

        sink = tempFile.openWrite(
          mode: chunk.downloaded > 0 ? FileMode.append : FileMode.write,
        );

        final stream = response.data?.stream;
        if (stream == null) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            message: 'Empty response body.',
          );
        }
        // FIX-AUDIT-02: Flush and save state on cancel to preserve latest progress
        try {
          await for (final piece in stream) {
            _throwIfCancelled();
            final sleepMs =
                await governor.acquire(piece.length, taskId: cmd.taskId);
            if (sleepMs > 0) {
              await _cancellableDelay(Duration(milliseconds: sleepMs));
              _throwIfCancelled();
            }
            sink.add(piece);
            chunk.downloaded += piece.length;
            // FIX-SIZE-LIVE: For unknown-size streams, do NOT set chunk.end
            // to downloaded-1 mid-stream. That makes ChunkState.size ==
            // downloaded and ChunkState.ratio always 1.0, falsely showing
            // 100% during active download. Keep chunk.end = -1 so ratio
            // returns 0.0 (indeterminate); the UI renders an indeterminate
            // bar and uses `downloaded` as the byte indicator. Final size
            // is confirmed at stream end below.
            _bytesSinceSave += piece.length;
            // FIX-SINGLE-FLUSH: Flush IOSink before state save so state
            // file never claims bytes still in OS buffer.
            await _throttledSaveAndReport(
              null,
              preSaveFlush: () async {
                await sink?.flush();
              },
            );
          }
        } on DioException catch (e) {
          if (e.type == DioExceptionType.cancel) {
            rethrow;
          }
          rethrow;
        }
        await sink.flush();
        await sink.close();
        sink = null;
        failover.reportSuccess();
        attempts = 0;

        if (st.totalSize <= 0) {
          // Unknown-size transfer finished: the stream IS the total.
          st.totalSize = chunk.downloaded;
          chunk.end = chunk.downloaded - 1;
        }
        break;
      } on DioException catch (e) {
        if (e.type == DioExceptionType.cancel) {
          _state!.status = DmxStateStatus.paused;
          rethrow;
        }
        if (e.message == 'HTML_INSTEAD_OF_MEDIA') {
          _state!.status = DmxStateStatus.failed;
          rethrow;
        }
        if (e.message?.startsWith('Server rejected resume') == true) {
          _state!.status = DmxStateStatus.failed;
          rethrow;
        }
        final status = e.response?.statusCode;
        if (status != null &&
            status >= 400 &&
            status < 500 &&
            status != 408 &&
            status != 429) {
          _state!.status = DmxStateStatus.failed;
          rethrow;
        }
        if (attempts >= maxAttempts) {
          _state!.status = DmxStateStatus.failed;
          final next = failover.advance();
          if (next != null) {
            activeUrl = next;
            attempts = 0;
            _state!.status = DmxStateStatus.active;
            _emitProgress(_stopwatch.elapsedMilliseconds,
                statusMessage: 'Retrying (mirror failover)…');
            continue;
          }
          rethrow;
        }
        _emitProgress(_stopwatch.elapsedMilliseconds,
            statusMessage: 'Retrying…');
        await _cancellableDelay(
            Duration(seconds: (attempts * attempts * 2) + Random().nextInt(3)));
      } finally {
        try {
          await sink?.flush();
          await sink?.close();
        } catch (_) {}
        // FIX-14: Always save state on exit (cancel or error)
        try {
          await StateStore.save(cmd.tempFilePath, _state!);
        } catch (_) {}
      }
    }

    // Final integrity: disk must match the claim.
    final actualLen = await tempFile.length();
    if (st.totalSize > 0 && actualLen != st.totalSize) {
      if (actualLen > st.totalSize) {
        final raf = await tempFile.open(mode: FileMode.writeOnly);
        await raf.truncate(st.totalSize);
        await raf.close();
      } else {
        st.status = DmxStateStatus.failed;
        await StateStore.save(cmd.tempFilePath, st);
        throw DownloadIntegrityException(
            'expected ${st.totalSize} bytes, got $actualLen');
      }
    }
    governor.removeTaskLimit(cmd.taskId);
    governor.unregisterConsumer();
  }

  // ── Shared helpers ───────────────────────────────────────────────────────

  Future<void> _finalize(Dio dio) async {
    final st = _state!;
    st.status = DmxStateStatus.complete;
    await StateStore.save(cmd.tempFilePath, st); // transition save
    _emitProgress(0, statusMessage: 'Completed');

    if (cmd.tempFilePath != cmd.localFilePath) {
      // FIX-C2: Skip rename if final file already exists (merge path)
      final tempExists = await File(cmd.tempFilePath).exists();
      if (!tempExists) {
        // File already moved by merge — skip rename entirely
        debugPrint('[DMX] FIX-C2: temp file gone, skipping rename');
      } else {
        final finalFile = File(cmd.localFilePath);
        await finalFile.parent.create(recursive: true);
        if (await finalFile.exists()) await finalFile.delete();
        try {
          await File(cmd.tempFilePath).rename(cmd.localFilePath);
        } catch (e) {
          await File(cmd.tempFilePath).copy(cmd.localFilePath);
          final copiedLen = await File(cmd.localFilePath).length();
          final origLen = await File(cmd.tempFilePath).length();
          if (copiedLen == origLen) {
            await File(cmd.tempFilePath).delete();
          } else {
            throw const DownloadIntegrityException(
                'File copy verification failed on rename fallback.');
          }
        }
      }
    }
    await StateStore.remove(cmd.tempFilePath);
  }

  int _effectiveGlobalLimit() {
    if (_workerGlobalLimitBps > 0) {
      return (_workerGlobalLimitBps / _workerGlobalActive).floor();
    }
    return cmd.initialSpeedLimit > 0
        ? (cmd.initialSpeedLimit / max(1, cmd.initialActiveCount)).floor()
        : 0;
  }

  void _throwIfCancelled() {
    if (_cancelRequested || _cancelToken.isCancelled) {
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.cancel,
        message: 'Download cancelled.',
      );
    }
  }

  Future<void> _cancellableDelay(Duration duration) async {
    if (_cancelRequested) return;
    final completer = Completer<void>();
    final timer = Timer(duration, () {
      if (!completer.isCompleted) completer.complete();
    });
    final sub = _cancelToken.whenCancel.then((_) {
      timer.cancel();
      if (!completer.isCompleted) completer.complete();
    });
    await completer.future;
    await sub;
  }

  /// Bounded-interval persistence + progress emission, both derived from the
  /// SAME TransferState snapshot.
  Future<void> _throttledSaveAndReport(
    PositionalFileWriter? writer, {
    Future<void> Function()? preSaveFlush,
  }) async {
    final nowMs = _stopwatch.elapsedMilliseconds;
    final st = _state!;
    final dueSave = nowMs - _lastStateSaveMs >= _stateSaveIntervalMs ||
        _bytesSinceSave >= _stateSaveByteThreshold;
    final dueReport = nowMs - _lastReportMs >= 500;

    if (dueSave) {
      _lastStateSaveMs = nowMs;
      _bytesSinceSave = 0;
      try {
        // FIX-SINGLE-FLUSH: For single-stream downloads (writer == null),
        // flush the IOSink before saving state so the state file never
        // claims bytes that are still buffered in the OS file buffer.
        // Without this, a crash between state save and sink flush leaves
        // the state file ahead of the actual file on disk, causing a
        // corrupt resume on the next start.
        if (preSaveFlush != null) await preSaveFlush();
        if (writer != null) await writer.flush();
        await StateStore.save(cmd.tempFilePath, st);
      } catch (e) {
        debugPrint('[DMX-Job] state save failed: $e');
      }
    }
    if (dueReport) {
      _lastReportMs = nowMs;
      _emitProgress(nowMs);
    }
  }

  void _emitProgress(int nowMs, {String? statusMessage}) {
    final st = _state!;
    final downloaded = st.downloadedBytes;
    final total = st.totalSize;

    _speedSamples.add(_SpeedSample(_stopwatch.elapsedMilliseconds, downloaded));
    while (_speedSamples.isNotEmpty &&
        _stopwatch.elapsedMilliseconds - _speedSamples.first.timestampMs >
            3000) {
      _speedSamples.removeFirst();
    }
    var speed = 0.0;
    if (_speedSamples.length > 1) {
      final first = _speedSamples.first;
      final elapsed =
          (_stopwatch.elapsedMilliseconds - first.timestampMs) / 1000;
      if (elapsed > 0) speed = (downloaded - first.bytes) / elapsed;
    }
    int? eta;
    final remaining = total - downloaded;
    if (speed.isFinite && speed > 0 && remaining > 0) {
      final raw = (remaining / speed).round().clamp(0, 86400 * 365);
      eta = _lastEta == null ? raw : ((_lastEta! * 0.7) + (raw * 0.3)).round();
      _lastEta = eta;
    } else {
      _lastEta = null;
    }

    // FIX-CHUNK-DETAILS: Always emit per-chunk details so the HTTP details
    // screen can render progress for every part — including single-stream
    // downloads where there is exactly one chunk. Previously chunkDetails
    // was null for single-stream, so the details screen showed nothing.
    final chunkDetails = st.chunks.isNotEmpty
        ? st.chunks.asMap().entries.map((e) {
            final c = e.value;
            return <String, dynamic>{
              'index': e.key,
              'start': c.start,
              'end': c.end,
              'downloaded': c.downloaded,
              'size': c.size,
              'ratio': c.ratio,
            };
          }).toList()
        : null;

    _send('progress', {
      'downloadedBytes': downloaded,
      'fileSize': total,
      'speed': speed,
      'eta': eta,
      'chunks': st.chunks.isNotEmpty ? st.chunkRatios : null,
      'chunkDetails': chunkDetails,
      'fileName': cmd.resolvedFileName,
      'supportsResume': cmd.supportsResume,
      if (cmd.ytStreamKind != null) 'ytStreamKind': cmd.ytStreamKind!.name,
      if (cmd.ytCounterpartSize != null)
        'ytCounterpartSize': cmd.ytCounterpartSize,
      if (cmd.ytCounterpartDownloadedBytes != null)
        'ytCounterpartDownloadedBytes': cmd.ytCounterpartDownloadedBytes,
      // FIX-YT-LIVE: Emit THIS stream's live downloaded bytes so the main
      // isolate can populate DownloadEngine._ytLiveBytes[taskId] and the
      // counterpart's combined percentage always reflects BOTH streams.
      'ytDownloadedBytes': downloaded,
      // FIX-CYCLE: Emit statusMessage so _deriveCycleState can map
      // 'Completed' → 'completed', 'Updating links…' → 'updating_links',
      // 'Checking pieces…' → 'checking', etc. Without this, every cycle
      // state defaults to 'downloading' regardless of actual status.
      'statusMessage': statusMessage,
    });
  }

  void _validateContentRange(
    String? value, {
    required int expectedStart,
    required int expectedEnd,
    required int expectedTotal,
    bool allowUnknown = false,
  }) {
    if (value == null || value.trim().isEmpty) {
      if (allowUnknown) return;
      return;
    }
    final match =
        RegExp(r'^bytes\s+(\d+)-(\d+)/(\d+|\*)$', caseSensitive: false)
            .firstMatch(value.trim());
    if (match == null) {
      if (allowUnknown) return;
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.badResponse,
        message: 'Malformed Content-Range during resume: $value.',
      );
    }
    final start = int.tryParse(match.group(1) ?? '');
    final end = int.tryParse(match.group(2) ?? '');
    final totalText = match.group(3);
    final total =
        totalText == null || totalText == '*' ? null : int.tryParse(totalText);
    if (start != expectedStart ||
        (expectedEnd >= 0 && end != expectedEnd) ||
        (expectedTotal > 0 && total != null && total != expectedTotal)) {
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.badResponse,
        message: 'Invalid Content-Range response: $value. '
            'Expected start $expectedStart got $start.',
      );
    }
  }
}

class _SpeedSample {
  final int timestampMs;
  final int bytes;
  _SpeedSample(this.timestampMs, this.bytes);
}
