part of 'download_engine.dart';

class EngineMessage {
  EngineMessage._(this.type, this.taskId, this.data, this.seq);
  static const int protocolVersion = 1;
  final String type;
  final String taskId;
  final Map<String, dynamic> data;
  final int seq;
  static Map<String, dynamic> encode({
    required String type,
    required String taskId,
    int seq = 0,
    Map<String, dynamic>? data,
  }) =>
      {
        'proto': protocolVersion,
        'type': type,
        'taskId': taskId,
        'seq': seq,
        if (data != null) 'data': data,
      };
  static EngineMessage? tryDecode(dynamic raw) {
    try {
      if (raw is! Map) return null;
      if (raw['proto'] != protocolVersion) return null;
      final type = raw['type'];
      final taskId = raw['taskId'];
      if (type is! String || taskId is! String) return null;
      final data = raw['data'];
      return EngineMessage._(
        type,
        taskId,
        data is Map ? Map<String, dynamic>.from(data) : <String, dynamic>{},
        (raw['seq'] as num?)?.toInt() ?? 0,
      );
    } catch (_) {
      return null;
    }
  }
}

class DownloadCommand {
  const DownloadCommand({
    required this.taskId,
    required this.url,
    required this.punyUrl,
    required this.tempFilePath,
    required this.localFilePath,
    required this.knownFileSize,
    required this.supportsResume,
    required this.threadCount,
    this.bypassSSL = true,
    this.isNameAutoGenerated = false,
    this.adaptiveThreads = false,
    this.initialSpeedLimit = 0,
    this.initialActiveCount = 1,
    this.speedLimitKbps = 0,
    int? speedLimit,
    int? activeCount,
    this.customUserAgent,
    this.referer,
    this.cookies,
    this.oauthToken,
    this.mirrorUrls,
    this.resolvedFileName,
    this.ytStreamKind,
    this.ytCounterpartSize,
    this.ytCounterpartDownloadedBytes,
    this.ytCounterpartTaskId,
  });
  final String taskId;
  final String url;
  final String punyUrl;
  final String tempFilePath;
  final String localFilePath;
  final int knownFileSize;
  final bool supportsResume;
  final int threadCount;
  final String? customUserAgent;
  final String? referer;

  final bool bypassSSL;
  final String? cookies;
  final String? oauthToken;
  final bool isNameAutoGenerated;
  final int initialSpeedLimit;
  final int initialActiveCount;
  final int speedLimitKbps;
  final List<String>? mirrorUrls;
  final bool adaptiveThreads;
  final String? resolvedFileName;
  final YtStreamKind? ytStreamKind;
  final int? ytCounterpartSize;
  final int? ytCounterpartDownloadedBytes;
  final String? ytCounterpartTaskId;
  Map<String, dynamic> toMap() => {
        'taskId': taskId,
        'url': url,
        'punyUrl': punyUrl,
        'tempFilePath': tempFilePath,
        'localFilePath': localFilePath,
        'knownFileSize': knownFileSize,
        'supportsResume': supportsResume,
        'threadCount': threadCount,
        'customUserAgent': customUserAgent,
        'referer': referer,
        'bypassSSL': bypassSSL,
        'cookies': cookies,
        'oauthToken': oauthToken,
        'isNameAutoGenerated': isNameAutoGenerated,
        'initialSpeedLimit': initialSpeedLimit,
        'initialActiveCount': initialActiveCount,
        'speedLimitKbps': speedLimitKbps,
        'mirrorUrls': mirrorUrls,
        'adaptiveThreads': adaptiveThreads,
        'resolvedFileName': resolvedFileName,
        if (ytStreamKind != null) 'ytStreamKind': ytStreamKind!.name,
        if (ytCounterpartSize != null) 'ytCounterpartSize': ytCounterpartSize,
        if (ytCounterpartDownloadedBytes != null)
          'ytCounterpartDownloadedBytes': ytCounterpartDownloadedBytes,
        if (ytCounterpartTaskId != null)
          'ytCounterpartTaskId': ytCounterpartTaskId,
      };
  static DownloadCommand fromMap(Map<String, dynamic> m) => DownloadCommand(
        taskId: m['taskId'] as String,
        url: m['url'] as String,
        punyUrl: m['punyUrl'] as String,
        tempFilePath: m['tempFilePath'] as String,
        localFilePath: m['localFilePath'] as String,
        knownFileSize: (m['knownFileSize'] as num?)?.toInt() ?? 0,
        supportsResume: m['supportsResume'] as bool? ?? false,
        threadCount: (m['threadCount'] as num?)?.toInt() ?? 1,
        customUserAgent: m['customUserAgent'] as String?,
        referer: m['referer'] as String?,
        bypassSSL: m['bypassSSL'] as bool? ?? true,
        cookies: m['cookies'] as String?,
        oauthToken: m['oauthToken'] as String?,
        isNameAutoGenerated: m['isNameAutoGenerated'] as bool? ?? false,
        initialSpeedLimit: (m['initialSpeedLimit'] as num?)?.toInt() ?? 0,
        initialActiveCount: (m['initialActiveCount'] as num?)?.toInt() ?? 1,
        speedLimitKbps: (m['speedLimitKbps'] as num?)?.toInt() ?? 0,
        mirrorUrls: (m['mirrorUrls'] as List?)?.cast<String>(),
        adaptiveThreads: m['adaptiveThreads'] as bool? ?? false,
        resolvedFileName: m['resolvedFileName'] as String?,
        ytStreamKind: m['ytStreamKind'] != null
            ? YtStreamKind.values.firstWhere(
                (k) => k.name == m['ytStreamKind'],
                orElse: () => YtStreamKind.combined,
              )
            : null,
        ytCounterpartSize: (m['ytCounterpartSize'] as num?)?.toInt(),
        ytCounterpartDownloadedBytes:
            (m['ytCounterpartDownloadedBytes'] as num?)?.toInt(),
        ytCounterpartTaskId: m['ytCounterpartTaskId'] as String?,
      );
}

class DownloadIsolatePool {
  DownloadIsolatePool({int size = 4, bool powerAware = false})
      : _size = size,
        _powerAware = powerAware;
  final int _size;
  final bool _powerAware;
  final List<_Worker> _workers = [];
  final List<PoolJob> _queue = [];
  bool _shuttingDown = false;
  int _seq = 0;
  int get maxJobsPerWorker =>
      PowerMonitor.batterySaverMode == BatterySaverMode.aggressive ? 1 : 2;
  int get workerCount {
    final live = _workers.length;
    if (live <= 0) return 0;
    if (_powerAware &&
        PowerMonitor.batterySaverMode == BatterySaverMode.aggressive) {
      return 1;
    }
    return live;
  }

  bool _isSpawning = false;
  Timer? _idleCheckTimer;

  int get effectiveMaxSize {
    if (_powerAware &&
        PowerMonitor.batterySaverMode == BatterySaverMode.aggressive) {
      return 1;
    }
    if (PowerMonitor.screenOff) {
      return max(1, _size ~/ 2);
    }
    return _size;
  }

  Future<void> init() async {
    if (_workers.isEmpty) {
      _workers.add(await _spawnWorker(0));
    }
    _startIdleCheckTimer();
  }

  void _startIdleCheckTimer() {
    _idleCheckTimer?.cancel();
    _idleCheckTimer = Timer.periodic(const Duration(seconds: 15), (_) {
      _checkIdleWorkers();
    });
  }

  void _checkIdleWorkers() {
    if (_shuttingDown || _workers.length <= 1) return;
    final now = DateTime.now();
    final toRemove = <_Worker>[];

    for (final w in _workers) {
      if (w.activeJobs == 0 &&
          !w.dead &&
          w.pending.isEmpty &&
          now.difference(w.lastActiveTime) > const Duration(seconds: 30)) {
        toRemove.add(w);
        if (_workers.length - toRemove.length <= 1) break;
      }
    }

    for (final w in toRemove) {
      _workers.remove(w);
      w.commandPort?.send({'t': 'shutdown'});
      w.inbox.close();
      w.errorPort.close();
      w.isolate.kill(priority: Isolate.beforeNextEvent);
    }
  }

  Future<_Worker> _spawnWorker(int index) async {
    final inbox = ReceivePort();
    final errorPort = ReceivePort();
    final isolate = await Isolate.spawn(
      _workerEntry,
      inbox.sendPort,
      errorsAreFatal: true,
      onError: errorPort.sendPort,
      debugName: 'dmx-engine-worker-$index',
    );
    final worker =
        _Worker(isolate: isolate, inbox: inbox, errorPort: errorPort);
    inbox.listen((dynamic msg) => _onWorkerMessage(worker, msg));
    errorPort.listen((dynamic err) => _onWorkerCrash(worker, err));
    return worker;
  }

  Future<void> _maybeExpandWorkers() async {
    if (_isSpawning || _shuttingDown || _workers.length >= effectiveMaxSize) {
      return;
    }
    _isSpawning = true;
    try {
      final newIndex = _workers.length;
      final worker = await _spawnWorker(newIndex);
      if (!_shuttingDown) {
        _workers.add(worker);
      } else {
        worker.inbox.close();
        worker.errorPort.close();
        worker.isolate.kill(priority: Isolate.immediate);
      }
    } catch (e) {
      // spawn failed
    } finally {
      _isSpawning = false;
      _drain();
    }
  }

  PoolJob submit(DownloadCommand command, {int priority = 0}) {
    if (_shuttingDown) {
      throw const IsolateSpawnTimeoutException();
    }
    final job = PoolJob._(this, command, _seq++);
    if (_shuttingDown) {
      scheduleMicrotask(() =>
          job._deliverError('workerDied', 'Engine is shutting down', null));
      return job;
    }
    _dispatch(job, priority);
    return job;
  }

  void _dispatch(PoolJob job, int priority) {
    job.priority = priority;
    final slots = maxJobsPerWorker;
    _Worker? worker;
    for (final w in _workers) {
      if (!w.dead && w.commandPort != null && w.activeJobs < slots) {
        worker = w;
        break;
      }
    }
    if (worker == null) {
      _queue.add(job);
      if (_workers.length < effectiveMaxSize) {
        _maybeExpandWorkers();
      }
      return;
    }
    worker.activeJobs++;
    worker.pending.add(job);
    worker.lastActiveTime = DateTime.now();
    job._worker = worker;
    worker.commandPort?.send({
      't': 'job',
      'jobId': job.command.taskId,
      'reply': job._incoming.sendPort,
      'cmd': job.command.toMap(),
    });
  }

  void _onWorkerMessage(_Worker worker, dynamic msg) {
    if (msg is! Map) return;
    switch (msg['t']) {
      case 'hello':
        worker.commandPort = msg['port'] as SendPort;
        _drain();
      case 'idle':
        worker.activeJobs = (worker.activeJobs - 1).clamp(0, 1 << 30);
        if (worker.activeJobs == 0) {
          worker.lastActiveTime = DateTime.now();
        }
        final doneId = msg['jobId'];
        worker.pending.removeWhere((j) => j.command.taskId == doneId);
        _drain();
      case 'limits':
        break;
    }
  }

  void _drain() {
    while (_queue.isNotEmpty) {
      final slots = maxJobsPerWorker;
      _Worker? worker;
      for (final w in _workers) {
        if (!w.dead && w.commandPort != null && w.activeJobs < slots) {
          worker = w;
          break;
        }
      }
      if (worker == null) {
        if (_workers.length < effectiveMaxSize) {
          _maybeExpandWorkers();
        }
        return;
      }
      final job = _removeHighestPriority();
      if (job == null) return;
      worker.activeJobs++;
      worker.pending.add(job);
      worker.lastActiveTime = DateTime.now();
      job._worker = worker;
      worker.commandPort!.send({
        't': 'job',
        'jobId': job.command.taskId,
        'reply': job._incoming.sendPort,
        'cmd': job.command.toMap(),
      });
    }
  }

  PoolJob? _removeHighestPriority() {
    if (_queue.isEmpty) return null;
    var best = 0;
    for (var i = 1; i < _queue.length; i++) {
      final a = _queue[best];
      final b = _queue[i];
      if (b.priority > a.priority ||
          (b.priority == a.priority && b.seq < a.seq)) {
        best = i;
      }
    }
    return _queue.removeAt(best);
  }

  void _onWorkerCrash(_Worker worker, dynamic err) {
    worker.dead = true;
    final jobs = List<PoolJob>.from(worker.pending);
    worker.pending.clear();
    worker.activeJobs = 0;
    for (final job in jobs) {
      job._deliverError('workerDied', 'Worker isolate died: $err', null);
    }
    worker.inbox.close();
    worker.errorPort.close();
    worker.isolate.kill(priority: Isolate.immediate);
    if (!_shuttingDown) {
      _workers.remove(worker);
      if (_workers.isEmpty) {
        _spawnWorker(0).then((w) {
          _workers.add(w);
          _drain();
        });
      } else {
        _drain();
      }
    }
  }

  void _cancelJob(PoolJob job) {
    job._worker?.commandPort
        ?.send({'t': 'cancel', 'jobId': job.command.taskId});
  }

  void updateSpeedLimit(int bytesPerSecond, int activeCount) {
    for (final w in _workers) {
      w.commandPort
          ?.send({'t': 'limits', 'bps': bytesPerSecond, 'active': activeCount});
    }
  }

  Future<void> shutdown() async {
    _shuttingDown = true;
    _idleCheckTimer?.cancel();
    _idleCheckTimer = null;
    _queue.clear();
    for (final w in _workers) {
      w.commandPort?.send({'t': 'shutdown'});
      await Future<void>.delayed(const Duration(milliseconds: 50));
      w.inbox.close();
      w.errorPort.close();
      w.isolate.kill(priority: Isolate.beforeNextEvent);
    }
    _workers.clear();
  }

  Future<void> dispose() async {
    await shutdown();
  }

  Future<void> drain({Duration? timeout}) async {
    await shutdown();
  }

  void onMemoryPressure() {
    if (_workers.length > 1) {
      final w = _workers.removeLast();
      w.inbox.close();
      w.errorPort.close();
      w.isolate.kill(priority: Isolate.immediate);
    }
  }
}

class _Worker {
  _Worker({
    required this.isolate,
    required this.inbox,
    required this.errorPort,
  });
  final Isolate isolate;
  final ReceivePort inbox;
  final ReceivePort errorPort;
  SendPort? commandPort;
  final List<PoolJob> pending = [];
  int activeJobs = 0;
  bool dead = false;
  DateTime lastActiveTime = DateTime.now();
}

class PoolJob {
  PoolJob._(this._pool, this.command, this._seq) {
    messages = _incoming
        .map(EngineMessage.tryDecode)
        .where((m) {
          if (m == null) {
            debugPrint('[DMX-Pool] dropped undecodable engine message');
            return false;
          }
          return true;
        })
        .cast<EngineMessage>()
        .asBroadcastStream();
  }
  final DownloadIsolatePool _pool;
  final DownloadCommand command;
  final int _seq;
  int priority = 0;
  int get seq => _seq;
  final ReceivePort _incoming = ReceivePort();
  _Worker? _worker;
  late final Stream<EngineMessage> messages;
  bool _disposed = false;
  void cancel() => _pool._cancelJob(this);
  void _deliverError(String type, String message, int? status) {
    if (_disposed) return;
    _incoming.sendPort.send(EngineMessage.encode(
      type: 'error',
      taskId: command.taskId,
      data: {'errorType': type, 'errorMessage': message, 'errorStatus': status},
    ));
  }

  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _incoming.close();
  }
}

int _workerGlobalLimitBps = 0;
int _workerGlobalActive = 1;
final Map<String, HttpTransferJob> _runningJobs = {};
Future<void> _workerEntry(SendPort poolPort) async {
  final cmdPort = ReceivePort();
  poolPort.send({'t': 'hello', 'port': cmdPort.sendPort});
  await for (final dynamic raw in cmdPort) {
    if (raw is! Map) continue;
    switch (raw['t']) {
      case 'job':
        final jobId = raw['jobId'] as String;
        final reply = raw['reply'] as SendPort;
        final cmd = DownloadCommand.fromMap(
            Map<String, dynamic>.from(raw['cmd'] as Map));
        final job = HttpTransferJob(cmd, reply);
        _runningJobs[jobId] = job;
        Future(() async {
          try {
            await job.run();
          } catch (e) {
            job.sendUnhandledError(e);
          } finally {
            _runningJobs.remove(jobId);
            poolPort.send({'t': 'idle', 'jobId': jobId});
          }
        });
        break;
      case 'cancel':
        _runningJobs[raw['jobId'] as String]?.requestCancel();
        break;
      case 'limits':
        _workerGlobalLimitBps = (raw['bps'] as num?)?.toInt() ?? 0;
        _workerGlobalActive =
            ((raw['active'] as num?)?.toInt() ?? 1).clamp(1, 1000);
        break;
      case 'shutdown':
        cmdPort.close();
        return;
    }
  }
}

class _RangeUnsupportedException implements Exception {}

class _FileChangedOnServerException implements Exception {
  @override
  String toString() => 'File changed on server. Restart required.';
}

class HttpTransferJob {
  HttpTransferJob(this.cmd, this.out);
  final DownloadCommand cmd;
  final SendPort out;
  final CancelToken _cancelToken = CancelToken();
  int _seq = 0;
  bool _cancelRequested = false;
  TransferState? _state;
  int? _lastEta;
  int _lastStateSaveMs = 0;
  int _lastReportMs = 0;
  int _bytesSinceSave = 0;
  final Stopwatch _stopwatch = Stopwatch();
  final Queue<_SpeedSample> _speedSamples = Queue();
  static const int _stateSaveIntervalMs = 2000;
  static const int _stateSaveByteThreshold = 256 * 1024;
  void requestCancel() {
    _cancelRequested = true;
    if (!_cancelToken.isCancelled) _cancelToken.cancel('paused');
  }

  void _send(String type, [Map<String, dynamic>? data]) {
    out.send(EngineMessage.encode(
        type: type, taskId: cmd.taskId, seq: _seq++, data: data));
  }

  void sendUnhandledError(Object e) {
    if (e is DioException && e.type == DioExceptionType.cancel) {
      _send('error', {
        'errorType': 'cancel',
        'errorMessage': e.message ?? 'cancelled',
      });
      return;
    }
    if (e is DownloadIntegrityException) {
      _send('error', {'errorType': 'integrity', 'errorMessage': e.message});
      return;
    }
    if (e is InsufficientStorageException ||
        (e is PositionalFileWriterException && _looksLikeDiskFull(e.message))) {
      _send('error', {'errorType': 'diskFull', 'errorMessage': e.toString()});
      return;
    }
    if (e is _FileChangedOnServerException) {
      _send('error', {
        'errorType': 'fileChanged',
        'errorMessage': 'File changed on server. Restart required.',
      });
      return;
    }
    if (e is UrlExpiredException) {
      _send('error', {
        'errorType': 'urlExpired',
        'errorMessage': e.message,
        'refreshAllMirrors': true,
      });
      return;
    }
    if (e is DioException) {
      _send('error', {
        'errorType': switch (e.type) {
          DioExceptionType.cancel => 'cancel',
          DioExceptionType.badResponse => 'badResponse',
          DioExceptionType.connectionTimeout => 'connectionTimeout',
          DioExceptionType.receiveTimeout => 'receiveTimeout',
          DioExceptionType.sendTimeout => 'sendTimeout',
          DioExceptionType.connectionError => 'connectionError',
          _ => 'uncaught',
        },
        'errorMessage': e.message ?? e.toString(),
        'errorStatus': e.response?.statusCode,
      });
      return;
    }
    _send('error', {'errorType': 'uncaught', 'errorMessage': e.toString()});
  }

  static bool _looksLikeDiskFull(String msg) {
    final m = msg.toLowerCase();
    return m.contains('enospc') || m.contains('no space left');
  }

  Future<void> run() async {
    _stopwatch.start();
    final dio = buildTransferDio(
      url: cmd.punyUrl,
      customUserAgent: cmd.customUserAgent,
      referer: cmd.referer,
      bypassSSL: cmd.bypassSSL,
      cookies: cmd.cookies,
      oauthToken: cmd.oauthToken,
    );
    _send('ack');
    try {
      final load = await StateStore.loadOrCreate(
        cmd.tempFilePath,
        url: cmd.url,
        threadCount: cmd.threadCount,
        knownFileSize: cmd.knownFileSize,
      );
      _state = load.state;
      if (_state!.chunks.isNotEmpty &&
          _state!.chunks.length != cmd.threadCount &&
          _state!.downloadedBytes > 0) {
        final savedBytes = _state!.downloadedBytes;
        final total = _state!.totalSize;
        final newChunks = ChunkScheduler.plan(
          totalSize: total,
          threadCount: cmd.threadCount,
        );
        var remaining = savedBytes;
        for (var i = 0; i < newChunks.length; i++) {
          final capacity =
              newChunks[i].size >= 0 ? newChunks[i].size : remaining;
          final take = remaining.clamp(0, capacity);
          newChunks[i].downloaded = take;
          remaining -= take;
        }
        _state!.chunks = newChunks;
        debugPrint(
          '[FIX-4/H-R1] Redistributed $savedBytes bytes from '
          '${load.state.chunks.length} → ${cmd.threadCount} chunks '
          '(leftover=$remaining)',
        );
      }
      if (_state!.totalSize <= 0 && cmd.knownFileSize > 0) {
        _state!.totalSize = cmd.knownFileSize;
      }
      _state!.status = DmxStateStatus.active;
      await StateStore.save(cmd.tempFilePath, _state!);
      if (_state!.downloadedBytes > 0 && cmd.supportsResume) {
        await _verifyServerIdentity(dio);
      }
      final multiThread = _state!.totalSize > 0 &&
          cmd.supportsResume &&
          cmd.threadCount > 1 &&
          _state!.totalSize >= ChunkScheduler.minSizeForMultithread;
      if (multiThread) {
        try {
          await _runMultiThreaded(dio);
        } on _RangeUnsupportedException {
          debugPrint('[DMX-Job] Range unsupported → single-stream fallback');
          _resetToSingleStream();
          await _runSingleStream(dio);
        }
      } else {
        await _runSingleStream(dio);
      }
      await _finalize(dio);
      _send('done');
    } finally {
      dio.close(force: true);
    }
  }

  Future<void> _verifyServerIdentity(Dio dio) async {
    try {
      final response = await dio.get<ResponseBody>(
        cmd.punyUrl,
        cancelToken: _cancelToken,
        options: Options(
          responseType: ResponseType.stream,
          followRedirects: true,
          headers: {'Range': 'bytes=0-0'},
          validateStatus: (_) => true,
        ),
      );
      if (response.statusCode == 206 || response.statusCode == 200) {
        final contentRange = response.headers.value('content-range');
        int? serverTotal;
        if (contentRange != null) {
          serverTotal = int.tryParse(
              RegExp(r'/(\d+)').firstMatch(contentRange)?.group(1) ?? '');
        }
        serverTotal ??= int.tryParse(
            response.headers.value(Headers.contentLengthHeader) ?? '');
        final newEtag = response.headers.value('etag');
        final newLm = response.headers.value('last-modified');
        await response.data?.stream.listen((_) {}).cancel();
        if (serverTotal != null && serverTotal > 0 && _state!.totalSize > 0) {
          final tolerance =
              (_state!.totalSize * 0.001).clamp(2048.0, 10 * 1024 * 1024);
          if ((serverTotal - _state!.totalSize).abs() > tolerance) {
            for (var i = 0; i < _state!.chunks.length; i++) {
              _state!.chunks[i] = ChunkState(
                  start: _state!.chunks[i].start, end: _state!.chunks[i].end);
            }
            try {
              final f = File(cmd.tempFilePath);
              if (await f.exists()) await f.delete();
            } catch (_) {}
            await StateStore.save(cmd.tempFilePath, _state!);
            throw _FileChangedOnServerException();
          }
        }
        final oldIdentity = _firstNonEmpty(_state!.etag, _state!.lastModified);
        final newIdentity = _firstNonEmpty(newEtag, newLm);
        if (oldIdentity != null &&
            newIdentity != null &&
            oldIdentity != newIdentity) {
          debugPrint('[DMX-Job] resource identity changed — restarting');
          for (final c in _state!.chunks) {
            c.downloaded = 0;
          }
          try {
            final f = File(cmd.tempFilePath);
            if (await f.exists()) await f.delete();
          } catch (_) {}
          _state!.etag = newEtag;
          _state!.lastModified = newLm;
          _state!.migrationNote =
              '${_state!.migrationNote ?? ''} identity_restart'.trim();
          await StateStore.save(cmd.tempFilePath, _state!);
          _emitProgress(0,
              statusMessage: 'Source changed on server — restarting');
        } else {
          _state!.etag ??= newEtag;
          _state!.lastModified ??= newLm;
        }
      }
    } on _FileChangedOnServerException {
      rethrow;
    } on DioException catch (e) {
      final status = e.response?.statusCode;
      final host = Uri.tryParse(cmd.punyUrl)?.host.toLowerCase() ?? '';
      final isYtOrSigned = host.endsWith('.googlevideo.com') ||
          host.contains('youtube.com') ||
          host.contains('youtu.be') ||
          cmd.url.contains('expire=') ||
          cmd.url.contains('signature=');
      if (isYtOrSigned && (status == 401 || status == 403)) {
        _emitProgress(0, statusMessage: 'Updating links (URL expired)…');
        throw UrlExpiredException(
          'YouTube / signed URL expired during identity probe (HTTP $status).',
        );
      }
      debugPrint('[DMX-Job] identity probe failed (continuing): $e');
    } catch (e) {
      debugPrint('[DMX-Job] identity probe failed (continuing): $e');
    }
  }

  void _resetToSingleStream() {
    final st = _state!;
    for (final c in st.chunks) {
      c.downloaded = 0;
    }
    st.chunks = ChunkScheduler.singleStream(st.totalSize);
    st.threadCount = 1;
    try {
      final f = File(cmd.tempFilePath);
      if (f.existsSync()) f.deleteSync();
    } catch (_) {}
  }

  Future<void> _runMultiThreaded(Dio dio) async {
    final st = _state!;
    if (st.chunks.isEmpty) {
      st.chunks = ChunkScheduler.plan(
          totalSize: st.totalSize, threadCount: cmd.threadCount);
    }
    PositionalFileWriter writer;
    final hasPriorBytes = st.downloadedBytes > 0;
    if (hasPriorBytes && await File(cmd.tempFilePath).exists()) {
      writer = await PositionalFileWriter.openForResume(cmd.tempFilePath,
          threadCount: st.threadCount, totalSize: st.totalSize);
    } else {
      writer = await PositionalFileWriter.open(cmd.tempFilePath,
          totalSize: st.totalSize, threadCount: st.threadCount);
      for (final c in st.chunks) {
        c.downloaded = 0;
      }
    }
    final governor = BandwidthGovernor(_effectiveGlobalLimit());
    governor.registerConsumer();
    if (cmd.speedLimitKbps > 0) {
      governor.setTaskLimit(cmd.taskId, cmd.speedLimitKbps * 125);
    }
    if (hasPriorBytes && SettingsProvider.instance.resumeIntegrityCheck) {
      await _spotCheckResumedBytes(dio, st, writer);
    }
    final failover = MirrorFailover([cmd.punyUrl, ...?cmd.mirrorUrls]);
    final work = ChunkScheduler.pendingWork(st.chunks);
    try {
      await Future.wait(work.map((chunk) => _runChunk(
            dio: dio,
            chunk: chunk,
            writer: writer,
            governor: governor,
            failover: failover,
          )));
      await writer.flushAll();
      final sum = st.downloadedBytes;
      if (st.totalSize > 0 && sum < st.totalSize) {
        throw DownloadIntegrityException(
            'Chunk sum $sum < expected ${st.totalSize}');
      }
      final diskLen = await writer.length();
      if (st.totalSize > 0 && diskLen < st.totalSize) {
        throw DownloadIntegrityException(
            'On-disk size $diskLen < expected ${st.totalSize}');
      }
    } catch (e) {
      if (e is DioException && e.type == DioExceptionType.cancel) {
        st.status = DmxStateStatus.paused;
        _emitProgress(0, statusMessage: 'Paused');
      } else if (e is! _RangeUnsupportedException) {
        final anyProven = st.chunks.any((c) => c.downloaded > 0);
        st.status = DmxStateStatus.failed;
        st.migrationNote =
            '${st.migrationNote ?? ''} ${anyProven ? 'resumable' : 'restartRequired'}'
                .trim();
        _emitProgress(0, statusMessage: 'Failed');
      }
      try {
        await writer.flushAll();
        await StateStore.save(cmd.tempFilePath, st);
      } catch (_) {}
      rethrow;
    } finally {
      governor.removeTaskLimit(cmd.taskId);
      governor.unregisterConsumer();
      governor.dispose();
      await writer.close();
    }
  }

  Future<void> _runChunk({
    required Dio dio,
    required ChunkState chunk,
    required PositionalFileWriter writer,
    required BandwidthGovernor governor,
    required MirrorFailover failover,
  }) async {
    var attempts = 0;
    const maxAttempts = 3;
    var activeUrl = failover.activeUrl;
    while (!chunk.isComplete) {
      _throwIfCancelled();
      attempts++;
      try {
        final resumeFrom = chunk.downloaded;
        final absStart = chunk.start + resumeFrom;
        final headers = <String, dynamic>{
          'Range': chunk.end < 0
              ? 'bytes=$absStart-'
              : 'bytes=$absStart-${chunk.end}',
        };
        if (resumeFrom > 0) {
          final ifRange = _firstNonEmpty(_state!.etag, _state!.lastModified);
          if (ifRange != null) headers['If-Range'] = ifRange;
        }
        final response = await dio.get<ResponseBody>(
          activeUrl,
          cancelToken: _cancelToken,
          options: Options(
            responseType: ResponseType.stream,
            followRedirects: true,
            headers: headers,
            validateStatus: (_) => true,
          ),
        );
        if (response.statusCode == 200) {
          await response.data?.stream.listen((_) {}).cancel();
          if (resumeFrom > 0) {
            throw DioException(
              requestOptions: response.requestOptions,
              type: DioExceptionType.badResponse,
              response: response,
              message: 'Server rejected resume: expected HTTP 206. Got 200.',
            );
          }
          throw _RangeUnsupportedException();
        }
        if (response.statusCode == 416) {
          await response.data?.stream.listen((_) {}).cancel();
          if (chunk.downloaded >= chunk.size) {
            chunk.downloaded = chunk.size;
            break;
          }
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'HTTP 416: invalid byte range for chunk.',
          );
        }
        if (response.statusCode != 206) {
          await response.data?.stream.listen((_) {}).cancel();
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'Server returned ${response.statusCode} instead of 206.',
          );
        }
        final contentType =
            response.headers.value('content-type')?.toLowerCase() ?? '';
        if (contentType.contains('text/html') ||
            contentType.contains('application/xhtml')) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'HTML_INSTEAD_OF_MEDIA',
          );
        }
        _validateContentRange(
          response.headers.value('content-range'),
          expectedStart: absStart,
          expectedEnd: chunk.end,
          expectedTotal: _state!.totalSize,
        );
        _state!.etag ??= response.headers.value('etag');
        _state!.lastModified ??= response.headers.value('last-modified');
        final stream = response.data?.stream;
        if (stream == null) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            message: 'Empty response body.',
          );
        }
        var sessionBytes = 0;
        await for (final piece in stream) {
          _throwIfCancelled();
          final sleepMs =
              await governor.acquire(piece.length, taskId: cmd.taskId);
          if (sleepMs > 0) {
            await _cancellableDelay(Duration(milliseconds: sleepMs));
            _throwIfCancelled();
          }
          final pos = chunk.start + resumeFrom + sessionBytes;
          final remainingInChunk = chunk.size >= 0
              ? chunk.size - (resumeFrom + sessionBytes)
              : piece.length;
          if (remainingInChunk <= 0) break;
          final toWrite = remainingInChunk < piece.length
              ? Uint8List.sublistView(piece, 0, remainingInChunk)
              : piece;
          await writer.write(-1, pos, toWrite);
          sessionBytes += toWrite.length;
          chunk.downloaded = resumeFrom + sessionBytes;
          _bytesSinceSave += toWrite.length;
          await _throttledSaveAndReport(writer);
          if (chunk.size >= 0 && (resumeFrom + sessionBytes) >= chunk.size) {
            break;
          }
        }
        failover.reportSuccess();
        attempts = 0;
        if (chunk.isComplete) {
          try {
            await writer.flushAll();
            await StateStore.save(cmd.tempFilePath, _state!);
          } catch (e) {
            debugPrint('[DMX] H-2: chunk-boundary save failed: $e');
          }
        }
      } on DioException catch (e) {
        if (e.type == DioExceptionType.cancel) rethrow;
        if (e.message == 'HTML_INSTEAD_OF_MEDIA') rethrow;
        if (e.message?.startsWith('Server rejected resume') == true) rethrow;
        final status = e.response?.statusCode;
        if (status == 401 || status == 403) {
          final bodyText = (e.response?.data?.toString() ?? '').toLowerCase();
          final host = Uri.tryParse(cmd.punyUrl)?.host.toLowerCase() ?? '';
          final isLikelyExpired = host.endsWith('.googlevideo.com') ||
              host.contains('youtube.com') ||
              host.contains('youtu.be') ||
              bodyText.contains('expired') ||
              bodyText.contains('token') ||
              bodyText.contains('signature') ||
              bodyText.contains('forbidden') ||
              cmd.url.contains('expire=') ||
              cmd.url.contains('signature=');
          if (isLikelyExpired) {
            _emitProgress(0, statusMessage: 'Updating links (URL expired)…');
            throw UrlExpiredException(
              'Download URL expired (HTTP $status). Refresh required.',
              refreshAllMirrors: true,
            );
          }
        }
        if (status != null &&
            status >= 400 &&
            status < 500 &&
            status != 408 &&
            status != 429) {
          rethrow;
        }
        if (attempts >= maxAttempts) {
          final next = failover.advance();
          if (next != null) {
            activeUrl = next;
            attempts = 0;
            debugPrint('[DMX-Job] failing over to mirror: $next');
            _emitProgress(_stopwatch.elapsedMilliseconds,
                statusMessage: 'Retrying (mirror failover)…');
            continue;
          }
          rethrow;
        }
        _emitProgress(_stopwatch.elapsedMilliseconds,
            statusMessage: 'Retrying…');
        await _cancellableDelay(
            Duration(seconds: (attempts * attempts * 2) + Random().nextInt(3)));
      } on PositionalFileWriterException {
        rethrow;
      } catch (e) {
        if (attempts >= maxAttempts) rethrow;
        await _cancellableDelay(Duration(seconds: attempts * 2));
      }
    }
  }

  Future<void> _spotCheckResumedBytes(
      Dio dio, TransferState st, PositionalFileWriter writer) async {
    const sampleSize = 64 * 1024;
    for (final chunk in st.chunks) {
      if (chunk.downloaded <= 0 || chunk.isComplete) continue;
      _throwIfCancelled();
      final start = chunk.start;
      final len = min(sampleSize, chunk.downloaded);
      try {
        final diskBytes = await writer.readRange(start, len);
        final response = await dio.get<ResponseBody>(
          cmd.punyUrl,
          cancelToken: _cancelToken,
          options: Options(
            responseType: ResponseType.stream,
            headers: {'Range': 'bytes=$start-${start + len - 1}'},
            validateStatus: (_) => true,
          ),
        );
        if (response.statusCode != 206 || response.data == null) {
          chunk.downloaded = 0;
          continue;
        }
        final builder = BytesBuilder(copy: false);
        await for (final b in response.data!.stream) {
          builder.add(b);
        }
        final netBytes = builder.takeBytes();
        if (netBytes.length != diskBytes.length ||
            !listEquals(netBytes, diskBytes)) {
          chunk.downloaded = 0;
          debugPrint('[DMX-Job] spot-check mismatch → chunk reset');
        }
      } catch (_) {}
    }
  }

  Future<void> _runSingleStream(Dio dio) async {
    final st = _state!;
    if (st.chunks.isEmpty) {
      st.chunks = ChunkScheduler.singleStream(st.totalSize);
    }
    final chunk = st.chunks.first;
    final tempFile = File(cmd.tempFilePath);
    await tempFile.parent.create(recursive: true);
    final stateFile = File(StateStore.pathFor(cmd.tempFilePath));
    final hasUsableState = await stateFile.exists() &&
        st.downloadedBytes > 0 &&
        st.chunks.isNotEmpty;
    if (await tempFile.exists()) {
      final len = await tempFile.length();
      if (st.totalSize > 0 && len >= st.totalSize) {
        if (hasUsableState && st.isComplete) {
          chunk.downloaded = st.totalSize;
          _emitProgress(0, statusMessage: 'Completed');
          return;
        }
        debugPrint(
            '[DMX-Job] FIX-1: temp file full but state unusable — restarting single-stream');
        chunk.downloaded = 0;
        await tempFile.delete();
        try {
          await StateStore.remove(cmd.tempFilePath);
        } catch (_) {}
        st.chunks = ChunkScheduler.singleStream(st.totalSize);
      } else if (cmd.supportsResume) {
        chunk.downloaded = st.totalSize > 0 ? len.clamp(0, st.totalSize) : len;
      } else {
        chunk.downloaded = 0;
        await tempFile.delete();
      }
    }
    final governor = BandwidthGovernor(_effectiveGlobalLimit());
    governor.registerConsumer();
    if (cmd.speedLimitKbps > 0) {
      governor.setTaskLimit(cmd.taskId, cmd.speedLimitKbps * 125);
    }
    if (chunk.downloaded > 0 &&
        cmd.supportsResume &&
        SettingsProvider.instance.resumeIntegrityCheck &&
        await tempFile.exists()) {
      try {
        const sampleSize = 64 * 1024;
        final len = min(sampleSize, chunk.downloaded);
        final raf = await tempFile.open(mode: FileMode.read);
        try {
          final diskBytes = await raf.read(len);
          final response = await dio.get<ResponseBody>(
            cmd.punyUrl,
            cancelToken: _cancelToken,
            options: Options(
              responseType: ResponseType.stream,
              headers: {'Range': 'bytes=0-${len - 1}'},
              validateStatus: (_) => true,
            ),
          );
          if (response.statusCode == 206 && response.data != null) {
            final builder = BytesBuilder(copy: false);
            await for (final b in response.data!.stream) {
              builder.add(b);
            }
            final netBytes = builder.takeBytes();
            if (netBytes.length != diskBytes.length ||
                !listEquals(netBytes, diskBytes)) {
              debugPrint(
                  '[DMX-Job] FIX-2: single-stream spot-check mismatch — restarting');
              chunk.downloaded = 0;
              await tempFile.delete();
              try {
                await StateStore.remove(cmd.tempFilePath);
              } catch (_) {}
              st.chunks = ChunkScheduler.singleStream(st.totalSize);
            }
          } else {
            await response.data?.stream.listen((_) {}).cancel();
          }
        } finally {
          await raf.close();
        }
      } catch (e) {
        debugPrint('[DMX-Job] FIX-2: spot-check probe failed (continuing): $e');
      }
    }
    var attempts = 0;
    const maxAttempts = 3;
    final failover = MirrorFailover([cmd.punyUrl, ...?cmd.mirrorUrls]);
    var activeUrl = failover.activeUrl;
    while (!st.isComplete || st.totalSize <= 0) {
      _throwIfCancelled();
      attempts++;
      IOSink? sink;
      try {
        final resumeFrom = chunk.downloaded;
        final headers = <String, dynamic>{};
        if (resumeFrom > 0 && cmd.supportsResume) {
          headers['Range'] = 'bytes=$resumeFrom-';
          final ifRange = _firstNonEmpty(st.etag, st.lastModified);
          if (ifRange != null) headers['If-Range'] = ifRange;
        }
        final response = await dio.get<ResponseBody>(
          activeUrl,
          cancelToken: _cancelToken,
          options: Options(
            responseType: ResponseType.stream,
            followRedirects: true,
            headers: headers,
            validateStatus: (_) => true,
          ),
        );
        if (response.statusCode == 416) {
          await response.data?.stream.listen((_) {}).cancel();
          if (st.totalSize > 0 && chunk.downloaded >= st.totalSize) break;
          chunk.downloaded = 0;
          if (await tempFile.exists()) await tempFile.delete();
          continue;
        }
        if (response.statusCode == 200 && resumeFrom > 0) {
          await response.data?.stream.listen((_) {}).cancel();
          for (final p in [
            '${cmd.tempFilePath}.dmxstate',
            '${cmd.tempFilePath}.dmxstate.tmp',
          ]) {
            try {
              final f = File(p);
              if (await f.exists()) await f.delete();
            } catch (_) {}
          }
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'Server rejected resume: expected HTTP 206. Got 200.',
          );
        }
        if (response.statusCode != 200 && response.statusCode != 206) {
          await response.data?.stream.listen((_) {}).cancel();
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'Server returned status code ${response.statusCode}',
          );
        }
        final contentType =
            response.headers.value('content-type')?.toLowerCase() ?? '';
        if (contentType.contains('text/html') ||
            contentType.contains('application/xhtml')) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            response: response,
            message: 'HTML_INSTEAD_OF_MEDIA',
          );
        }
        final isPartial = response.statusCode == 206;
        if (isPartial) {
          final contentRange = response.headers.value('content-range');
          if (contentRange != null) {
            _validateContentRange(
              contentRange,
              expectedStart: chunk.downloaded,
              expectedEnd: st.totalSize > 0 ? st.totalSize - 1 : -1,
              expectedTotal: st.totalSize,
              allowUnknown: chunk.downloaded == 0,
            );
          }
        }
        st.etag ??= response.headers.value('etag');
        st.lastModified ??= response.headers.value('last-modified');
        final contentLength = int.tryParse(
                response.headers.value(Headers.contentLengthHeader) ?? '') ??
            0;
        if (contentLength > 0) {
          final actual = (isPartial ? chunk.downloaded : 0) + contentLength;
          if (st.totalSize <= 0 || actual != st.totalSize) {
            st.totalSize = actual;
            chunk.end = actual - 1;
          }
        }
        sink = tempFile.openWrite(
          mode: chunk.downloaded > 0 ? FileMode.append : FileMode.write,
        );
        final stream = response.data?.stream;
        if (stream == null) {
          throw DioException(
            requestOptions: response.requestOptions,
            type: DioExceptionType.badResponse,
            message: 'Empty response body.',
          );
        }
        try {
          await for (final piece in stream) {
            _throwIfCancelled();
            final sleepMs =
                await governor.acquire(piece.length, taskId: cmd.taskId);
            if (sleepMs > 0) {
              await _cancellableDelay(Duration(milliseconds: sleepMs));
              _throwIfCancelled();
            }
            sink.add(piece);
            chunk.downloaded += piece.length;
            _bytesSinceSave += piece.length;
            await _throttledSaveAndReport(
              null,
              preSaveFlush: () async {
                await sink?.flush();
              },
            );
          }
        } on DioException catch (e) {
          if (e.type == DioExceptionType.cancel) {
            rethrow;
          }
          rethrow;
        }
        await sink.flush();
        await sink.close();
        sink = null;
        failover.reportSuccess();
        attempts = 0;
        if (st.totalSize <= 0) {
          st.totalSize = chunk.downloaded;
          chunk.end = chunk.downloaded - 1;
        }
        break;
      } on DioException catch (e) {
        if (e.type == DioExceptionType.cancel) {
          _state!.status = DmxStateStatus.paused;
          _emitProgress(0, statusMessage: 'Paused');
          rethrow;
        }
        if (e.message == 'HTML_INSTEAD_OF_MEDIA') {
          _state!.status = DmxStateStatus.failed;
          _emitProgress(0, statusMessage: 'Failed');
          rethrow;
        }
        if (e.message?.startsWith('Server rejected resume') == true) {
          _state!.status = DmxStateStatus.failed;
          _emitProgress(0, statusMessage: 'Failed');
          rethrow;
        }
        final status = e.response?.statusCode;
        if (status != null &&
            status >= 400 &&
            status < 500 &&
            status != 408 &&
            status != 429) {
          _state!.status = DmxStateStatus.failed;
          _emitProgress(0, statusMessage: 'Failed');
          rethrow;
        }
        if (attempts >= maxAttempts) {
          _state!.status = DmxStateStatus.failed;
          final next = failover.advance();
          if (next != null) {
            activeUrl = next;
            attempts = 0;
            _state!.status = DmxStateStatus.active;
            _emitProgress(_stopwatch.elapsedMilliseconds,
                statusMessage: 'Retrying (mirror failover)…');
            continue;
          }
          _emitProgress(0, statusMessage: 'Failed');
          rethrow;
        }
        _emitProgress(_stopwatch.elapsedMilliseconds,
            statusMessage: 'Retrying…');
        await _cancellableDelay(
            Duration(seconds: (attempts * attempts * 2) + Random().nextInt(3)));
      } finally {
        try {
          await sink?.flush();
          await sink?.close();
        } catch (_) {}
        try {
          await StateStore.save(cmd.tempFilePath, _state!);
        } catch (_) {}
      }
    }
    final actualLen = await tempFile.length();
    if (st.totalSize > 0 && actualLen != st.totalSize) {
      if (actualLen > st.totalSize) {
        final raf = await tempFile.open(mode: FileMode.writeOnly);
        await raf.truncate(st.totalSize);
        await raf.close();
      } else {
        st.status = DmxStateStatus.failed;
        await StateStore.save(cmd.tempFilePath, st);
        _emitProgress(0, statusMessage: 'Failed');
        throw DownloadIntegrityException(
            'expected ${st.totalSize} bytes, got $actualLen');
      }
    }
    governor.removeTaskLimit(cmd.taskId);
    governor.unregisterConsumer();
    governor.dispose();
  }

  Future<void> _finalize(Dio dio) async {
    final st = _state!;
    if (cmd.tempFilePath != cmd.localFilePath) {
      final tempExists = await File(cmd.tempFilePath).exists();
      if (!tempExists) {
        st.status = DmxStateStatus.failed;
        await StateStore.save(cmd.tempFilePath, st);
        _emitProgress(0, statusMessage: 'Failed');
        throw DownloadIntegrityException(
            'Temporary download file missing: ${cmd.tempFilePath}');
      }
      final finalFile = File(cmd.localFilePath);
      await finalFile.parent.create(recursive: true);
      if (await finalFile.exists()) await finalFile.delete();
      try {
        await File(cmd.tempFilePath).rename(cmd.localFilePath);
      } catch (e) {
        await File(cmd.tempFilePath).copy(cmd.localFilePath);
        final copiedLen = await File(cmd.localFilePath).length();
        final origLen = await File(cmd.tempFilePath).length();
        if (copiedLen == origLen) {
          await File(cmd.tempFilePath).delete();
        } else {
          throw const DownloadIntegrityException(
              'File copy verification failed on rename fallback.');
        }
      }
    } else {
      final localExists = await File(cmd.localFilePath).exists();
      if (!localExists) {
        st.status = DmxStateStatus.failed;
        await StateStore.save(cmd.tempFilePath, st);
        _emitProgress(0, statusMessage: 'Failed');
        throw DownloadIntegrityException(
            'Download output file missing: ${cmd.localFilePath}');
      }
    }
    st.status = DmxStateStatus.complete;
    await StateStore.save(cmd.tempFilePath, st);
    _emitProgress(0, statusMessage: 'Completed');
    await StateStore.remove(cmd.tempFilePath);
  }

  int _effectiveGlobalLimit() {
    if (_workerGlobalLimitBps > 0) {
      return (_workerGlobalLimitBps / _workerGlobalActive).floor();
    }
    return cmd.initialSpeedLimit > 0
        ? (cmd.initialSpeedLimit / max(1, cmd.initialActiveCount)).floor()
        : 0;
  }

  void _throwIfCancelled() {
    if (_cancelRequested || _cancelToken.isCancelled) {
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.cancel,
        message: 'Download cancelled.',
      );
    }
  }

  Future<void> _cancellableDelay(Duration duration) async {
    if (_cancelRequested) return;
    final completer = Completer<void>();
    final timer = Timer(duration, () {
      if (!completer.isCompleted) completer.complete();
    });
    final sub = _cancelToken.whenCancel.then((_) {
      timer.cancel();
      if (!completer.isCompleted) completer.complete();
    });
    await completer.future;
    await sub;
  }

  Future<void> _throttledSaveAndReport(
    PositionalFileWriter? writer, {
    Future<void> Function()? preSaveFlush,
  }) async {
    final nowMs = _stopwatch.elapsedMilliseconds;
    final st = _state!;
    final dueSave = nowMs - _lastStateSaveMs >= _stateSaveIntervalMs ||
        _bytesSinceSave >= _stateSaveByteThreshold;
    final dueReport = nowMs - _lastReportMs >= 500;
    if (dueSave) {
      _lastStateSaveMs = nowMs;
      _bytesSinceSave = 0;
      try {
        if (preSaveFlush != null) await preSaveFlush();
        if (writer != null) await writer.flush();
        await StateStore.save(cmd.tempFilePath, st);
      } catch (e) {
        debugPrint('[DMX-Job] state save failed: $e');
      }
    }
    if (dueReport) {
      _lastReportMs = nowMs;
      _emitProgress(nowMs);
    }
  }

  void _emitProgress(int nowMs, {String? statusMessage}) {
    final st = _state!;
    final downloaded = st.downloadedBytes;
    final total = st.totalSize;
    _speedSamples.add(_SpeedSample(_stopwatch.elapsedMilliseconds, downloaded));
    while (_speedSamples.isNotEmpty &&
        _stopwatch.elapsedMilliseconds - _speedSamples.first.timestampMs >
            3000) {
      _speedSamples.removeFirst();
    }
    var speed = 0.0;
    if (_speedSamples.length > 1) {
      final first = _speedSamples.first;
      final elapsed =
          (_stopwatch.elapsedMilliseconds - first.timestampMs) / 1000;
      if (elapsed > 0) speed = (downloaded - first.bytes) / elapsed;
    }
    int? eta;
    final remaining = total - downloaded;
    if (speed.isFinite && speed > 0 && remaining > 0) {
      final raw = (remaining / speed).round().clamp(0, 86400 * 365);
      eta = _lastEta == null ? raw : ((_lastEta! * 0.7) + (raw * 0.3)).round();
      _lastEta = eta;
    } else {
      _lastEta = null;
    }
    final chunkDetails = st.chunks.isNotEmpty
        ? st.chunks.asMap().entries.map((e) {
            final c = e.value;
            final rawRatio = c.ratio;
            final safeRatio = rawRatio < 0.0 ? 0.0 : rawRatio.clamp(0.0, 1.0);
            return <String, dynamic>{
              'index': e.key,
              'start': c.start,
              'end': c.end,
              'downloaded': c.downloaded,
              'size': c.size,
              'ratio': safeRatio,
              'isComplete': c.isComplete,
              'isIndeterminate': c.size < 0,
            };
          }).toList()
        : null;
    final totalChunks = st.chunks.isNotEmpty ? st.chunks.length : null;
    final completedChunks = st.chunks.isNotEmpty
        ? st.chunks.where((c) => c.isComplete).length
        : null;
    final cycleState = _deriveCycleState(statusMessage, st.status);
    final ytLiveCounterpartBytes = cmd.ytCounterpartDownloadedBytes;
    _send('progress', {
      'downloadedBytes': downloaded,
      'fileSize': total,
      'speed': speed,
      'eta': eta,
      'chunks': st.chunks.isNotEmpty ? st.chunkRatios : null,
      'chunkDetails': chunkDetails,
      'fileName': cmd.resolvedFileName,
      'supportsResume': cmd.supportsResume,
      if (cmd.ytStreamKind != null) 'ytStreamKind': cmd.ytStreamKind!.name,
      if (cmd.ytCounterpartSize != null)
        'ytCounterpartSize': cmd.ytCounterpartSize,
      if (ytLiveCounterpartBytes != null)
        'ytCounterpartDownloadedBytes': ytLiveCounterpartBytes,
      'ytDownloadedBytes': downloaded,
      'statusMessage': statusMessage,
      'cycleState': cycleState,
      if (totalChunks != null) 'totalChunks': totalChunks,
      if (completedChunks != null) 'completedChunks': completedChunks,
    });
  }

  static String _deriveCycleState(
      String? statusMessage, DmxStateStatus status) {
    switch (status) {
      case DmxStateStatus.complete:
        return 'completed';
      case DmxStateStatus.failed:
        return 'failed';
      case DmxStateStatus.paused:
        return 'paused';
      case DmxStateStatus.active:
        final msg = statusMessage?.toLowerCase() ?? '';
        if (msg.contains('updating links')) return 'updating_links';
        if (msg.contains('retrying')) return 'retrying';
        if (msg.contains('restarting') || msg.contains('source changed')) {
          return 'retrying';
        }
        if (msg.contains('checking') || msg.contains('verifying')) {
          return 'checking';
        }
        if (msg.contains('seeding')) return 'seeding';
        if (msg.contains('completed')) return 'completed';
        if (msg.contains('starting') ||
            msg.contains('allocating') ||
            msg.contains('preparing')) {
          return 'starting';
        }
        if (msg.contains('resuming')) return 'resuming';
        if (msg.contains('fetching metadata')) return 'fetching_metadata';
        return 'downloading';
    }
  }

  void _validateContentRange(
    String? value, {
    required int expectedStart,
    required int expectedEnd,
    required int expectedTotal,
    bool allowUnknown = false,
  }) {
    if (value == null || value.trim().isEmpty) {
      if (allowUnknown) return;
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.badResponse,
        message: 'Missing Content-Range header during resume.',
      );
    }
    final match =
        RegExp(r'^bytes\s+(\d+)-(\d+)/(\d+|\*)$', caseSensitive: false)
            .firstMatch(value.trim());
    if (match == null) {
      if (allowUnknown) return;
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.badResponse,
        message: 'Malformed Content-Range during resume: $value.',
      );
    }
    final start = int.tryParse(match.group(1) ?? '');
    final end = int.tryParse(match.group(2) ?? '');
    final totalText = match.group(3);
    final total =
        totalText == null || totalText == '*' ? null : int.tryParse(totalText);
    if (start != expectedStart ||
        (expectedEnd >= 0 && end != expectedEnd) ||
        (expectedTotal > 0 && total != null && total != expectedTotal)) {
      throw DioException(
        requestOptions: RequestOptions(path: cmd.punyUrl),
        type: DioExceptionType.badResponse,
        message: 'Invalid Content-Range response: $value. '
            'Expected start $expectedStart got $start.',
      );
    }
  }
}

class _SpeedSample {
  final int timestampMs;
  final int bytes;
  _SpeedSample(this.timestampMs, this.bytes);
}
