// REFACTOR C: isolate pool for HTTP downloads.
//
// Hardened version:
// - worker respawn with backoff
// - safer shutdown
// - better error classification
// - robust job routing
part of 'download_engine.dart';

final _log = Logger('DownloadIsolatePool');

/// A download job description sent to a worker isolate.
class DownloadCommand {
  final String url;
  final String punyUrl;
  final String tempFilePath;
  final String localFilePath;
  final int knownFileSize;
  final bool supportsResume;
  final int threadCount;
  final String? customUserAgent;
  final String? referer;
  final bool enableProxy;
  final String? proxyAddress;
  final String? proxyHost;
  final int? proxyPort;
  final String? proxyUsername;
  final String? proxyPassword;
  final bool bypassSSL;
  final String? cookies;
  final String? oauthToken;
  final bool isNameAutoGenerated;
  final int speedLimit;
  final int activeCount;
  final String taskId;
  final List<String>? mirrorUrls;

  DownloadCommand({
    required this.url,
    required this.punyUrl,
    required this.tempFilePath,
    required this.localFilePath,
    required this.knownFileSize,
    required this.supportsResume,
    required this.threadCount,
    this.customUserAgent,
    this.referer,
    required this.enableProxy,
    this.proxyAddress,
    this.proxyHost,
    this.proxyPort,
    this.proxyUsername,
    this.proxyPassword,
    required this.bypassSSL,
    this.cookies,
    this.oauthToken,
    required this.isNameAutoGenerated,
    required this.speedLimit,
    required this.activeCount,
    required this.taskId,
    this.mirrorUrls,
  });
}

/// A message sent from a worker isolate back to the main isolate.
class IsolateMessage {
  final int jobId;
  final String type;
  final Map<String, Object?> data;

  IsolateMessage(this.jobId, this.type, [Map<String, Object?>? data])
      : data = data ?? const {};
}

/// Pool of long-lived worker isolates.
class DownloadIsolatePool {
  final int size;
  final List<_Worker> _workers = [];

  /// Max concurrent jobs admitted to a single worker before jobs queue.
  static const int _maxJobsPerWorker = 2;

  /// Priority-aware job queue. Higher priority = processed first.
  final List<_PendingJob> _pendingQueue = [];

  Timer? _healthCheckTimer;
  bool _draining = false;

  DownloadIsolatePool({this.size = 4});

  Future<void> init() async {
    for (int i = 0; i < size; i++) {
      final worker = _Worker(i);
      worker.onJobCompleted = _onJobCompleted;
      try {
        await worker.spawn().timeout(
          const Duration(seconds: 30),
          onTimeout: () {
            debugPrint('[DMX Pool] Worker $i spawn timeout - continuing');
          },
        );
        _workers.add(worker);
      } catch (e) {
        debugPrint('[DMX Pool] Worker $i failed to spawn: $e');
        // Continue with remaining workers
      }
    }
  }

  DownloadJob submit(DownloadCommand command, {int priority = 0}) {
    final aliveWorkers = _workers.where((w) => w._isAlive).toList();

    if (aliveWorkers.isEmpty) {
      throw const IsolateSpawnTimeoutException(
        'No available download workers.',
      );
    }

    // Prefer the least-busy worker that still has capacity.
    _Worker? bestWorker;
    var bestLoad = _maxJobsPerWorker;
    for (final w in aliveWorkers) {
      final load = w._jobs.length;
      if (load < bestLoad) {
        bestLoad = load;
        bestWorker = w;
        if (load == 0) break;
      }
    }

    if (bestWorker != null) {
      return bestWorker.submit(command);
    }

    // All workers at capacity — enqueue with priority.
    final pending = _PendingJob(
      command: command,
      priority: priority,
      pool: this,
    );
    _pendingQueue.add(pending);
    _pendingQueue.sort((a, b) => b.priority.compareTo(a.priority));
    return pending.job;
  }

  void _cancelPending(DownloadJob job) {
    final index = _pendingQueue.indexWhere((pending) => pending.job == job);
    if (index == -1) return;

    _pendingQueue.removeAt(index);
    if (!job._controller.isClosed) {
      job._controller.add(
        IsolateMessage(job.jobId, 'error', {
          'errorType': 'cancel',
          'errorMessage': 'Download cancelled before a worker was available.',
        }),
      );
    }
  }

  /// Dequeues the next pending job (highest priority first) and submits it to
  /// the worker that just freed a slot.
  void _onJobCompleted(int workerId) {
    if (_draining || _pendingQueue.isEmpty) return;

    final worker =
        _workers.where((w) => w.id == workerId && w._isAlive).firstOrNull;
    if (worker == null || worker._jobs.length >= _maxJobsPerWorker) return;

    final next = _pendingQueue.removeAt(0);
    worker.submitJob(next.command, next.job);
  }

  /// Starts periodic worker health checks (every 30 seconds).
  void startHealthMonitor() {
    _healthCheckTimer?.cancel();
    _healthCheckTimer = Timer.periodic(const Duration(seconds: 30), (_) {
      if (_draining) return;
      _checkWorkerHealth();
    });
  }

  void _checkWorkerHealth() {
    for (final worker in _workers) {
      if (!worker._isAlive) {
        _log.warning('[Pool] Worker ${worker.id} is dead. Respawning...');
        worker.respawn();
        continue;
      }

      // Check for stuck jobs (> 5 minutes with no progress).
      final now = DateTime.now();
      final stuckJobs = worker._jobs.entries.where((entry) {
        return now.difference(entry.value.lastProgress) >
            const Duration(minutes: 5);
      }).toList();

      for (final stuck in stuckJobs) {
        _log.warning(
          '[Pool] Worker ${worker.id} has stuck job ${stuck.key}. Cancelling.',
        );
        worker.cancelJob(stuck.key);
      }
    }
  }

  /// Graceful shutdown: stop accepting new jobs, wait for active jobs to
  /// finish (bounded by [timeout]), then force-kill remaining workers.
  Future<void> drain({Duration timeout = const Duration(seconds: 30)}) async {
    _draining = true;
    _healthCheckTimer?.cancel();
    _healthCheckTimer = null;

    // Cancel queued jobs so they are not silently dropped without an error.
    for (final pending in _pendingQueue) {
      pending.job.dispose();
    }
    _pendingQueue.clear();

    final stopwatch = Stopwatch()..start();
    while (stopwatch.elapsed < timeout) {
      final activeCount = _workers.fold<int>(
        0,
        (sum, w) => sum + w._jobs.length,
      );
      if (activeCount == 0) break;
      await Future.delayed(const Duration(milliseconds: 500));
    }

    await shutdown();
    _draining = false;
  }

  /// Memory pressure callback — reduce pool size to a safe minimum (2 idle
  /// workers remain).
  void onMemoryPressure() {
    _log.warning('[Pool] Memory pressure detected. Reducing pool size.');
    final toKill = _workers
        .where((w) => w._jobs.isEmpty && !w._shuttingDown)
        .skip(2)
        .toList();
    for (final worker in toKill) {
      worker.kill();
      _workers.remove(worker);
    }
  }

  void updateSpeedLimit(int bytesPerSecond, int activeCount) {
    for (final w in _workers) {
      w.broadcastSpeedLimit(bytesPerSecond, activeCount);
    }
  }

  Future<void> shutdown() async {
    _draining = true;
    _healthCheckTimer?.cancel();
    _healthCheckTimer = null;
    _pendingQueue.clear();

    for (final w in _workers) {
      await w.shutdown();
    }
    _workers.clear();
    _draining = false;
  }
}

/// One long-lived worker isolate plus main-side routing of its messages.
class _Worker {
  final int id;

  Isolate? _isolate;
  SendPort? _commandPort;
  ReceivePort? _receivePort;
  ReceivePort? _errorPort;

  final Map<int, DownloadJob> _jobs = {};
  int _nextJobId = 0;

  bool _isAlive = false;
  bool _shuttingDown = false;

  /// Invoked by the pool when a job finishes so pending jobs can be dequeued.
  void Function(int workerId)? onJobCompleted;

  // FIX(N1): circuit breaker for worker respawns
  static const int _maxConsecutiveRespawnFailures = 5;
  int _consecutiveSpawnFailures = 0;

  int _respawnAttempts = 0;
  Timer? _respawnTimer;

  _Worker(this.id);

  Future<void> spawn({bool isRespawn = false}) async {
    if (_shuttingDown) return;

    if (isRespawn) {
      _respawnAttempts++;
      _consecutiveSpawnFailures++;

      // FIX(N2): Use >= so the breaker trips after exactly
      // _maxConsecutiveRespawnFailures failures (previously `>` allowed one
      // extra failure before death).
      if (_consecutiveSpawnFailures >= _maxConsecutiveRespawnFailures) {
        _isAlive = false;
        debugPrint(
          '[DMX Pool] Worker $id circuit breaker tripped after '
          '$_consecutiveSpawnFailures consecutive spawn failures. '
          'Leaving worker dead.',
        );
        return;
      }

      if (_respawnAttempts >= 5) {
        _isAlive = false;
        debugPrint(
          '[DMX Pool] Worker $id exceeded max respawn attempts. '
          'Leaving worker dead.',
        );
        return;
      }

      final attempt = _respawnAttempts.clamp(1, 5);
      final delayMs = 500 * (1 << attempt);

      debugPrint(
        '[DMX Pool] Respawning worker $id in ${delayMs}ms '
        '(attempt $_respawnAttempts/$_maxConsecutiveRespawnFailures)',
      );

      await Future.delayed(Duration(milliseconds: delayMs));
      if (_shuttingDown) return;
    }

    _receivePort?.close();
    _errorPort?.close();

    final receivePort = ReceivePort();
    final errorPort = ReceivePort();

    _receivePort = receivePort;
    _errorPort = errorPort;

    final handshake = Completer<SendPort>();

    receivePort.listen((message) {
      if (message is SendPort) {
        if (!handshake.isCompleted) handshake.complete(message);
      } else if (message is IsolateMessage) {
        // FIX(N2): a successfully routed job message proves the worker is
        // healthy — clear the failure counter so a single transient failure
        // (or a crash that was followed by a working respawn) does not
        // accumulate towards a permanent kill.
        if (_consecutiveSpawnFailures > 0) _consecutiveSpawnFailures = 0;
        final job = _jobs[message.jobId];
        if (job != null) {
          job.lastProgress = DateTime.now();
          job._controller.add(message);
        }
      }
    });

    errorPort.listen((message) {
      if (_shuttingDown) return;

      _isAlive = false;

      final errorMessage = message is List && message.isNotEmpty
          ? message[0].toString()
          : 'Worker isolate exited unexpectedly without payload.';

      // FIX(H1): Mark jobs with 'worker_crash' type instead of 'uncaught'
      // so the orchestrator can distinguish a job-specific failure from a
      // worker crash and potentially re-queue unrelated jobs.
      for (final job in List<DownloadJob>.from(_jobs.values)) {
        job._controller.add(
          IsolateMessage(job.jobId, 'error', {
            'errorType': 'worker_crash',
            'errorMessage': 'Worker isolate crashed: $errorMessage',
          }),
        );

        if (!job._controller.isClosed) {
          job._controller.close();
        }
      }

      _jobs.clear();

      _scheduleRespawn();
    });

    try {
      _isolate = await Isolate.spawn(
        _downloadWorkerMain,
        receivePort.sendPort,
        debugName: 'DownloadPoolWorker_$id',
        onError: errorPort.sendPort,
      );

      _commandPort = await handshake.future.timeout(
        const Duration(seconds: 30),
      );

      _isAlive = true;

      // FIX(N1): Healthy spawn — reset circuit breaker counter
      _consecutiveSpawnFailures = 0;
      if (isRespawn) {
        _respawnAttempts = 0;
      }
    } on TimeoutException {
      _isolate?.kill(priority: Isolate.immediate);
      _isolate = null;

      receivePort.close();
      errorPort.close();

      if (isRespawn) {
        _scheduleRespawn();
        return;
      }

      throw const IsolateSpawnTimeoutException();
    } catch (e) {
      debugPrint('[DMX Pool] Failed to spawn worker $id: $e');

      _isolate?.kill(priority: Isolate.immediate);
      _isolate = null;

      receivePort.close();
      errorPort.close();

      if (isRespawn) {
        _scheduleRespawn();
        return;
      }

      rethrow;
    }
  }

  void _scheduleRespawn() {
    if (_shuttingDown) return;

    _respawnTimer?.cancel();

    final attempt = _respawnAttempts.clamp(0, 5);
    final delayMs = 500 * (1 << attempt);

    _respawnTimer = Timer(Duration(milliseconds: delayMs), () {
      unawaited(
        spawn(isRespawn: true).catchError((Object e) {
          debugPrint('[DMX Pool] Worker $id respawn failed: $e');
        }),
      );
    });
  }

  DownloadJob submit(DownloadCommand command) {
    final jobId = _nextJobId++;
    final job = DownloadJob._(jobId, this);

    _jobs[jobId] = job;
    _send({'type': 'start', 'jobId': jobId, 'command': command});

    return job;
  }

  /// Submits a job whose [DownloadJob] handle was created earlier (a queued
  /// job). The handle is attached to this worker and sent to the isolate.
  DownloadJob submitJob(DownloadCommand command, DownloadJob job) {
    final jobId = _nextJobId++;
    job._jobId = jobId;
    job._worker = this;

    _jobs[jobId] = job;
    _send({'type': 'start', 'jobId': jobId, 'command': command});

    return job;
  }

  /// Backstop respawn entry point used by the health monitor when a worker is
  /// found dead outside the normal error-port flow.
  void respawn() {
    if (_shuttingDown) return;
    if (_isAlive) return;
    _scheduleRespawn();
  }

  /// Hard-kills the worker immediately (used when shrinking the pool).
  void kill() {
    _shuttingDown = true;
    _respawnTimer?.cancel();
    _respawnTimer = null;

    for (final job in List<DownloadJob>.from(_jobs.values)) {
      job.dispose();
    }
    _jobs.clear();

    _receivePort?.close();
    _receivePort = null;
    _errorPort?.close();
    _errorPort = null;

    _isolate?.kill(priority: Isolate.immediate);
    _isolate = null;
    _commandPort = null;
    _isAlive = false;
  }

  /// Cancels a job that has made no progress for too long.
  void cancelJob(int jobId) {
    final job = _jobs[jobId];
    if (job == null) return;

    _send({'type': 'cancel', 'jobId': jobId});
    if (!job._controller.isClosed) {
      job._controller.add(
        IsolateMessage(jobId, 'error', {
          'errorType': 'cancel',
          'errorMessage':
              'Job cancelled: no progress for over 5 minutes (stuck).',
        }),
      );
    }
  }

  void broadcastSpeedLimit(int bytesPerSecond, int activeCount) {
    if (_jobs.isEmpty) return;

    _send({
      'type': 'update_speed_limit',
      'value': bytesPerSecond,
      'activeCount': activeCount,
    });
  }

  void _send(Map<String, Object?> message) {
    if (_shuttingDown) return;

    final port = _commandPort;
    if (port == null) return;

    try {
      port.send(message);
    } catch (e) {
      debugPrint('[DMX Pool] Failed to send command to worker $id: $e');
      _isAlive = false;
      _scheduleRespawn();
    }
  }

  Future<void> shutdown() async {
    _respawnTimer?.cancel();
    _respawnTimer = null;

    // Send shutdown before marking the worker unavailable; _send intentionally
    // ignores commands after _shuttingDown is set.
    _send({'type': 'shutdown'});
    _shuttingDown = true;

    // FIX(C4): Give the isolate a brief window to process the shutdown
    // message, cancel HTTP streams, and close file handles gracefully
    // before force-killing it.
    await Future.delayed(const Duration(milliseconds: 500));

    for (final job in List<DownloadJob>.from(_jobs.values)) {
      job.dispose();
    }

    _jobs.clear();

    _receivePort?.close();
    _receivePort = null;

    _errorPort?.close();
    _errorPort = null;

    _isolate?.kill(priority: Isolate.immediate);
    _isolate = null;

    _commandPort = null;
    _isAlive = false;
  }
}

/// Main-side handle for one submitted download job.
class DownloadJob {
  int _jobId;
  _Worker? _worker;
  final DownloadIsolatePool? _pool;

  final StreamController<IsolateMessage> _controller =
      StreamController<IsolateMessage>();

  /// Last time a progress/status message arrived from the worker. Used by the
  /// health monitor to detect stuck jobs.
  DateTime lastProgress = DateTime.now();

  DownloadJob._(this._jobId, this._worker, [this._pool]);

  int get jobId => _jobId;
  bool get isClosed => _controller.isClosed;

  Stream<IsolateMessage> get messages => _controller.stream;

  void cancel() {
    final worker = _worker;
    if (worker != null) {
      worker._send({'type': 'cancel', 'jobId': _jobId});
    } else {
      _pool?._cancelPending(this);
    }
  }

  void dispose() {
    final worker = _worker;
    worker?._jobs.remove(_jobId);

    if (!_controller.isClosed) {
      _controller.close();
    }

    if (worker != null && worker.onJobCompleted != null) {
      worker.onJobCompleted!(worker.id);
    }
  }
}

/// A job waiting in the pool's priority queue for a worker slot.
class _PendingJob {
  final DownloadCommand command;
  final int priority;
  final DownloadJob job;

  _PendingJob({
    required this.command,
    required this.priority,
    required DownloadIsolatePool pool,
  }) : job = DownloadJob._(0, null, pool);
}

/// Worker-side mutable state for one running job.
class _WorkerJobState {
  final CancelToken cancelToken = CancelToken();

  int speedLimit;
  int activeCount;

  _WorkerJobState({required this.speedLimit, required this.activeCount});
}

/// Worker isolate main loop.
void _downloadWorkerMain(SendPort mainSendPort) {
  final commandPort = ReceivePort();
  final jobs = <int, _WorkerJobState>{};

  final engine = DownloadEngine(enableCleanupTimer: false);

  void safeSend(IsolateMessage message) {
    try {
      mainSendPort.send(message);
    } catch (e) {
      debugPrint('[DMX Worker] safeSend failed: $e');
    }
  }

  commandPort.listen((message) {
    try {
      if (message is! Map) return;

      final type = message['type'];

      if (type == 'start') {
        final jobId = message['jobId'] as int;
        final command = message['command'] as DownloadCommand;

        final state = _WorkerJobState(
          speedLimit: command.speedLimit,
          activeCount: command.activeCount,
        );

        jobs[jobId] = state;

        safeSend(IsolateMessage(jobId, 'ack'));

        _runWorkerJob(jobId, command, state, safeSend, engine).whenComplete(() {
          jobs.remove(jobId);
        });
      } else if (type == 'cancel') {
        final jobId = message['jobId'] as int;
        final state = jobs[jobId];

        if (state != null && !state.cancelToken.isCancelled) {
          state.cancelToken.cancel();
        }
      } else if (type == 'update_speed_limit') {
        final value = message['value'] as int;
        final activeCount = message['activeCount'] as int?;

        for (final state in jobs.values) {
          state.speedLimit = value;
          if (activeCount != null) {
            state.activeCount = activeCount;
          }
        }
      } else if (type == 'shutdown') {
        for (final state in jobs.values) {
          if (!state.cancelToken.isCancelled) {
            state.cancelToken.cancel();
          }
        }

        try {
          engine.close();
        } catch (e) {
          _log.info(
            '[DownloadIsolatePool] engine close on shutdown failed: $e',
          );
        }

        commandPort.close();
      }
    } catch (e) {
      debugPrint('[DMX Worker] Error handling command message: $e');
    }
  });

  mainSendPort.send(commandPort.sendPort);
}

/// Runs a single download on the worker isolate and streams results back.
Future<void> _runWorkerJob(
  int jobId,
  DownloadCommand command,
  _WorkerJobState state,
  void Function(IsolateMessage) safeSend,
  DownloadEngine engine,
) async {
  try {
    void onProgress(DownloadProgress p) {
      safeSend(
        IsolateMessage(jobId, 'progress', {
          'downloadedBytes': p.downloadedBytes,
          'fileSize': p.fileSize,
          'speed': p.speed,
          'eta': p.eta,
          'chunks': p.chunks,
          'fileName': p.fileName,
          'supportsResume': p.supportsResume,
          'statusMessage': p.statusMessage,
        }),
      );
    }

    Future<void> runMirrorAttempt(String mirrorUrl) async {
      await engine._doHttpDownload(
        url: mirrorUrl,
        punyUrl: convertIdnToPunycode(mirrorUrl),
        tempFilePath: command.tempFilePath,
        localFilePath: command.localFilePath,
        knownFileSize: command.knownFileSize,
        supportsResume: command.supportsResume,
        threadCount: command.threadCount,
        customUserAgent: command.customUserAgent,
        referer: command.referer,
        enableProxy: command.enableProxy,
        proxyAddress: command.proxyAddress,
        proxyHost: command.proxyHost,
        proxyPort: command.proxyPort,
        proxyUsername: command.proxyUsername,
        proxyPassword: command.proxyPassword,
        bypassSSL: command.bypassSSL,
        cookies: command.cookies,
        oauthToken: command.oauthToken,
        isNameAutoGenerated: command.isNameAutoGenerated,
        speedLimitBytesPerSecond: () => state.speedLimit,
        activeDownloadCount: () => state.activeCount,
        cancelToken: state.cancelToken,
        onProgress: onProgress,
      );
    }

    final mirrors = <String>[
      command.url,
      if (command.mirrorUrls != null) ...command.mirrorUrls!,
    ];

    if (mirrors.length <= 1) {
      await runMirrorAttempt(command.url);
      safeSend(IsolateMessage(jobId, 'done'));
      return;
    }

    // Automatic in-loop mirror failover: when the primary mirror fails with a
    // retryable error, the download is restarted (resuming from the shared
    // state/journal) against the next-best mirror.
    final failover = MirrorFailover(mirrors, primary: command.url);
    Object? lastError;
    final succeeded = await failover.run((mirrorUrl) async {
      try {
        await runMirrorAttempt(mirrorUrl);
      } catch (e) {
        lastError = e;
        rethrow;
      }
    });

    if (succeeded == null) {
      final err = lastError;
      if (err != null) {
        Error.throwWithStackTrace(err, StackTrace.current);
      }
      throw StateError('All mirrors failed');
    }
    safeSend(IsolateMessage(jobId, 'done'));
  } catch (e) {
    String errType = 'unknown';
    int? errStatus;

    if (e is _FileChangedOnServerException) {
      errType = 'fileChanged';
    } else if (e is DioException) {
      if (e.type == DioExceptionType.cancel) {
        errType = 'cancel';
      } else if (e.type == DioExceptionType.badResponse) {
        errType = 'badResponse';
      } else if (e.type == DioExceptionType.connectionTimeout) {
        errType = 'connectionTimeout';
      } else if (e.type == DioExceptionType.receiveTimeout) {
        errType = 'receiveTimeout';
      } else if (e.type == DioExceptionType.sendTimeout) {
        errType = 'sendTimeout';
      } else if (e.type == DioExceptionType.connectionError) {
        errType = 'connectionError';
      }

      errStatus = e.response?.statusCode;
    } else if (e is TimeoutException) {
      errType = 'receiveTimeout';
    } else if (e is SocketException) {
      errType = 'connectionError';
    } else if (e is FileSystemException) {
      if (_isDiskFullError(e)) {
        errType = 'diskFull';
      }
    } else {
      final typeName = e.runtimeType.toString();
      final stringRep = e.toString();

      if (typeName == 'DownloadIntegrityException' ||
          stringRep.startsWith('DownloadIntegrityException')) {
        errType = 'integrity';
      }
    }

    safeSend(
      IsolateMessage(jobId, 'error', {
        'errorType': errType,
        'errorMessage': e.toString(),
        'errorStatus': errStatus,
      }),
    );
  }
}

/// Checks whether a [FileSystemException] indicates that the disk is full.
///
/// Handles platform-specific error codes:
/// - Android / Linux: ENOSPC (errno 28)
/// - Windows: ERROR_DISK_FULL (errno 112) or "not enough space" in message
bool _isDiskFullError(FileSystemException e) {
  final osError = e.osError;
  if (osError != null) {
    final code = osError.errorCode;
    // 28 = ENOSPC (POSIX), 112 = ERROR_DISK_FULL (Windows)
    if (code == 28 || code == 112) {
      return true;
    }
  }

  final message = e.message.toLowerCase();
  if (message.contains('no space left') ||
      message.contains('not enough space') ||
      message.contains('disk full')) {
    return true;
  }

  final osMessage = osError?.message.toLowerCase() ?? '';
  if (osMessage.contains('no space left') ||
      osMessage.contains('not enough space') ||
      osMessage.contains('disk full')) {
    return true;
  }

  return false;
}
