// NOTE: A legacy file named download_engine.dart.bak exists alongside this
// file. It is a historical artifact from a prior refactor and is not used by
// the application. It can be safely deleted once this note is confirmed.

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:dio/dio.dart';
import 'package:dio/io.dart';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:synchronized/synchronized.dart';
import 'torrent_service.dart';

import '../utils/bencode_decoder.dart';
import '../utils/file_utils.dart';
import '../utils/url_utils.dart';

class DownloadMetadata {
  final String fileName;
  final String category;
  final int fileSize;
  final bool supportsResume;
  final List<Map<String, dynamic>>? torrentFiles;
  final int? torrentId;

  const DownloadMetadata({
    required this.fileName,
    required this.category,
    required this.fileSize,
    required this.supportsResume,
    this.torrentFiles,
    this.torrentId,
  });
}

class DownloadProgress {
  final int downloadedBytes;
  final int fileSize;
  final double speed;
  final int? eta;
  final List<double>? chunks;
  final String? fileName;
  final List<Map<String, dynamic>>? torrentFiles;
  final bool? supportsResume;

  const DownloadProgress({
    required this.downloadedBytes,
    required this.fileSize,
    required this.speed,
    required this.eta,
    this.chunks,
    this.fileName,
    this.torrentFiles,
    this.supportsResume,
  });
}


class _DownloadIsolateArgs {
  final SendPort sendPort;
  final String url;
  final String punyUrl;
  final String tempFilePath;
  final String localFilePath;
  final int knownFileSize;
  final bool supportsResume;
  final int threadCount;
  final String? customUserAgent;
  final String? referer;
  final bool enableProxy;
  final String? proxyAddress;
  final String? proxyHost;
  final int? proxyPort;
  final String? proxyUsername;
  final String? proxyPassword;
  final bool bypassSSL;
  final String? cookies;
  final String? oauthToken;
  final bool isNameAutoGenerated;
  final int speedLimit;
  final int activeCount;

  _DownloadIsolateArgs({
    required this.sendPort,
    required this.url,
    required this.punyUrl,
    required this.tempFilePath,
    required this.localFilePath,
    required this.knownFileSize,
    required this.supportsResume,
    required this.threadCount,
    this.customUserAgent,
    this.referer,
    required this.enableProxy,
    this.proxyAddress,
    this.proxyHost,
    this.proxyPort,
    this.proxyUsername,
    this.proxyPassword,
    required this.bypassSSL,
    this.cookies,
    this.oauthToken,
    required this.isNameAutoGenerated,
    required this.speedLimit,
    required this.activeCount,
  });
}

void _isolateHttpDownloadEntryPoint(_DownloadIsolateArgs args) async {
  final sendPort = args.sendPort;
  final commandPort = ReceivePort();
  final engine = DownloadEngine(enableCleanupTimer: false);
  final cancelToken = CancelToken();

  int currentSpeedLimit = args.speedLimit;
  int currentActiveCount = args.activeCount;

  commandPort.listen((message) {
    if (message is Map) {
      if (message['type'] == 'cancel') {
        if (!cancelToken.isCancelled) cancelToken.cancel();
      } else if (message['type'] == 'update_speed_limit') {
        currentSpeedLimit = message['value'] as int;
        if (message['activeCount'] != null) {
          currentActiveCount = message['activeCount'] as int;
        }
      }
    }
  });

  void safeSend(Object message) {
    try {
      sendPort.send(message);
    } catch (e) {
      debugPrint('[DMX Isolate] safeSend failed: $e');
    }
  }

  try {
    safeSend(commandPort.sendPort);
    void onProgress(DownloadProgress p) {
      safeSend({
        'type': 'progress',
        'progress': {
           'downloadedBytes': p.downloadedBytes,
           'fileSize': p.fileSize,
           'speed': p.speed,
           'eta': p.eta,
           'chunks': p.chunks,
           'fileName': p.fileName,
           'supportsResume': p.supportsResume,
        }
      });
    }

    await engine._doHttpDownload(
      url: args.url,
      punyUrl: args.punyUrl,
      tempFilePath: args.tempFilePath,
      localFilePath: args.localFilePath,
      knownFileSize: args.knownFileSize,
      supportsResume: args.supportsResume,
      threadCount: args.threadCount,
      customUserAgent: args.customUserAgent,
      referer: args.referer,
      enableProxy: args.enableProxy,
      proxyAddress: args.proxyAddress,
      proxyHost: args.proxyHost,
      proxyPort: args.proxyPort,
      proxyUsername: args.proxyUsername,
      proxyPassword: args.proxyPassword,
      bypassSSL: args.bypassSSL,
      cookies: args.cookies,
      oauthToken: args.oauthToken,
      isNameAutoGenerated: args.isNameAutoGenerated,
      speedLimitBytesPerSecond: () => currentSpeedLimit,
      activeDownloadCount: () => currentActiveCount,
      cancelToken: cancelToken,
      onProgress: onProgress,
    );

    safeSend({'type': 'done'});
  } catch (e) {
    String errType = 'unknown';
    int? errStatus;
    if (e is DioException) {
      if (e.type == DioExceptionType.cancel) { errType = 'cancel'; }
      else if (e.type == DioExceptionType.badResponse) { errType = 'badResponse'; }
      else if (e.type == DioExceptionType.connectionTimeout) { errType = 'connectionTimeout'; }
      else if (e.type == DioExceptionType.receiveTimeout) { errType = 'receiveTimeout'; }
      else if (e.type == DioExceptionType.sendTimeout) { errType = 'sendTimeout'; }
      else if (e.type == DioExceptionType.connectionError) { errType = 'connectionError'; }
      errStatus = e.response?.statusCode;
    }
    safeSend({
      'type': 'error',
      'errorType': errType,
      'errorMessage': e.toString(),
      'errorStatus': errStatus,
    });
  } finally {
    commandPort.close();
    engine.close();
  }
}

class DownloadEngine {
  final List<CancelToken> _activeCancelTokens = [];
  final List<SendPort> _activeIsolateCommandPorts = [];
  final List<Isolate> _activeIsolates = [];
  final Dio _sharedDio;
  final Set<Dio> _activeDioClients = {};
  final Map<Dio, DateTime> _dioClientCreationTimes = {};
  Timer? _cleanupTimer;

  DownloadEngine({Dio? dio, bool enableCleanupTimer = true})
      : _sharedDio = dio ?? Dio() {
    if (enableCleanupTimer) {
      _cleanupTimer = Timer.periodic(const Duration(seconds: 120), (_) {
        final now = DateTime.now();
        _activeDioClients.removeWhere((client) {
          final createdAt = _dioClientCreationTimes[client];
          final age = createdAt != null ? now.difference(createdAt) : Duration.zero;
          // Only clean up clients older than 5 minutes with no active isolates
          if (_activeIsolates.isEmpty && age > const Duration(minutes: 5)) {
            debugPrint('[DMX] Cleanup timer: closing orphaned Dio client (${age.inSeconds}s old)');
            try {
              client.close(force: true);
            } // Safe cleanup: Swallow exception during client cleanup to avoid interrupting loop.
            catch (_) {}
            _dioClientCreationTimes.remove(client);
            return true;
          }
          return false;
        });
      });
    }
  }

  /// Builds an isolated Dio instance configured with per-call options.
  /// Using a fresh client per request prevents the shared [_dio] instance
  /// from being mutated by concurrent downloads (which previously caused
  /// one in-flight download to silently pick up another download's
  /// proxy/UA/SSL settings).
  Dio _buildIsolatedClient({
    String? url,
    String? customUserAgent,
    String? referer,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
  }) {
    final client = Dio();
    client.options.connectTimeout = const Duration(seconds: 30);
    client.options.sendTimeout = const Duration(seconds: 60);
    client.options.receiveTimeout = const Duration(seconds: 60);

    final isYoutubeUrl = url != null &&
        (url.contains('.googlevideo.com/') ||
            url.contains('youtube.com/') ||
            url.contains('youtu.be/'));

    if (isYoutubeUrl) {
      client.options.headers['Origin'] = 'https://www.youtube.com';
      client.options.headers['Referer'] =
          (referer != null && referer.isNotEmpty)
              ? referer
              : 'https://www.youtube.com/';
      client.options.headers['User-Agent'] =
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
      // YouTube expects OAuth Bearer tokens via the Authorization header,
      // not as a cookie. This is required for age-restricted content and
      // authenticated stream access.
      if (oauthToken != null && oauthToken.isNotEmpty) {
        client.options.headers['Authorization'] = 'Bearer $oauthToken';
      }
    } else if (customUserAgent != null && customUserAgent.trim().isNotEmpty) {
      client.options.headers['User-Agent'] = customUserAgent.trim();
    } else {
      client.options.headers['User-Agent'] =
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
    }
    if (referer != null && referer.isNotEmpty && !client.options.headers.containsKey('Referer')) {
      client.options.headers['Referer'] = referer;
    }
    if (cookies != null && cookies.isNotEmpty) {
      client.options.headers['Cookie'] = cookies;
    }


    if (client.httpClientAdapter is IOHttpClientAdapter) {
      final adapter = client.httpClientAdapter as IOHttpClientAdapter;
      final String host =
          (enableProxy && proxyHost != null && proxyHost.trim().isNotEmpty)
          ? proxyHost.trim()
          : (enableProxy && proxyAddress != null && proxyAddress.contains(':')
                ? proxyAddress.split(':')[0].trim()
                : (enableProxy ? proxyAddress?.trim() ?? '' : ''));
      final int port = (enableProxy && proxyPort != null && proxyPort > 0)
          ? proxyPort
          : (enableProxy && proxyAddress != null && proxyAddress.contains(':')
                ? int.tryParse(proxyAddress.split(':')[1]) ?? 8080
                : 8080);

      adapter.createHttpClient = () {
        final httpClient = HttpClient();
        if (enableProxy && host.isNotEmpty) {
          httpClient.findProxy = (uri) {
            return 'PROXY $host:$port';
          };
          if (proxyUsername != null && proxyUsername.isNotEmpty) {
            httpClient.authenticateProxy = (h, p, scheme, realm) async {
              httpClient.addProxyCredentials(
                h,
                p,
                realm ?? '',
                HttpClientBasicCredentials(proxyUsername, proxyPassword ?? ''),
              );
              return true;
            };
          }
        }
        if (bypassSSL) {
          debugPrint('[DMX] SSL verification is BYPASSED for host $host — all certificates accepted.');
          httpClient.badCertificateCallback = (cert, host, port) => true;
        }
        return httpClient;
      };
    }
    _activeDioClients.add(client);
    _dioClientCreationTimes[client] = DateTime.now();
    return client;
  }

  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? customUserAgent,
    String? referer,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
  }) async {
    final isTorrent = isTorrentUrl(url, fileName: requestedFileName);

    if (isTorrent) {
      var fileName = requestedFileName?.trim().isNotEmpty == true
          ? safeFileName(requestedFileName!.trim())
          : 'torrent_download.zip';
      var fileSize = 0; // Default 0
      List<Map<String, dynamic>>? torrentFiles;

      if (url.startsWith('magnet:')) {
        final magnetParams = parseMagnetUrl(url);
        final magnetName = magnetParams['name'];
        final resolvedName = requestedFileName?.trim().isNotEmpty == true
            ? safeFileName(requestedFileName!.trim())
            : (magnetName != null && magnetName.trim().isNotEmpty
                  ? safeFileName(magnetName.trim())
                  : 'torrent_download.zip');

        String tempDir = '';
        if (!kIsWeb) {
          try {
            final directory = await getTemporaryDirectory();
            tempDir = directory.path;
          } catch (e) {
            debugPrint('Failed to get temporary directory: $e');
            throw StateError('Cannot resolve temporary directory for Torrent download: $e');
          }
        }
        final torrentId = TorrentService.addMagnet(url, tempDir);
        TorrentService.resumeTorrent(torrentId);

        final completer = Completer<DownloadMetadata>();
        StreamSubscription? sub;

        sub = TorrentService.torrentUpdates.listen((torrents) {
          final torrent = torrents[torrentId];
          if (torrent != null && torrent.hasMetadata) {
            sub?.cancel();

            final files = TorrentService.getFiles(torrentId);
            final resolvedFiles = files
                .map(
                  (f) => {
                    'name': f.name,
                    'length': f.size,
                    'selected': true,
                    'priority': 4,
                    'downloadedBytes': 0,
                    'speed': 0.0,
                  },
                )
                .toList();

            final totalSize = resolvedFiles.fold(
              0,
              (sum, f) => sum + (f['length'] as int),
            );

            if (!completer.isCompleted) {
              try {
                TorrentService.pauseTorrent(torrentId);
                TorrentService.removeTorrent(torrentId);
              } // Safe cleanup: Swallow exception during best-effort torrent engine cleanup.
              catch (_) {}
              completer.complete(
                DownloadMetadata(
                  fileName: torrent.name,
                  category: 'Archive',
                  fileSize: totalSize,
                  supportsResume: true,
                  torrentFiles: resolvedFiles,
                  torrentId: null,
                ),
              );
            }
          }
        });

        // Timeout of 30 seconds -> Fallback to placeholder/magnet name instead of failing
        Future.delayed(const Duration(seconds: 30), () {
          if (!completer.isCompleted) {
            sub?.cancel();
            try {
              TorrentService.pauseTorrent(torrentId);
              TorrentService.removeTorrent(torrentId);
            } // Safe cleanup: Swallow exception during best-effort torrent engine cleanup on timeout.
            catch (_) {}
            completer.complete(
              DownloadMetadata(
                fileName: resolvedName,
                category: 'Archive',
                fileSize: 0,
                supportsResume: true,
                torrentFiles: null,
                torrentId: null,
              ),
            );
          }
        });

        return completer.future;
      } else if (url.startsWith('file://')) {
        final filePath = Uri.parse(url).toFilePath();
        final file = File(filePath);
        if (await file.exists()) {
          final bytes = await file.readAsBytes();
          final meta = await compute(BencodeDecoder.parseTorrentBytes, bytes);
          if (meta != null) {
            fileName = meta['name'] ?? fileName;
            fileSize = meta['length'] ?? fileSize;
            torrentFiles = (meta['files'] as List? ?? [])
                .map(
                  (f) => {
                    'name': f['name'] as String? ?? '',
                    'length': f['length'] as int? ?? 0,
                    'selected': true,
                    'priority': 4,
                    'downloadedBytes': 0,
                    'speed': 0.0,
                  },
                )
                .toList();
          }
        }
      }

      return DownloadMetadata(
        fileName: fileName,
        category: 'Archive',
        fileSize: fileSize,
        supportsResume: true,
        torrentFiles: torrentFiles,
      );
    }

    final punyUrl = convertIdnToPunycode(url);
    var fileName = requestedFileName?.trim().isNotEmpty == true
        ? safeFileName(requestedFileName!.trim())
        : fileNameFromUrl(punyUrl);
    var fileSize = 0;
    final isYoutube = punyUrl.contains('youtube.com') ||
        punyUrl.contains('youtu.be') ||
        punyUrl.contains('.googlevideo.com');
    var supportsResume = isYoutube;

    // Use a per-call Dio so concurrent downloads don't share UA/proxy/SSL
    // state via the engine's long-lived client.
    final isolatedDio = _buildIsolatedClient(
      url: punyUrl,
      customUserAgent: customUserAgent,
      referer: referer,
      enableProxy: enableProxy,
      proxyAddress: proxyAddress,
      proxyHost: proxyHost,
      proxyPort: proxyPort,
      proxyUsername: proxyUsername,
      proxyPassword: proxyPassword,
      bypassSSL: bypassSSL,
      cookies: cookies,
      oauthToken: oauthToken,
    );

    try {
      final response = await isolatedDio.head<dynamic>(
        punyUrl,
        options: Options(followRedirects: true, validateStatus: (_) => true),
      );
      final headerName = fileNameFromContentDisposition(response.headers);
      if (requestedFileName?.trim().isNotEmpty != true && headerName != null) {
        fileName = headerName;
      }

      final length = response.headers.value(Headers.contentLengthHeader);
      fileSize = int.tryParse(length ?? '') ?? 0;

      final acceptRanges = response.headers
          .value('accept-ranges')
          ?.toLowerCase();
      if (acceptRanges != null) {
        supportsResume = acceptRanges == 'bytes';
      } else {
        supportsResume = isYoutube || response.statusCode == 206;
      }

      // If HEAD returns 403, 405, 400 or no content length, fall back to ranged GET probe
      if (fileSize == 0 || response.statusCode == 403 || response.statusCode == 405 || response.statusCode == 400) {
        try {
          final getResponse = await isolatedDio.get<ResponseBody>(
            punyUrl,
            options: Options(
              responseType: ResponseType.stream,
              followRedirects: true,
              headers: {'Range': 'bytes=0-0'},
              validateStatus: (_) => true,
            ),
          );
          if (getResponse.statusCode == 200 || getResponse.statusCode == 206) {
            final getHeaderName = fileNameFromContentDisposition(getResponse.headers);
            if (requestedFileName?.trim().isNotEmpty != true && getHeaderName != null) {
              fileName = getHeaderName;
            }
            final contentRange = getResponse.headers.value('content-range');
            if (contentRange != null) {
              final totalMatch = RegExp(r'/(\d+)').firstMatch(contentRange);
              if (totalMatch != null) {
                fileSize = int.tryParse(totalMatch.group(1)!) ?? 0;
              }
            }
            if (fileSize == 0) {
              final getLen = getResponse.headers.value(Headers.contentLengthHeader);
              fileSize = int.tryParse(getLen ?? '') ?? 0;
            }
            supportsResume = isYoutube || getResponse.statusCode == 206 || getResponse.headers.value('accept-ranges') == 'bytes';
          }
        } catch (e) {
          debugPrint('[DownloadEngine] resolveMetadata ranged GET probe failed: $e');
        }
      }
    } catch (e) {
      debugPrint('HEAD request failed for $punyUrl: $e');
    } finally {
      _activeDioClients.remove(isolatedDio);
      _dioClientCreationTimes.remove(isolatedDio);
      isolatedDio.close(force: true);
    }

    return DownloadMetadata(
      fileName: fileName,
      category: categoryFromFileName(fileName),
      fileSize: fileSize,
      supportsResume: supportsResume,
    );
  }

  void updateSpeedLimit(int bytesPerSecond, int activeCount) {
    TorrentService.setDownloadLimit(bytesPerSecond);
    for (final port in _activeIsolateCommandPorts) {
      port.send({'type': 'update_speed_limit', 'value': bytesPerSecond, 'activeCount': activeCount});
    }
  }

  Future<void> download({
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    String? customUserAgent,
    String? referer,
    bool enableProxy = false,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool bypassSSL = false,
    String? cookies,
    String? oauthToken,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
  }) async {
    _activeCancelTokens.add(cancelToken);
    int resolvedFileSize = knownFileSize;
    bool resolvedSupportsResume = supportsResume;
    String? resolvedFileName;
    String currentTempFilePath = tempFilePath;
    String currentLocalFilePath = localFilePath;

    final isTorrent = isTorrentUrl(url, fileName: fileNameFromUrl(url));

    if (!isTorrent && resolvedFileSize == 0 && isNameAutoGenerated) {
      try {
        final meta = await resolveMetadata(
          url: url,
          customUserAgent: customUserAgent,
          referer: referer,
          enableProxy: enableProxy,
          proxyAddress: proxyAddress,
          proxyHost: proxyHost,
          proxyPort: proxyPort,
          proxyUsername: proxyUsername,
          proxyPassword: proxyPassword,
          bypassSSL: bypassSSL,
          cookies: cookies,
        );
        resolvedFileSize = meta.fileSize;
        resolvedSupportsResume = meta.supportsResume;
        resolvedFileName = meta.fileName;
      } catch (e) {
        debugPrint('[DownloadEngine] resolveMetadata failed in startDownload: $e');
      }

      if (resolvedFileName != null) {
        final saveDir = File(localFilePath).parent.path;
        currentLocalFilePath = p.join(saveDir, safeFileName(resolvedFileName));
        currentTempFilePath = p.join(
          saveDir,
          '${safeFileName(resolvedFileName)}.dmxpart',
        );
      }

      if (resolvedFileName != null || resolvedFileSize > 0) {
        onProgress(
          DownloadProgress(
            downloadedBytes: 0,
            fileSize: resolvedFileSize,
            speed: 0.0,
            eta: null,
            fileName: resolvedFileName,
            supportsResume: resolvedSupportsResume,
          ),
        );
      }
    }

    if (isTorrent) {
      // Torrent logic remains in main isolate
      await _handleTorrentDownload(
        url: url,
        currentTempFilePath: currentTempFilePath,
        currentLocalFilePath: currentLocalFilePath,
        knownFileSize: resolvedFileSize,
        cancelToken: cancelToken,
        onProgress: onProgress,
        getTorrentFiles: getTorrentFiles,
        torrentId: torrentId,
      );
      _activeCancelTokens.remove(cancelToken);
      return;
    }

    var finalUrl = url;
    finalUrl = finalUrl.replaceAll(RegExp(r'(?<=[?&])range=[^&]*&?'), '');
    if (finalUrl.endsWith('?')) finalUrl = finalUrl.substring(0, finalUrl.length - 1);
    if (finalUrl.endsWith('&')) finalUrl = finalUrl.substring(0, finalUrl.length - 1);

    final punyUrl = convertIdnToPunycode(finalUrl);

    final receivePort = ReceivePort();
    final errorPort = ReceivePort();

    final args = _DownloadIsolateArgs(
      sendPort: receivePort.sendPort,
      url: url,
      punyUrl: punyUrl,
      tempFilePath: currentTempFilePath,
      localFilePath: currentLocalFilePath,
      knownFileSize: resolvedFileSize,
      supportsResume: resolvedSupportsResume,
      threadCount: threadCount,
      customUserAgent: customUserAgent,
      referer: referer,
      enableProxy: enableProxy,
      proxyAddress: proxyAddress,
      proxyHost: proxyHost,
      proxyPort: proxyPort,
      proxyUsername: proxyUsername,
      proxyPassword: proxyPassword,
      bypassSSL: bypassSSL,
      cookies: cookies,
      oauthToken: oauthToken,
      isNameAutoGenerated: isNameAutoGenerated,
      speedLimit: speedLimitBytesPerSecond(),
      activeCount: activeDownloadCount(),
    );

    final exitPort = ReceivePort();
    final isolate = await Isolate.spawn(
      _isolateHttpDownloadEntryPoint,
      args,
      debugName: 'DownloadIsolate_${finalUrl.hashCode}',
      onError: errorPort.sendPort,
    );
    isolate.addOnExitListener(exitPort.sendPort);
    _activeIsolates.add(isolate);

    var exitPortClosed = false;
    void closeExitPort() {
      if (!exitPortClosed) {
        exitPortClosed = true;
        exitPort.close();
      }
    }
    exitPort.listen((_) {
      _activeIsolates.remove(isolate);
      closeExitPort();
    });

    final completer = Completer<void>();
    SendPort? isolateCommandPort;
    bool isCancelledEarly = false;

    Timer? isolateWatchdog;
    isolateWatchdog = Timer(const Duration(seconds: 30), () {
      if (isolateCommandPort == null) {
        isolate.kill(priority: Isolate.immediate);
        if (!completer.isCompleted) {
          completer.completeError(
            DioException(
              requestOptions: RequestOptions(path: punyUrl),
              type: DioExceptionType.connectionTimeout,
              message: 'Isolate failed to initialize within 30 seconds.',
            ),
          );
        }
      }
    });

    void handleEarlyCancel() {
      if (isolateCommandPort != null) {
        isolateCommandPort!.send({'type': 'cancel'});
      } else {
        isCancelledEarly = true;
        isolate.kill(priority: Isolate.immediate);
        if (!completer.isCompleted) {
          completer.completeError(
            DioException(
              requestOptions: RequestOptions(path: punyUrl),
              type: DioExceptionType.cancel,
              message: 'Download cancelled before isolate initialized.',
            ),
          );
        }
      }
    }

    cancelToken.whenCancel.then((_) => handleEarlyCancel());
    if (cancelToken.isCancelled) {
      handleEarlyCancel();
    }

    errorPort.listen((message) {
      if (message is List && message.isNotEmpty) {
        final exception = Exception(message[0].toString());
        final stack = message.length > 1 ? StackTrace.fromString(message[1].toString()) : StackTrace.current;
        if (!completer.isCompleted) {
          completer.completeError(exception, stack);
        }
      } else {
        if (!completer.isCompleted) {
          completer.completeError(Exception('Isolate exited unexpectedly without payload.'));
        }
      }
    });

    receivePort.listen((message) {
      if (message is SendPort) {
        isolateCommandPort = message;
        _activeIsolateCommandPorts.add(isolateCommandPort!);
        if (isCancelledEarly) {
          isolateCommandPort!.send({'type': 'cancel'});
        }
      } else if (message is Map) {
        final type = message['type'];
        if (type == 'progress') {
          final p = message['progress'] as Map;
          onProgress(DownloadProgress(
            downloadedBytes: p['downloadedBytes'],
            fileSize: p['fileSize'],
            speed: p['speed'],
            eta: p['eta'],
            chunks: p['chunks'] != null ? List<double>.from(p['chunks']) : null,
            fileName: p['fileName'],
            supportsResume: p['supportsResume'],
          ));
        } else if (type == 'done') {
          if (!completer.isCompleted) completer.complete();
        } else if (type == 'error') {
          final errType = message['errorType'];
          final errMsg = message['errorMessage'];
          final errStatus = message['errorStatus'];
          final isCancel = errType == 'cancel';
          
          DioExceptionType dioType = DioExceptionType.unknown;
          if (isCancel) { dioType = DioExceptionType.cancel; }
          else if (errType == 'badResponse') { dioType = DioExceptionType.badResponse; }
          else if (errType == 'connectionTimeout') { dioType = DioExceptionType.connectionTimeout; }
          else if (errType == 'receiveTimeout') { dioType = DioExceptionType.receiveTimeout; }
          else if (errType == 'sendTimeout') { dioType = DioExceptionType.sendTimeout; }
          else if (errType == 'connectionError') { dioType = DioExceptionType.connectionError; }
          
          final dioException = DioException(
            requestOptions: RequestOptions(path: punyUrl),
            type: dioType,
            message: errMsg,
            response: errStatus != null ? Response(requestOptions: RequestOptions(path: punyUrl), statusCode: errStatus) : null,
          );
          if (!completer.isCompleted) completer.completeError(dioException);
        }
      }
    });

    try {
      await completer.future;
    } finally {
      isolateWatchdog.cancel();
      if (isolateCommandPort != null) {
        _activeIsolateCommandPorts.remove(isolateCommandPort);
      }
      receivePort.close();
      errorPort.close();
      closeExitPort();
      _activeIsolates.removeWhere((i) => i == isolate);
      isolate.kill(priority: Isolate.immediate);
      _activeCancelTokens.remove(cancelToken);
    }
  }

  Future<void> _handleTorrentDownload({
    required String url,
    required String currentTempFilePath,
    required String currentLocalFilePath,
    required int knownFileSize,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
  }) async {
    int id = torrentId ?? -1;
      if (id == -1) {
        final saveDir = File(currentLocalFilePath).parent.path;
        if (url.startsWith('magnet:')) {
          id = TorrentService.addMagnet(url, saveDir);
        } else {
          String filePath = url;
          if (url.startsWith('file://')) {
            filePath = Uri.parse(url).toFilePath();
          } else if (url.startsWith('http://') || url.startsWith('https://')) {
            final tempTorrentPath = p.join(Directory.systemTemp.path, 'temp_${DateTime.now().millisecondsSinceEpoch}.torrent');
            await Dio().download(url, tempTorrentPath);
            filePath = tempTorrentPath;
          }
          id = TorrentService.addTorrentFile(filePath, saveDir);
        }
      }
      if (id < 0) {
        throw DioException(
          requestOptions: RequestOptions(path: url),
          type: DioExceptionType.unknown,
          error: 'Torrent engine rejected the torrent.',
        );
      }

      // Wait for metadata to resolve
      final metadataCompleter = Completer<void>();
      StreamSubscription? metadataSub;
      bool metadataReceived = false;

      metadataSub = TorrentService.torrentUpdates.listen((torrents) {
        if (cancelToken.isCancelled) return;
        final torrent = torrents[id];
        if (torrent != null && torrent.hasMetadata) {
          metadataSub?.cancel();
          metadataReceived = true;
          if (!metadataCompleter.isCompleted) {
            metadataCompleter.complete();
          }
        }
      });

      Timer? metadataTimer;
      final downloadCompleter = Completer<void>();

      // Handle cancel during metadata loading AND downloading
      cancelToken.whenCancel.then((_) async {
        if (metadataCompleter.isCompleted) {
          // Metadata already received → pause for resume (download phase)
          TorrentService.pauseTorrent(id);
        } else {
          // Metadata not yet received → remove (metadata phase, nothing to resume)
          try {
            TorrentService.removeTorrent(id);
          } // Safe cleanup: Swallow exception when removing torrent during cancellation.
          catch (_) {}
        }
        await metadataSub?.cancel();
        metadataTimer?.cancel();
        if (!metadataCompleter.isCompleted) {
          metadataCompleter.completeError(
            DioException(
              requestOptions: RequestOptions(path: url),
              type: DioExceptionType.cancel,
              error: 'cancelled',
            ),
          );
        } else if (!downloadCompleter.isCompleted) {
          downloadCompleter.completeError(
            DioException(
              requestOptions: RequestOptions(path: url),
              type: DioExceptionType.cancel,
              error: 'cancelled',
            ),
          );
        }
      }).catchError((e) {
        debugPrint('Torrent download cancel handler error: $e');
      });

      // Metadata timeout: use removeTorrent (not just pauseTorrent) because the
      // torrent never started downloading — there is nothing to resume. This
      // differs from the active-download cancel handler above, which only pauses
      // so the user can resume from partial progress later.
      metadataTimer = Timer(const Duration(seconds: 45), () {
        if (metadataCompleter.isCompleted) return;
        metadataSub?.cancel();
        try {
          TorrentService.pauseTorrent(id);
          TorrentService.removeTorrent(id);
        } // Safe cleanup: Swallow exception when pausing/removing torrent during metadata timeout.
        catch (_) {}
        if (!metadataCompleter.isCompleted) {
          metadataCompleter.completeError(
            DioException(
              requestOptions: RequestOptions(path: url),
              type: DioExceptionType.receiveTimeout,
              error: 'Timed out waiting for torrent metadata.',
            ),
          );
        }
      });

      try {
        await metadataCompleter.future;
      } finally {
        metadataTimer.cancel();
      }

      // Set file priorities after metadata is loaded
      final currentTorrentFiles = getTorrentFiles?.call();
      if (currentTorrentFiles != null && currentTorrentFiles.isNotEmpty) {
        final priorities = currentTorrentFiles.map((f) {
          final selected = f['selected'] as bool? ?? true;
          if (!selected) return 0;
          return f['priority'] as int? ?? 4;
        }).toList();
        TorrentService.setFilePriorities(id, priorities);
      }

      // Resume download
      TorrentService.resumeTorrent(id);

      StreamSubscription? downloadSub;
      int lastTorrentReportTime = 0;

      downloadSub = TorrentService.torrentUpdates.listen((torrents) {
        final torrent = torrents[id];
        if (torrent == null) return;

        final progress = torrent.progress; // double from 0.0 to 1.0
        final stateLabel = torrent.stateLabel.toLowerCase();

        final totalSize = torrent.totalWanted > 0
            ? torrent.totalWanted
            : (knownFileSize > 0 ? knownFileSize : 0);
        final downloadedBytes = torrent.totalDone;
        final isCheckingOrMetadata =
            stateLabel.contains('checking') ||
            stateLabel.contains('metadata') ||
            stateLabel.contains('allocating');

        final isFullyDownloaded = totalSize > 0 && downloadedBytes >= totalSize;
        final isCompleted =
            isFullyDownloaded &&
            ((progress >= 1.0 && !isCheckingOrMetadata) ||
                stateLabel == 'seeding' ||
                stateLabel == 'completed' ||
                stateLabel == 'finished');

        final nowMs = DateTime.now().millisecondsSinceEpoch;
        if (!isCompleted && (nowMs - lastTorrentReportTime < 500)) return;
        lastTorrentReportTime = nowMs;

        final speed = torrent.downloadRate.toDouble();
        final remaining = totalSize - downloadedBytes;
        final eta = speed > 0 && remaining > 0
            ? (remaining / speed).round()
            : 0;

        List<Map<String, dynamic>>? resolvedFiles;
        String? resolvedName;
        if (torrent.hasMetadata) {
          resolvedName = torrent.name;
          try {
            final files = TorrentService.getFiles(id);
            resolvedFiles = files
                .map(
                  (f) => {
                    'name': f.name,
                    'length': f.size,
                    'selected': true,
                    'priority': 4,
                    'downloadedBytes': 0,
                    'speed': 0.0,
                  },
                )
                .toList();
          } catch (e) {
            debugPrint('[DownloadEngine] TorrentService.getFiles failed: $e');
          }
        }

        onProgress(
          DownloadProgress(
            downloadedBytes: downloadedBytes,
            fileSize: totalSize,
            speed: speed,
            eta: eta,
            chunks: null,
            fileName: resolvedName,
            torrentFiles: resolvedFiles,
          ),
        );

        if (isCompleted) {
          downloadSub?.cancel();
          if (!downloadCompleter.isCompleted) {
            downloadCompleter.complete();
          }
        }
      });

      await downloadCompleter.future;
      _activeCancelTokens.remove(cancelToken);
      return;
  }


  Future<void> _doHttpDownload({
    required String url,
    required String punyUrl,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required int threadCount,
    String? customUserAgent,
    String? referer,
    required bool enableProxy,
    String? proxyAddress,
    String? proxyHost,
    int? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    required bool bypassSSL,
    String? cookies,
    String? oauthToken,
    required bool isNameAutoGenerated,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
  }) async {
    int resolvedFileSize = knownFileSize;
    bool resolvedSupportsResume = supportsResume;
    String currentTempFilePath = tempFilePath;
    String currentLocalFilePath = localFilePath;
    String? resolvedFileName;
    if (isNameAutoGenerated) {
       resolvedFileName = fileNameFromUrl(url);
    }


    // Use a per-call Dio so concurrent downloads don't share UA/proxy/SSL
    // state via the engine's long-lived client.
    final isolatedDio = _buildIsolatedClient(
      url: punyUrl,
      customUserAgent: customUserAgent,
      referer: referer,
      enableProxy: enableProxy,
      proxyAddress: proxyAddress,
      proxyHost: proxyHost,
      proxyPort: proxyPort,
      proxyUsername: proxyUsername,
      proxyPassword: proxyPassword,
      bypassSSL: bypassSSL,
      cookies: cookies,
      oauthToken: oauthToken,
    );

    try {
      if (resolvedFileSize < threadCount * 1024) {
        threadCount = 1;
      }
      final isMultiThread =
          threadCount > 1 && resolvedSupportsResume && resolvedFileSize > 0;

      debugPrint('[DMX] Starting download. Multi-thread: $isMultiThread. '
          'Thread count: $threadCount, supportsResume: $resolvedSupportsResume, '
          'fileSize: $resolvedFileSize');

      if (!isMultiThread) {
        await _downloadSingleThreaded(
          url: url,
          punyUrl: punyUrl,
          tempFilePath: currentTempFilePath,
          localFilePath: currentLocalFilePath,
          knownFileSize: resolvedFileSize,
          supportsResume: resolvedSupportsResume,
          cancelToken: cancelToken,
          onProgress: onProgress,
          speedLimitBytesPerSecond: speedLimitBytesPerSecond,
          activeDownloadCount: activeDownloadCount,
          isolatedDio: isolatedDio,
          isNameAutoGenerated: isNameAutoGenerated,
        );
      } else {
        // Real Multi-Thread segment downloading
        final futures = <Future<void>>[];
        final chunkCancelTokens = List<CancelToken>.generate(threadCount, (_) => CancelToken());
        final chunkProgress = List<int>.filled(threadCount, 0);
        final chunkSizes = List<int>.filled(threadCount, 0);

        final totalSize = resolvedFileSize;
        final partSize = (totalSize / threadCount).floor();

        final targetFile = File(currentTempFilePath);
        await targetFile.parent.create(recursive: true);
        final stateFile = File('$currentTempFilePath.dmxstate');

        // Read resume state BEFORE opening the file
        final fileExists = await targetFile.exists();
        bool needPreallocate = true;
        if (fileExists) {
          final actualLen = await targetFile.length();
          needPreallocate = actualLen != totalSize;
        }
        List<int>? loadedState;
        if (!needPreallocate && await stateFile.exists()) {
          try {
            final content = await stateFile.readAsString();
            final stateList = jsonDecode(content) as List;
            if (stateList.length == threadCount) {
              loadedState = stateList.cast<int>();
              for (int i = 0; i < threadCount; i++) {
                chunkProgress[i] = loadedState[i];
              }
            }
          } catch (e) {
            // state corrupt, will reset below
          }
        }
        if (needPreallocate || loadedState == null) {
          if (await stateFile.exists()) await stateFile.delete();
          for (int i = 0; i < threadCount; i++) {
            chunkProgress[i] = 0;
          }
        }
        // Open file: only truncate when pre-allocating; otherwise open read-write without truncation
        late RandomAccessFile sharedRaf;
        if (needPreallocate) {
          sharedRaf = await targetFile.open(mode: FileMode.write);
          await sharedRaf.truncate(totalSize);
        } else {
          sharedRaf = await targetFile.open(mode: FileMode.writeOnly);
        }
        bool isRafClosed = false;

        final lock = Lock();

        // Calculate start/end boundaries
        for (int i = 0; i < threadCount; i++) {
          final start = i * partSize;
          final end = (i == threadCount - 1)
              ? (totalSize - 1)
              : (start + partSize - 1);
          final size = end - start + 1;
          chunkSizes[i] = size;
          // Validate chunkProgress
          if (chunkProgress[i] > size) {
            chunkProgress[i] = 0;
          }
        }

        final stopwatch = Stopwatch()..start();
        final speedSamples = Queue<_SpeedSample>();

        int lastReportTime = 0;
        int lastStateSaveTime = 0;

        Future<void> saveState() async {
          try {
            await lock.synchronized(() async {
              final tempStateFile = File('${stateFile.path}.tmp');
              await tempStateFile.writeAsString(jsonEncode(chunkProgress));
              await tempStateFile.rename(stateFile.path);
            });
          } catch (e) {
            debugPrint('Failed to save state: $e');
          }
        }

        void reportProgress() {
          final downloadedTotal = chunkProgress.reduce((a, b) => a + b);
          final nowMs = stopwatch.elapsedMilliseconds;
          speedSamples.add(_SpeedSample(nowMs, downloadedTotal));

          // Keep samples from the last 3 seconds
          while (speedSamples.isNotEmpty &&
              nowMs - speedSamples.first.timestampMs > 3000) {
            speedSamples.removeFirst();
          }

          var speed = 0.0;
          if (speedSamples.length > 1) {
            final first = speedSamples.first;
            final elapsedSeconds = (nowMs - first.timestampMs) / 1000.0;
            if (elapsedSeconds > 0) {
              speed = (downloadedTotal - first.bytes) / elapsedSeconds;
            }
          }

          final remaining = totalSize > downloadedTotal
              ? totalSize - downloadedTotal
              : 0;
          final eta = speed > 0 && remaining > 0
              ? (remaining / speed).round()
              : null;

          final isCompleted = totalSize > 0 && downloadedTotal >= totalSize;
          if (nowMs - lastReportTime >= 250 || isCompleted) {
            lastReportTime = nowMs;

            final chunksList = List<double>.generate(threadCount, (idx) {
              return chunkSizes[idx] > 0
                  ? (chunkProgress[idx] / chunkSizes[idx]).clamp(0.0, 1.0)
                  : 1.0;
            });

            Future.microtask(() {
              onProgress(
                DownloadProgress(
                  downloadedBytes: downloadedTotal,
                  fileSize: totalSize,
                  speed: speed,
                  eta: eta,
                  chunks: chunksList,
                  fileName: resolvedFileName,
                  supportsResume: true,
                ),
              );
            });
          }

          if (nowMs - lastStateSaveTime >= 2000 || isCompleted) {
            lastStateSaveTime = nowMs;
            saveState();
          }
        }

        Object? chunkError;
        try {
          for (int i = 0; i < threadCount; i++) {
            final idx = i;
            final start = idx * partSize;
            final end = (idx == threadCount - 1)
                ? (totalSize - 1)
                : (start + partSize - 1);

            futures.add(() async {
              cancelToken.whenCancel.then((_) {
                for (final ct in chunkCancelTokens) {
                  if (!ct.isCancelled) ct.cancel();
                }
              });

              final chunkStopwatch = Stopwatch()..start();
              var resumeFrom = chunkProgress[idx];
              if (resumeFrom >= chunkSizes[idx]) return;

              // Setup Micro-retries
              int attempts = 0;
              const maxAttempts = 3;

              while (attempts < maxAttempts) {
                attempts++;
                try {
                  resumeFrom = chunkProgress[idx];
                  if (resumeFrom >= chunkSizes[idx]) break;

                  final headers = <String, dynamic>{};
                  headers['Range'] = 'bytes=${start + resumeFrom}-$end';

                  final chunkResponse = await isolatedDio.get<ResponseBody>(
                    punyUrl,
                    cancelToken: chunkCancelTokens[idx],
                    options: Options(
                      responseType: ResponseType.stream,
                      followRedirects: true,
                      headers: headers,
                      validateStatus: (_) => true,
                    ),
                  );

                  if (chunkResponse.statusCode != 206) {
                    throw DioException(
                      requestOptions: RequestOptions(path: punyUrl),
                      type: DioExceptionType.badResponse,
                      response: chunkResponse,
                      message: 'Server returned ${chunkResponse.statusCode} instead of 206.',
                    );
                  }

                  _validateContentRange(
                    chunkResponse.headers.value('content-range'),
                    expectedStart: start + resumeFrom,
                    expectedEnd: end,
                    expectedTotal: totalSize,
                  );

                  try {
                    final stream = chunkResponse.data?.stream;
                    if (stream == null) {
                      throw DioException(
                        requestOptions: RequestOptions(path: punyUrl),
                        type: DioExceptionType.badResponse,
                        message: 'Server returned empty response body.',
                      );
                    }
                    final buffer = BytesBuilder(copy: false);
                    int bufferStartOffset = start + chunkProgress[idx];
                    var chunkDownloadedThisSession = 0;
                    var localWrittenBytes = 0; // tracks bytes committed to disk for this chunk

                    try {
                      await for (final chunk in stream) {
                        if (cancelToken.isCancelled || chunkCancelTokens[idx].isCancelled) {
                          throw DioException(
                            requestOptions: RequestOptions(path: punyUrl),
                            type: DioExceptionType.cancel,
                            message: 'Download cancelled.',
                          );
                        }

                        buffer.add(chunk);
                        chunkDownloadedThisSession += chunk.length;

                        if (buffer.length >= 1024 * 1024) {
                          final bytesToWrite = buffer.takeBytes();
                          await lock.synchronized(() async {
                            await sharedRaf.setPosition(bufferStartOffset);
                            await sharedRaf.writeFrom(bytesToWrite);
                          });
                          bufferStartOffset += bytesToWrite.length;
                          localWrittenBytes += bytesToWrite.length;
                          chunkProgress[idx] = resumeFrom + localWrittenBytes;
                        }

                        reportProgress();

                        final limit = speedLimitBytesPerSecond();
                        if (limit > 0) {
                          final activeCount = activeDownloadCount().clamp(1, 1000);
                          final perTaskLimit = limit / activeCount.toDouble();
                          final limitPerChunk = perTaskLimit / threadCount.toDouble();
                          if (limitPerChunk > 0) {
                            final expectedElapsedMs = (chunkDownloadedThisSession / limitPerChunk * 1000.0).round();
                            final actualElapsedMs = chunkStopwatch.elapsedMilliseconds;
                            if (expectedElapsedMs > actualElapsedMs) {
                              final sleepTimeMs = (expectedElapsedMs - actualElapsedMs).clamp(0, 30000);
                              if (sleepTimeMs > 0) {
                                await Future<void>.delayed(Duration(milliseconds: sleepTimeMs));
                              }
                            }
                          }
                          chunkStopwatch.reset();
                          chunkDownloadedThisSession = 0;
                        }
                      }

                      if (buffer.length > 0) {
                        final bytesToWrite = buffer.takeBytes();
                        await lock.synchronized(() async {
                          await sharedRaf.setPosition(bufferStartOffset);
                          await sharedRaf.writeFrom(bytesToWrite);
                        });
                        localWrittenBytes += bytesToWrite.length;
                        chunkProgress[idx] = resumeFrom + localWrittenBytes;
                      }
                    } catch (e) {
                      if (buffer.length > 0) {
                        try {
                          final bytesToWrite = buffer.takeBytes();
                          await lock.synchronized(() async {
                            await sharedRaf.setPosition(bufferStartOffset);
                            await sharedRaf.writeFrom(bytesToWrite);
                          });
                          localWrittenBytes += bytesToWrite.length;
                          chunkProgress[idx] = resumeFrom + localWrittenBytes;
                        } catch (writeError) {
                          debugPrint('Failed to flush buffer on error: $writeError');
                        }
                      }
                      rethrow;
                    }
                    // Success, break out of retry loop
                    break;
                  } finally {
                    // Nothing to close here, sharedRaf is closed later
                  }
                } catch (e) {
                  if (cancelToken.isCancelled || chunkCancelTokens[idx].isCancelled) {
                    rethrow;
                  }
                  if (attempts >= maxAttempts) {
                    for (final ct in chunkCancelTokens) {
                      if (!ct.isCancelled) ct.cancel();
                    }
                    chunkError ??= e;
                    rethrow;
                  }
                  debugPrint('Thread $idx failed attempt $attempts: $e. Retrying in ${attempts}s...');
                  await Future.delayed(Duration(seconds: attempts));
                }
              }
            }());
          }

          // Wait for all threads to complete
          await Future.wait(futures);
          await saveState();

          try {
            if (!isRafClosed) {
              await sharedRaf.flush();
              await sharedRaf.close();
              isRafClosed = true;
            }
          } catch (e) {
            debugPrint('Failed to close shared RAF: $e');
          }

          if (totalSize > 0) {
            final actualSize = await targetFile.length();
            if (actualSize != totalSize) {
              throw Exception(
                'Download integrity check failed: expected $totalSize bytes, got $actualSize bytes.',
              );
            }
          }

          // Rename to final local file and cleanup state
          if (currentTempFilePath != currentLocalFilePath) {
            final finalFile = File(currentLocalFilePath);
            if (await finalFile.exists()) {
              await finalFile.delete();
            }
            try {
              await targetFile.rename(currentLocalFilePath);
            } catch (e) {
              await targetFile.copy(currentLocalFilePath);
              final copiedLen = await File(currentLocalFilePath).length();
              final origLen = await targetFile.length();
              if (copiedLen == origLen) {
                await targetFile.delete();
              } else {
                throw Exception('File copy failed on rename fallback.');
              }
            }
          }
          if (await stateFile.exists()) {
            await stateFile.delete();
          }

        } catch (e) {
          try {
            if (!isRafClosed) {
              await sharedRaf.close();
              isRafClosed = true;
            }
          } // Safe cleanup: Swallow exception when closing random access file inside catch.
          catch (_) {}

          if (cancelToken.isCancelled) {
            await saveState(); // Save state on cancel
            rethrow;
          }

          final errorToCheck = chunkError ?? e;

          bool isRangeRejection = false;
          if (errorToCheck is DioException &&
              errorToCheck.type == DioExceptionType.badResponse) {
            final status = errorToCheck.response?.statusCode;
            if (status == 200 || status == 416) {
              isRangeRejection = true;
            }
            if (errorToCheck.message?.startsWith('Invalid Content-Range') ==
                true) {
              isRangeRejection = true;
            }
          }

          if (!isRangeRejection) {
            await saveState();
            rethrow;
          }

          // Fallback on range failure or range reject
          debugPrint(
            'Multi-threaded range request failed (Range Rejection): $e. Checking aggregated progress.',
          );

          // Find the longest valid contiguous prefix from any chunk.
          // Chunk 0 is sequential from byte 0, but if it made no progress,
          // check other chunks that may have valid sequential data.
          int contiguousBytes = 0;
          for (int ci = 0; ci < chunkProgress.length; ci++) {
            if (chunkProgress[ci] == chunkSizes[ci]) {
              // Whole chunk is complete, extend the contiguous prefix
              int chunkStart = 0;
              for (int cj = 0; cj < ci; cj++) {
                chunkStart += chunkSizes[cj];
              }
              if (chunkStart == contiguousBytes) {
                contiguousBytes += chunkSizes[ci];
              }
            }
          }
          if (contiguousBytes > 0 && supportsResume) {
            if (await targetFile.exists()) {
              final raf = await targetFile.open(mode: FileMode.writeOnly);
              await raf.truncate(contiguousBytes);
              await raf.close();
            }
            if (await stateFile.exists()) await stateFile.delete();
          } else {
            // Server doesn't support resume or no progress made, start from scratch
            if (await targetFile.exists()) await targetFile.delete();
            if (await stateFile.exists()) await stateFile.delete();
          }

          // Fallback to single-threaded stream download
          await _downloadSingleThreaded(
            url: url,
            punyUrl: punyUrl,
            tempFilePath: currentTempFilePath,
            localFilePath: currentLocalFilePath,
            knownFileSize: resolvedFileSize,
            supportsResume: supportsResume,
            cancelToken: cancelToken,
            onProgress: onProgress,
            speedLimitBytesPerSecond: speedLimitBytesPerSecond,
            activeDownloadCount: activeDownloadCount,
            isolatedDio: isolatedDio,
            isNameAutoGenerated: isNameAutoGenerated,
          );
        }
      }
    } finally {
      _activeDioClients.remove(isolatedDio);
      _dioClientCreationTimes.remove(isolatedDio);
      isolatedDio.close(force: true);
    }
  }

  Future<void> _downloadSingleThreaded({
    required String url,
    required String punyUrl,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    required Dio isolatedDio,
    bool isNameAutoGenerated = false,
  }) async {
    final tempFile = File(tempFilePath);
    await tempFile.parent.create(recursive: true);

    var resumeFrom = 0;
    if (supportsResume && await tempFile.exists()) {
      resumeFrom = await tempFile.length();
    } else if (await tempFile.exists()) {
      await tempFile.delete();
    }

    final headers = <String, dynamic>{};
    if (resumeFrom > 0) {
      headers['Range'] = 'bytes=$resumeFrom-';
    }

    var response = await isolatedDio.get<ResponseBody>(
      punyUrl,
      cancelToken: cancelToken,
      options: Options(
        responseType: ResponseType.stream,
        followRedirects: true,
        headers: headers,
        validateStatus: (_) => true,
      ),
    );

    if (response.statusCode == 403 || response.statusCode == 410) {
      throw DioException(
        requestOptions: RequestOptions(path: punyUrl),
        type: DioExceptionType.badResponse,
        response: response,
        message: 'Server returned status code ${response.statusCode}',
      );
    }

    var actualResumeFrom = resumeFrom;

    if (response.statusCode == 416) {
      if (await tempFile.exists()) {
        await tempFile.delete();
      }
      actualResumeFrom = 0;
      headers.remove('range');
      response = await isolatedDio.get<ResponseBody>(
        punyUrl,
        cancelToken: cancelToken,
        options: Options(
          responseType: ResponseType.stream,
          followRedirects: true,
          headers: headers,
          validateStatus: (_) => true,
        ),
      );
    }

    if (response.statusCode != 200 && response.statusCode != 206) {
      throw DioException(
        requestOptions: RequestOptions(path: punyUrl),
        type: DioExceptionType.badResponse,
        response: response,
        message: 'Server returned status code ${response.statusCode}',
      );
    }

    final isPartialResponse = response.statusCode == 206;
    if (actualResumeFrom > 0 && !isPartialResponse) {
      // Server returned 200 instead of 206 — restart from scratch
      actualResumeFrom = 0;
      if (await tempFile.exists()) {
        await tempFile.delete();
      }
    }

    final acceptRanges = response.headers.value('accept-ranges')?.toLowerCase();
    final serverSupportsResume = isPartialResponse || (acceptRanges == 'bytes');
    final responseName = fileNameFromContentDisposition(response.headers);
    final finalUrlName =
        responseName ?? fileNameFromUrl(response.realUri.toString());

    var totalSize = knownFileSize;
    final contentLength =
        int.tryParse(
          response.headers.value(Headers.contentLengthHeader) ?? '',
        ) ??
        0;
    if (contentLength > 0) {
      final actualSize =
          (isPartialResponse ? actualResumeFrom : 0) + contentLength;
      if (actualSize != totalSize) {
        totalSize = actualSize;
      }
    }

    final sink = tempFile.openWrite(
      mode: actualResumeFrom > 0 ? FileMode.append : FileMode.write,
    );
    final stopwatch = Stopwatch()..start();
    var downloadedThisSession = 0;
    var downloadedTotal = actualResumeFrom;
    final speedSamples = Queue<_SpeedSample>();
    int lastReportTime = 0;
    var throttleBaseMs = 0;

    try {
      final stream = response.data?.stream;
      if (stream == null) {
        throw DioException(
          requestOptions: RequestOptions(path: punyUrl),
          type: DioExceptionType.badResponse,
          message: 'Server returned empty response body.',
        );
      }
      await for (final chunk in stream) {
        if (cancelToken.isCancelled) {
          throw DioException(
            requestOptions: RequestOptions(path: punyUrl),
            type: DioExceptionType.cancel,
            message: 'Download cancelled.',
          );
        }
        try {
          sink.add(chunk);
        } catch (e) {
          debugPrint('[DownloadEngine] Failed to write chunk to sink: $e');
          if (cancelToken.isCancelled) {
            throw DioException(
              requestOptions: RequestOptions(path: punyUrl),
              type: DioExceptionType.cancel,
              message: 'Download cancelled.',
            );
          }
          rethrow;
        }
        downloadedThisSession += chunk.length;
        downloadedTotal += chunk.length;

        final nowMs = stopwatch.elapsedMilliseconds;
        speedSamples.add(_SpeedSample(nowMs, downloadedTotal));

        // Keep samples from the last 3 seconds (3000 ms)
        while (speedSamples.isNotEmpty &&
            nowMs - speedSamples.first.timestampMs > 3000) {
          speedSamples.removeFirst();
        }

        var speed = 0.0;
        if (speedSamples.length > 1) {
          final first = speedSamples.first;
          final elapsedSeconds = (nowMs - first.timestampMs) / 1000.0;
          if (elapsedSeconds > 0) {
            speed = (downloadedTotal - first.bytes) / elapsedSeconds;
          }
        }

        final remaining = totalSize > 0 ? totalSize - downloadedTotal : 0;
        final eta = speed > 0 && remaining > 0
            ? (remaining / speed).round()
            : null;

        final isCompleted = totalSize > 0 && downloadedTotal >= totalSize;
        if (nowMs - lastReportTime >= 250 || isCompleted) {
          lastReportTime = nowMs;
          Future.microtask(() {
            onProgress(
              DownloadProgress(
                downloadedBytes: downloadedTotal,
                fileSize: totalSize,
                speed: speed,
                eta: eta,
                supportsResume: serverSupportsResume,
                fileName: finalUrlName,
              ),
            );
          });
        }

        final limit = speedLimitBytesPerSecond();
        if (limit > 0) {
          final activeCount = activeDownloadCount().clamp(1, 1000);
          final perTaskLimit = limit / activeCount.toDouble();
          final expectedElapsedMs =
              (downloadedThisSession / perTaskLimit * 1000.0).round();
          final actualElapsedMs = stopwatch.elapsedMilliseconds - throttleBaseMs;
          if (expectedElapsedMs > actualElapsedMs) {
            final sleepTimeMs = (expectedElapsedMs - actualElapsedMs).clamp(0, 30000);
            if (sleepTimeMs > 0) {
              await Future<void>.delayed(
                Duration(milliseconds: sleepTimeMs),
              );
            }
          }
          throttleBaseMs = stopwatch.elapsedMilliseconds;
          downloadedThisSession = 0;
        }
      }
    } finally {
      try {
        await sink.flush();
      } catch (e) {
        debugPrint('Single-thread sink flush failed: $e');
      }
      try {
        await sink.close();
      } catch (e) {
        debugPrint('Single-thread sink close failed: $e');
      }
    }

    // Always publish the final on-disk size and resolved filename. Very fast
    // or chunked responses may otherwise finish before the throttled progress
    // callback emits a useful final state.
    final actualFileSize = await tempFile.length();
    Future.microtask(() {
      onProgress(
        DownloadProgress(
          downloadedBytes: actualFileSize,
          fileSize: totalSize > 0 ? totalSize : actualFileSize,
          speed: 0.0,
          eta: null,
          supportsResume: serverSupportsResume,
          fileName: finalUrlName,
        ),
      );
    });

    if (totalSize > 0 && actualFileSize != totalSize) {
      // A non-zero but wrong-size file is incomplete/corrupt — fail loudly
      // instead of delivering a truncated download to the user.
      throw Exception(
        'Download integrity check failed: expected $totalSize bytes, got $actualFileSize bytes.',
      );
    }

    final saveDir = File(localFilePath).parent.path;
    final finalLocalFilePath = isNameAutoGenerated
        ? p.join(saveDir, safeFileName(finalUrlName))
        : localFilePath;

    await File(finalLocalFilePath).parent.create(recursive: true);
    if (finalLocalFilePath != tempFile.path) {
      if (await File(finalLocalFilePath).exists()) {
        await File(finalLocalFilePath).delete();
      }
      try {
        await tempFile.rename(finalLocalFilePath);
      } catch (e) {
        debugPrint('File rename failed (cross-device?), using copy fallback: $e');
        // Fallback for cross-device/cross-filesystem move
        await tempFile.copy(finalLocalFilePath);
        final copiedLen = await File(finalLocalFilePath).length();
        final origLen = await tempFile.length();
        if (copiedLen == origLen) {
          await tempFile.delete();
        } else {
          throw Exception('File copy failed on fallback rename.');
        }
      }
    }

    final stateFile = File('$tempFilePath.dmxstate');
    if (await stateFile.exists()) {
      await stateFile.delete();
    }
  }

  String buildLocalFilePath(String directory, String fileName) {
    return p.join(directory, safeFileName(fileName));
  }

  String buildTempFilePath(String directory, String fileName) {
    return p.join(directory, '${safeFileName(fileName)}.dmxpart');
  }

  void _validateContentRange(
    String? value, {
    required int expectedStart,
    required int expectedEnd,
    required int expectedTotal,
  }) {
    final match = RegExp(
      r'^bytes\s+(\d+)-(\d+)/(\d+|\*)$',
    ).firstMatch(value?.trim() ?? '');
    final start = int.tryParse(match?.group(1) ?? '');
    final end = int.tryParse(match?.group(2) ?? '');
    final totalText = match?.group(3);
    final total = totalText == null || totalText == '*'
        ? null
        : int.tryParse(totalText);

    if (start != expectedStart ||
        end != expectedEnd ||
        (expectedTotal > 0 && total != null && total != expectedTotal)) {
      throw DioException(
        requestOptions: RequestOptions(path: ''),
        type: DioExceptionType.badResponse,
        message: 'Invalid Content-Range response: $value. '
            'Expected start: $expectedStart, got start: $start. '
            'Got end: $end, expected end: $expectedEnd. '
            'Got total: $total, expected total: $expectedTotal.',
      );
    }
  }

  void close() {
    _cleanupTimer?.cancel();
    _cleanupTimer = null;
    for (final token in List<CancelToken>.from(_activeCancelTokens)) {
      try {
        token.cancel('Engine closing');
      } // Safe cleanup: Swallow cancel exception on shutdown.
      catch (_) {}
    }
    _activeCancelTokens.clear();
    _sharedDio.close(force: true);
    for (final client in _activeDioClients) {
      try {
        client.close(force: true);
      } // Safe cleanup: Swallow close exception on shutdown.
      catch (_) {}
    }
    _activeDioClients.clear();
    _dioClientCreationTimes.clear();
    for (final isolate in _activeIsolates) {
      try {
        isolate.kill(priority: Isolate.immediate);
      } // Safe cleanup: Swallow kill exception on shutdown.
      catch (_) {}
    }
    _activeIsolates.clear();
    _activeIsolateCommandPorts.clear();
  }
}

typedef ValueChangedProgress = void Function(DownloadProgress progress);

class _SpeedSample {
  final int timestampMs;
  final int bytes;
  _SpeedSample(this.timestampMs, this.bytes);
}