import 'dart:async';

import 'package:dio/dio.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/download_journal.dart';
import 'package:dmx/core/services/engine/download_progress_handler.dart';
import 'package:dmx/core/services/logging_service.dart';
import 'package:dmx/core/services/metadata_probe_service.dart';
import 'package:dmx/core/services/power_monitor.dart';
import 'package:dmx/core/services/yt_counterpart_coordinator.dart';
import 'package:dmx/core/utils/url_utils.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:flutter/foundation.dart';

/// Orchestrates HTTP multi-threaded downloads, managing mirrors, retries, and YT sync.
/// Task 1.1: Fixes Infinite Mirror Retry Loop.
/// Task 1.2: Specialized Service for HTTP download orchestration.
class HttpDownloadOrchestrator {
  final MetadataProbeService _metadataService;
  final YtCounterpartCoordinator _ytCoordinator;
  final SettingsProvider _settings;

  HttpDownloadOrchestrator(
    this._metadataService,
    this._ytCoordinator,
    this._settings,
  );

  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required DownloadIsolatePool pool,
    int threadCount = 0,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    bool isRetry = false,
  }) async {
    final int defaultCount = _settings.effectiveDefaultThreadCount;
    final int effectiveThreadCount =
        (threadCount > 0 ? threadCount : defaultCount)
            .clamp(1, PowerMonitor.maxAllowedThreads);

    int resolvedFileSize = knownFileSize;
    bool resolvedSupportsResume = supportsResume;
    String? resolvedFileName;

    if (resolvedFileSize == 0 && isNameAutoGenerated) {
      try {
        final meta = await _metadataService.resolveMetadata(
          url: url,
          customUserAgent: customUserAgent,
          referer: referer,
          cookies: cookies,
          oauthToken: oauthToken,
          cancelToken: cancelToken,
        );
        resolvedFileSize = meta.fileSize;
        resolvedSupportsResume = meta.supportsResume;
        resolvedFileName = meta.fileName;
      } catch (e) {
        debugPrint('[HttpOrchestrator] resolveMetadata failed: $e');
      }
    }

    int alreadyOnDisk = 0;
    if (resolvedFileSize > 0) {
      try {
        final state = await StateStore.loadOrCreate(
          tempFilePath,
          url: url,
          threadCount: effectiveThreadCount,
          knownFileSize: resolvedFileSize,
        );
        alreadyOnDisk = state.state.downloadedBytes;
      } catch (e, st) {
        LoggingService.logger('HttpDownloadOrchestrator')
            .warning('Operation failed', e, st);
      }
    }

    final punyUrl = convertIdnToPunycode(url);
    final command = DownloadCommand(
      taskId: taskId,
      url: url,
      punyUrl: punyUrl,
      tempFilePath: tempFilePath,
      localFilePath: localFilePath,
      knownFileSize: resolvedFileSize,
      supportsResume: resolvedSupportsResume,
      threadCount: effectiveThreadCount,
      customUserAgent: customUserAgent,
      referer: referer,
      cookies: cookies,
      oauthToken: oauthToken,
      isNameAutoGenerated:
          resolvedFileName != null ? false : isNameAutoGenerated,
      initialSpeedLimit: 0,
      initialActiveCount: 1,
      mirrorUrls: mirrorUrls,
      adaptiveThreads: adaptiveThreads,
      speedLimitKbps: speedLimitKbps,
      resolvedFileName: resolvedFileName,
      ytStreamKind: ytStreamKind,
      ytCounterpartSize: ytCounterpartSize,
      ytCounterpartDownloadedBytes: ytCounterpartDownloadedBytes,
      ytCounterpartTaskId: _ytCoordinator.getCounterpartId(taskId),
      throttleFactor: PowerMonitor.throttleFactor,
    );

    final progressHandler = DownloadProgressHandler(
      taskId: taskId,
      onProgress: onProgress,
      cancelToken: cancelToken,
      resolvedFileName: resolvedFileName,
      resolvedSupportsResume: resolvedSupportsResume,
      ytStreamKind: ytStreamKind,
      ytCounterpartSize: ytCounterpartSize,
      ytCounterpartDownloadedBytes: ytCounterpartDownloadedBytes,
      isTorrent: false,
      getEffectiveIntervalMs: () => 500, // Throttling interval
      lastDownloadedBytes: alreadyOnDisk,
      lastFileSize: resolvedFileSize,
    );

    final job = pool.submit(command);
    final completer = Completer<void>();

    PauseReason? getStructuredPauseReason() {
      final err = cancelToken.cancelError;
      final r = err?.error ?? err?.message;
      if (r is PauseReason) return r;
      if (r is String) return PauseReason.fromName(r);
      return null;
    }

    if (cancelToken.isCancelled) {
      job.cancel(getStructuredPauseReason());
      throw DioException(
        requestOptions: RequestOptions(path: punyUrl),
        type: DioExceptionType.cancel,
        message: 'Download cancelled',
      );
    }

    unawaited(cancelToken.whenCancel.then((_) {
      if (!completer.isCompleted) {
        job.cancel(getStructuredPauseReason());
        if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: punyUrl),
            type: DioExceptionType.cancel,
            message: 'Download cancelled',
          ),
        );
      }
    }));

    final sub = job.messages.listen((message) {
      switch (message.type) {
        case EngineMessageType.progress:
          final data = message.data;
          int? ytCpOverride;
          bool isCpStale = false;
          if (ytStreamKind != null) {
            final downloaded = (data['downloadedBytes'] as num?)?.toInt() ?? 0;
            _ytCoordinator.updateLiveBytes(taskId, downloaded);
            final cpId = _ytCoordinator.getCounterpartId(taskId);
            if (cpId != null) {
              ytCpOverride = _ytCoordinator.getLiveBytes(cpId);
              isCpStale = _ytCoordinator.isLiveBytesStale(cpId);
            }
          }
          progressHandler.handleWorkerProgress(
            data,
            ytCounterpartDownloadedOverride: ytCpOverride,
            isCounterpartStale: isCpStale,
          );
          break;
        case EngineMessageType.done:
          progressHandler.markDone();
          if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
          if (!completer.isCompleted) completer.complete();
          break;
        case EngineMessageType.error:
          if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
          final errData = message.data;
          if (!completer.isCompleted) {
            completer.completeError(_mapWorkerError(errData, punyUrl));
          }
          break;
        case EngineMessageType.hello:
        case EngineMessageType.idle:
        case EngineMessageType.limits:
        case EngineMessageType.job:
        case EngineMessageType.cancel:
        case EngineMessageType.shutdown:
          break;
      }
    });

    try {
      await completer.future;
    } finally {
      sub.cancel();
      job.dispose();
    }
  }

  Exception _mapWorkerError(Map<String, dynamic> data, String url) {
    final type = data['errorType'] as String? ?? 'uncaught';
    final msg = data['errorMessage'] as String? ?? 'Unknown error';
    final status = (data['errorStatus'] as num?)?.toInt();

    if (type == 'cancel') {
      return DioException(
          requestOptions: RequestOptions(path: url),
          type: DioExceptionType.cancel,
          message: msg);
    }
    if (type == 'badResponse' || (status != null && status >= 400)) {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.badResponse,
        response: Response(
          requestOptions: RequestOptions(path: url),
          statusCode: status ?? 400,
          statusMessage: msg,
        ),
        message: msg,
      );
    }
    if (type == 'connectionTimeout') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.connectionTimeout,
        message: msg,
      );
    }
    if (type == 'receiveTimeout') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.receiveTimeout,
        message: msg,
      );
    }
    if (type == 'sendTimeout') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.sendTimeout,
        message: msg,
      );
    }
    if (type == 'connectionError') {
      return DioException(
        requestOptions: RequestOptions(path: url),
        type: DioExceptionType.connectionError,
        message: msg,
      );
    }
    if (type == 'urlExpired') {
      return UrlExpiredException(msg,
          refreshAllMirrors: data['refreshAllMirrors'] == true);
    }
    if (type == 'diskFull') return const InsufficientStorageException();

    return DioException(
      requestOptions: RequestOptions(path: url),
      type: DioExceptionType.unknown,
      error: msg,
    );
  }
}
