import 'dart:async';
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/power_monitor.dart';
import 'package:dmx/core/services/metadata_probe_service.dart';
import 'package:dmx/core/services/yt_counterpart_coordinator.dart';
import 'package:dmx/core/services/download_progress_handler.dart';
import 'package:dmx/core/services/bandwidth_governor.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:dmx/core/utils/url_utils.dart';
import 'package:path/path.dart' as p;

/// Orchestrates HTTP multi-threaded downloads, managing mirrors, retries, and YT sync.
/// Task 1.1: Fixes Infinite Mirror Retry Loop.
/// Task 1.2: Specialized Service for HTTP download orchestration.
class HttpDownloadOrchestrator {
  final MetadataProbeService _metadataService;
  final YtCounterpartCoordinator _ytCoordinator;
  final SettingsProvider _settings;

  HttpDownloadOrchestrator(
    this._metadataService,
    this._ytCoordinator,
    this._settings,
  );

  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required DownloadIsolatePool pool,
    int threadCount = 0,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    bool isRetry = false,
  }) async {
    final legKey = ytStreamKind != null ? '$taskId::${ytStreamKind.name}' : taskId;
    
    final int defaultCount = _settings.effectiveDefaultThreadCount;
    final int effectiveThreadCount = (threadCount > 0 ? threadCount : defaultCount)
        .clamp(1, PowerMonitor.maxAllowedThreads);

    int resolvedFileSize = knownFileSize;
    bool resolvedSupportsResume = supportsResume;
    String? resolvedFileName;

    if (resolvedFileSize == 0 && isNameAutoGenerated) {
      try {
        final meta = await _metadataService.resolveMetadata(
          url: url,
          customUserAgent: customUserAgent,
          referer: referer,
          cookies: cookies,
          oauthToken: oauthToken,
          cancelToken: cancelToken,
        );
        resolvedFileSize = meta.fileSize;
        resolvedSupportsResume = meta.supportsResume;
        resolvedFileName = meta.fileName;
      } catch (e) {
        debugPrint('[HttpOrchestrator] resolveMetadata failed: $e');
      }
    }

    int alreadyOnDisk = 0;
    if (resolvedFileSize > 0) {
      final saveDir = File(localFilePath).parent.path;
      try {
        final state = await StateStore.loadOrCreate(
          tempFilePath,
          url: url,
          threadCount: effectiveThreadCount,
          knownFileSize: resolvedFileSize,
        );
        alreadyOnDisk = state.state.downloadedBytes;
      } catch (_) {}
      
      final remaining = (resolvedFileSize - alreadyOnDisk).clamp(0, resolvedFileSize);
      if (!await _hasEnoughDiskSpace(saveDir, remaining)) {
        throw const InsufficientStorageException();
      }
    }

    final punyUrl = convertIdnToPunycode(url);
    final command = DownloadCommand(
      taskId: taskId,
      url: url,
      punyUrl: punyUrl,
      tempFilePath: tempFilePath,
      localFilePath: localFilePath,
      knownFileSize: resolvedFileSize,
      supportsResume: resolvedSupportsResume,
      threadCount: effectiveThreadCount,
      customUserAgent: customUserAgent,
      referer: referer,
      cookies: cookies,
      oauthToken: oauthToken,
      isNameAutoGenerated: isNameAutoGenerated,
      initialSpeedLimit: 0, // Will be updated by pool
      initialActiveCount: 1,
      mirrorUrls: mirrorUrls,
      adaptiveThreads: adaptiveThreads,
      speedLimitKbps: speedLimitKbps,
      resolvedFileName: resolvedFileName,
      ytStreamKind: ytStreamKind,
      ytCounterpartSize: ytCounterpartSize,
      ytCounterpartDownloadedBytes: ytCounterpartDownloadedBytes,
      ytCounterpartTaskId: _ytCoordinator.getCounterpartId(taskId),
      throttleFactor: PowerMonitor.throttleFactor,
    );

    final progressHandler = DownloadProgressHandler(
      taskId: taskId,
      onProgress: onProgress,
      cancelToken: cancelToken,
      resolvedFileName: resolvedFileName,
      resolvedSupportsResume: resolvedSupportsResume,
      ytStreamKind: ytStreamKind,
      ytCounterpartSize: ytCounterpartSize,
      ytCounterpartDownloadedBytes: ytCounterpartDownloadedBytes,
      lastDownloadedBytes: alreadyOnDisk,
      lastFileSize: resolvedFileSize,
    );

    final job = pool.submit(command);
    final completer = Completer<void>();
    
    final sub = job.messages.listen((message) {
      switch (message.type) {
        case 'progress':
          final data = message.data;
          if (ytStreamKind != null) {
            final downloaded = (data['downloadedBytes'] as num?)?.toInt() ?? 0;
            _ytCoordinator.updateLiveBytes(taskId, downloaded);
            final cpId = _ytCoordinator.getCounterpartId(taskId);
            if (cpId != null) {
              data['ytCounterpartDownloadedBytes'] = _ytCoordinator.getLiveBytes(cpId);
            }
          }
          progressHandler.handleWorkerProgress(data);
          break;
        case 'done':
          if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
          completer.complete();
          break;
        case 'error':
          if (ytStreamKind != null) _ytCoordinator.unregister(taskId);
          final errData = message.data;
          completer.completeError(_mapWorkerError(errData, punyUrl));
          break;
      }
    });

    try {
      await completer.future;
    } finally {
      sub.cancel();
      job.dispose();
    }
  }

  Exception _mapWorkerError(Map<String, dynamic> data, String url) {
    final type = data['errorType'] as String? ?? 'uncaught';
    final msg = data['errorMessage'] as String? ?? 'Unknown error';
    
    if (type == 'cancel') return DioException(requestOptions: RequestOptions(path: url), type: DioExceptionType.cancel, message: msg);
    if (type == 'urlExpired') return UrlExpiredException(msg, refreshAllMirrors: data['refreshAllMirrors'] == true);
    if (type == 'diskFull') return const InsufficientStorageException();
    
    return DioException(
      requestOptions: RequestOptions(path: url),
      type: DioExceptionType.unknown,
      error: msg,
    );
  }

  Future<bool> _hasEnoughDiskSpace(String savePath, int requiredBytes) async {
    final requiredWithMargin = (requiredBytes * 1.1).toInt();
    final dir = Directory(savePath);
    if (!await dir.exists()) await dir.create(recursive: true);
    // Simplified for now, real implementation would use platform channels or process run
    return true; 
  }
}
