import 'package:flutter/foundation.dart';
import '../../domain/engine_types.dart';
import '../download_journal.dart';

export '../../domain/cycle_state.dart';
export '../../domain/engine_types.dart';
export '../../domain/pause_reason.dart';

/// Typed kinds of engine IPC messages exchanged with the download worker.
///
/// Wire format stays as the string [name] for isolate compatibility; the enum
/// gives compile-time checking on the host side.
enum EngineMessageType {
  progress,
  done,
  error,
  hello,
  idle,
  limits,
  job,
  cancel,
  shutdown,
  ack;

  static EngineMessageType? fromWire(Object? value) {
    if (value is! String) return null;
    for (final t in EngineMessageType.values) {
      if (t.name == value) return t;
    }
    return null;
  }
}

enum MergeFailureKind {
  missingBinary,
  formatMismatch,
  diskFull,
  processCrash,
  incompleteInput,
  unknown,
}

@immutable
class ChunkResult {
  const ChunkResult({
    required this.chunk,
    required this.success,
    this.error,
    this.stackTrace,
    this.attempts = 1,
  });

  final ChunkState chunk;
  final bool success;
  final Object? error;
  final StackTrace? stackTrace;
  final int attempts;
}

@immutable
class DownloadCommand {
  const DownloadCommand({
    required this.taskId,
    required this.url,
    required this.punyUrl,
    required this.tempFilePath,
    required this.localFilePath,
    required this.knownFileSize,
    required this.supportsResume,
    required this.threadCount,
    this.isNameAutoGenerated = false,
    this.adaptiveThreads = false,
    int? speedLimit,
    int? activeCount,
    int initialSpeedLimit = 0,
    int initialActiveCount = 1,
    int speedLimitKbps = 0,
    this.customUserAgent,
    this.referer,
    this.cookies,
    this.oauthToken,
    this.mirrorUrls,
    this.resolvedFileName,
    this.ytStreamKind,
    this.ytCounterpartSize,
    this.ytCounterpartDownloadedBytes,
    this.ytCounterpartTaskId,
    this.throttleFactor = 1.0,
    this.urlExpiresHint = false,
    this.authUsername,
    this.authPassword,
    this.customHeaders,
    this.httpsOnly = false,
    this.proxyType,
    this.proxyHost,
    this.proxyPort,
    this.proxyUsername,
    this.proxyPassword,
    this.diskWriteBatching = true,
    this.stalledTimeoutMinutes = 5,
    this.resumeIntegrityCheck = true,
    this.initialDownloadedBytes = 0,
  })  : initialSpeedLimit = speedLimit ?? initialSpeedLimit,
        initialActiveCount = activeCount ?? initialActiveCount,
        speedLimitKbps = speedLimit ?? speedLimitKbps;

  final double throttleFactor;
  final String taskId;
  final String url;
  final String punyUrl;
  final String tempFilePath;
  final String localFilePath;
  final int knownFileSize;
  final bool supportsResume;
  final int threadCount;
  final String? customUserAgent;
  final String? referer;
  final String? cookies;
  final String? oauthToken;
  final bool isNameAutoGenerated;
  final int initialSpeedLimit;
  final int initialActiveCount;
  final int speedLimitKbps;
  final List<String>? mirrorUrls;
  final bool adaptiveThreads;
  final String? resolvedFileName;
  final YtStreamKind? ytStreamKind;
  final int? ytCounterpartSize;
  final int? ytCounterpartDownloadedBytes;
  final String? ytCounterpartTaskId;
  final bool urlExpiresHint;
  // Per-download HTTP auth + custom headers (Plan 06 6.2), and per-session
  // network policy (proxy + HTTPS-only, Plan 06 6.3 / Plan 05 S3) threaded to
  // the worker isolate, which cannot read SettingsProvider.instance.
  final String? authUsername;
  final String? authPassword;
  final Map<String, String>? customHeaders;
  final bool httpsOnly;
  final String? proxyType; // 'http' | 'socks5' | null
  final String? proxyHost;
  final int? proxyPort;
  final String? proxyUsername;
  final String? proxyPassword;
  // 7.3-writer: batched (paced) disk flushing vs a tighter cadence.
  final bool diskWriteBatching;
  // FIX(P2.5): Thread settings to the worker isolate which cannot access
  // SettingsProvider.instance.
  final int stalledTimeoutMinutes;
  final bool resumeIntegrityCheck;
  final int initialDownloadedBytes;

  Map<String, dynamic> toMap() => {
        'taskId': taskId,
        'url': url,
        'punyUrl': punyUrl,
        'tempFilePath': tempFilePath,
        'localFilePath': localFilePath,
        'knownFileSize': knownFileSize,
        'supportsResume': supportsResume,
        'initialDownloadedBytes': initialDownloadedBytes,
        'threadCount': threadCount,
        'customUserAgent': customUserAgent,
        'referer': referer,
        'cookies': cookies,
        'oauthToken': oauthToken,
        'isNameAutoGenerated': isNameAutoGenerated,
        'initialSpeedLimit': initialSpeedLimit,
        'initialActiveCount': initialActiveCount,
        'speedLimitKbps': speedLimitKbps,
        'mirrorUrls': mirrorUrls,
        'adaptiveThreads': adaptiveThreads,
        'resolvedFileName': resolvedFileName,
        if (ytStreamKind != null) 'ytStreamKind': ytStreamKind!.name,
        if (ytCounterpartSize != null) 'ytCounterpartSize': ytCounterpartSize,
        if (ytCounterpartDownloadedBytes != null)
          'ytCounterpartDownloadedBytes': ytCounterpartDownloadedBytes,
        if (ytCounterpartTaskId != null)
          'ytCounterpartTaskId': ytCounterpartTaskId,
        'throttleFactor': throttleFactor,
        'urlExpiresHint': urlExpiresHint,
        'authUsername': authUsername,
        'authPassword': authPassword,
        if (customHeaders != null) 'customHeaders': customHeaders,
        'httpsOnly': httpsOnly,
        'proxyType': proxyType,
        'proxyHost': proxyHost,
        'proxyPort': proxyPort,
        'proxyUsername': proxyUsername,
        'proxyPassword': proxyPassword,
        'diskWriteBatching': diskWriteBatching,
        'stalledTimeoutMinutes': stalledTimeoutMinutes,
        'resumeIntegrityCheck': resumeIntegrityCheck,
      };

  factory DownloadCommand.fromMap(Map<String, dynamic> m) => DownloadCommand(
        taskId: m['taskId'] as String,
        url: m['url'] as String,
        punyUrl: m['punyUrl'] as String,
        tempFilePath: m['tempFilePath'] as String,
        localFilePath: m['localFilePath'] as String,
        knownFileSize: (m['knownFileSize'] as num?)?.toInt() ?? 0,
        supportsResume: m['supportsResume'] as bool? ?? false,
        threadCount: (m['threadCount'] as num?)?.toInt() ?? 1,
        customUserAgent: m['customUserAgent'] as String?,
        referer: m['referer'] as String?,
        cookies: m['cookies'] as String?,
        oauthToken: m['oauthToken'] as String?,
        isNameAutoGenerated: m['isNameAutoGenerated'] as bool? ?? false,
        initialSpeedLimit: (m['initialSpeedLimit'] as num?)?.toInt() ?? 0,
        initialActiveCount: (m['initialActiveCount'] as num?)?.toInt() ?? 1,
        speedLimitKbps: (m['speedLimitKbps'] as num?)?.toInt() ?? 0,
        mirrorUrls: (m['mirrorUrls'] as List?)?.cast<String>(),
        adaptiveThreads: m['adaptiveThreads'] as bool? ?? false,
        resolvedFileName: m['resolvedFileName'] as String?,
        throttleFactor: (m['throttleFactor'] as num?)?.toDouble() ?? 1.0,
        urlExpiresHint: m['urlExpiresHint'] as bool? ?? false,
        ytStreamKind: m['ytStreamKind'] != null
            ? YtStreamKind.values.firstWhere(
                (k) => k.name == m['ytStreamKind'],
                orElse: () => YtStreamKind.combined,
              )
            : null,
        ytCounterpartSize: (m['ytCounterpartSize'] as num?)?.toInt(),
        ytCounterpartDownloadedBytes:
            (m['ytCounterpartDownloadedBytes'] as num?)?.toInt(),
        ytCounterpartTaskId: m['ytCounterpartTaskId'] as String?,
        authUsername: m['authUsername'] as String?,
        authPassword: m['authPassword'] as String?,
        customHeaders: (m['customHeaders'] as Map?)
            ?.map((k, v) => MapEntry(k.toString(), v.toString())),
        httpsOnly: m['httpsOnly'] as bool? ?? false,
        proxyType: m['proxyType'] as String?,
        proxyHost: m['proxyHost'] as String?,
        proxyPort: (m['proxyPort'] as num?)?.toInt(),
        proxyUsername: m['proxyUsername'] as String?,
        proxyPassword: m['proxyPassword'] as String?,
        diskWriteBatching: m['diskWriteBatching'] as bool? ?? true,
        stalledTimeoutMinutes:
            (m['stalledTimeoutMinutes'] as num?)?.toInt() ?? 5,
        resumeIntegrityCheck: m['resumeIntegrityCheck'] as bool? ?? true,
      );
}

/// A single (timestamp, bytes) pair captured for speed measurement.
class SpeedSample {
  final int timestampMs;
  final int bytes;
  SpeedSample(this.timestampMs, this.bytes);
}
