import 'dart:async';

import 'package:dio/dio.dart';
import 'package:dmx/core/services/database_service.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/features/downloads/models/download_task.dart';
import 'package:dmx/features/downloads/provider/download_provider.dart';
import 'package:dmx/features/settings/provider/settings_provider.dart';
import 'package:drift/drift.dart' as drift;
import 'package:flutter_test/flutter_test.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../helpers/fake_services.dart';
import '../../helpers/test_helpers.dart';

/// Local fake engine that resolves metadata and keeps downloads pending so the
/// provider sees an active cancel token and retains DownloadStatus.downloading.
class ActiveFakeEngine extends DownloadEngine {
  final List<String> startedUrls = [];

  ActiveFakeEngine() : super(enableCleanupTimer: false);

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    CancelToken? cancelToken,
  }) async {
    return DownloadMetadata(
      fileName: requestedFileName ?? 'merge.bin',
      category: 'Compressed',
      fileSize: 104857600,
      supportsResume: true,
    );
  }

  @override
  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 1,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    bool isRetry = false,
    int? metadataTimeoutSeconds,
  }) {
    startedUrls.add(url);
    final completer = Completer<void>();
    cancelToken.whenCancel.then((_) {
      if (!completer.isCompleted) {
        completer.completeError(
          DioException(
            requestOptions: RequestOptions(path: url),
            type: DioExceptionType.cancel,
          ),
        );
      }
    });
    return completer.future;
  }
}

class GrantedPermissionService extends FakePermissionService {
  @override
  Future<String> defaultDownloadDirectory() async => 'build/test_merge_downloads';

  @override
  Future<bool> ensureStorageAccess() async => true;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('DownloadProvider merge-aware task updates (H8)', () {
    late DownloadProvider provider;
    late DatabaseService database;
    late SettingsProvider settings;

    setUpAll(() {
      drift.driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
      Hive.init('build/test_provider_merge');
    });

    tearDown(() async {
      if (Hive.isBoxOpen(DatabaseService.downloadsBoxName)) {
        await Hive.box<dynamic>(DatabaseService.downloadsBoxName).clear();
      }
    });

    Future<void> buildLoadedProvider(List<DownloadTask> tasks) async {
      setupTestPluginMocks();
      SharedPreferences.setMockInitialValues({});
      database = DatabaseService.forSubclass();
      await database.init(testPath: 'build/test_provider_merge');
      for (final task in tasks) {
        await database.saveTask(task);
      }
      settings = SettingsProvider();
      await settings.load();
      provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: ActiveFakeEngine(),
        permissionService: GrantedPermissionService(),
        enableBackgroundTimers: false,
      );
      addTearDown(() => provider.dispose());
      await provider.load(pauseOrphanDownloads: false);
    }

    test('completed tasks are immutable against stale incoming updates',
        () async {
      await buildLoadedProvider([
        createTestTask(
          id: 'merge-2',
          fileName: 'done.bin',
          status: DownloadStatus.completed,
          progress: 1.0,
          fileSize: 100,
          downloadedBytes: 100,
        ),
      ]);

      // A stale incoming snapshot reports older progress with a paused status.
      await provider.setTaskState(provider.taskById('merge-2')!
          .copyWith(status: DownloadStatus.paused, downloadedBytes: 50));

      final task = provider.taskById('merge-2');
      expect(task, isNotNull);
      expect(task!.status, DownloadStatus.completed);
      expect(task.downloadedBytes, 100);
    });

    test('pausedByUser prevents automatic un-pause', () async {
      await buildLoadedProvider([
        createTestTask(
          id: 'merge-3',
          fileName: 'paused.bin',
          status: DownloadStatus.paused,
          progress: 0.5,
        ).copyWith(pausedByUser: true),
      ]);

      // Incoming snapshot from the engine with a stale "downloading" status.
      await provider
          .setTaskState(provider.taskById('merge-3')!
              .copyWith(status: DownloadStatus.downloading));

      final task = provider.taskById('merge-3');
      expect(task, isNotNull);
      expect(task!.status, DownloadStatus.paused);
      expect(task.pausedByUser, isTrue);
    });

    test('stale downloading snapshot cannot overwrite a failed task', () async {
      await buildLoadedProvider([
        createTestTask(
          id: 'merge-4',
          fileName: 'failed.bin',
          status: DownloadStatus.failed,
          progress: 0.2,
          errorMessage: 'Timeout',
        ),
      ]);

      await provider.setTaskState(provider.taskById('merge-4')!
          .copyWith(status: DownloadStatus.downloading));

      final task = provider.taskById('merge-4');
      expect(task, isNotNull);
      expect(task!.status, DownloadStatus.failed);
    });

    test('active download: progress ticks keep the larger downloadedBytes',
        () async {
      setupTestPluginMocks();
      SharedPreferences.setMockInitialValues({});
      database = DatabaseService.forSubclass();
      await database.init(testPath: 'build/test_provider_merge');
      settings = SettingsProvider();
      await settings.load();
      final engine = ActiveFakeEngine();
      provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: engine,
        permissionService: GrantedPermissionService(),
        enableBackgroundTimers: false,
      );
      addTearDown(() => provider.dispose());

      await provider.addDownload(
        name: 'merge.bin',
        url: 'https://example.com/merge.bin',
        size: 104857600,
        category: 'Compressed',
        savePath: 'build/test_merge_downloads',
      );
      await pumpEventQueue();

      final live = provider.tasks
          .singleWhere((t) => t.fileName == 'merge.bin');
      expect(live.status, DownloadStatus.downloading);

      // A stale tick reports fewer bytes than the live in-memory task.
      await provider.setTaskState(
          live.copyWith(downloadedBytes: 1024 * 1024));
      await pumpEventQueue();

      final task = provider.taskById(live.id);
      expect(task, isNotNull);
      expect(task!.downloadedBytes,
          greaterThanOrEqualTo(live.downloadedBytes));
      expect(task.status, DownloadStatus.downloading);
    });

    test('active download: downloadedBytes larger than fileSize is clamped (H-6)',
        () async {
      setupTestPluginMocks();
      SharedPreferences.setMockInitialValues({});
      database = DatabaseService.forSubclass();
      await database.init(testPath: 'build/test_provider_merge');
      settings = SettingsProvider();
      await settings.load();
      final engine = ActiveFakeEngine();
      provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: engine,
        permissionService: GrantedPermissionService(),
        enableBackgroundTimers: false,
      );
      addTearDown(() => provider.dispose());

      await provider.addDownload(
        name: 'merge.bin',
        url: 'https://example.com/merge.bin',
        size: 104857600,
        category: 'Compressed',
        savePath: 'build/test_merge_downloads',
      );
      await pumpEventQueue();

      final live = provider.tasks.singleWhere((t) => t.fileName == 'merge.bin');
      await provider.setTaskState(
          live.copyWith(downloadedBytes: live.fileSize + 4096));
      await pumpEventQueue();

      final task = provider.taskById(live.id);
      expect(task, isNotNull);
      expect(task!.downloadedBytes, lessThanOrEqualTo(task.fileSize));
    });

    test('active download: status updates are applied normally', () async {
      setupTestPluginMocks();
      SharedPreferences.setMockInitialValues({});
      database = DatabaseService.forSubclass();
      await database.init(testPath: 'build/test_provider_merge');
      settings = SettingsProvider();
      await settings.load();
      final engine = ActiveFakeEngine();
      provider = DownloadProvider(
        databaseService: database,
        settingsProvider: settings,
        downloadEngine: engine,
        permissionService: GrantedPermissionService(),
        enableBackgroundTimers: false,
      );
      addTearDown(() => provider.dispose());

      await provider.addDownload(
        name: 'merge.bin',
        url: 'https://example.com/merge.bin',
        size: 104857600,
        category: 'Compressed',
        savePath: 'build/test_merge_downloads',
      );
      await pumpEventQueue();

      final live = provider.tasks.singleWhere((t) => t.fileName == 'merge.bin');
      await provider.setTaskState(
          live.copyWith(statusMessage: 'Connecting...'));
      await pumpEventQueue();

      final task = provider.taskById(live.id);
      expect(task, isNotNull);
      expect(task!.statusMessage, 'Connecting...');
    });
  });
}
