import 'dart:async';
import 'dart:io';

import 'package:battery_plus/battery_plus.dart';
import 'package:dmx/core/services/download_engine.dart';
import 'package:dmx/core/services/power_monitor.dart';
import 'package:flutter_test/flutter_test.dart';

var _counter = 0;

/// Submits [command] and resolves with the URL once the job completes.
Future<String> _runJob(
  DownloadIsolatePool pool,
  String url, {
  int priority = 0,
}) {
  final completer = Completer<String>();
  final n = _counter++;
  final command = DownloadCommand(
    url: url,
    punyUrl: url,
    tempFilePath:
        '${Directory.systemTemp.path}/dmx_pool_${n}_${DateTime.now().microsecondsSinceEpoch}.tmp',
    localFilePath:
        '${Directory.systemTemp.path}/dmx_pool_out_${n}_${DateTime.now().microsecondsSinceEpoch}.bin',
    knownFileSize: 10,
    supportsResume: false,
    threadCount: 1,
    isNameAutoGenerated: false,
    speedLimit: 0,
    activeCount: 1,
    taskId: 'task_$n',
  );

  final job = pool.submit(command, priority: priority);
  job.messages.listen((msg) {
    if (msg.type == EngineMessageType.done ||
        msg.type == EngineMessageType.error) {
      if (!completer.isCompleted) completer.complete(url);
    }
  });
  completer.future.whenComplete(job.dispose);
  return completer.future;
}

void main() {
  test('pool drain completes within timeout and closes all workers', () async {
    final pool = DownloadIsolatePool(size: 2);
    await pool.init();
    await pool.drain(timeout: const Duration(seconds: 15));

    // All workers are gone, so submitting must fail.
    expect(
      () => pool.submit(
        DownloadCommand(
          url: 'http://localhost:1/none',
          punyUrl: 'http://localhost:1/none',
          tempFilePath: '${Directory.systemTemp.path}/x.tmp',
          localFilePath: '${Directory.systemTemp.path}/x.bin',
          knownFileSize: 10,
          supportsResume: false,
          threadCount: 1,
          isNameAutoGenerated: false,
          speedLimit: 0,
          activeCount: 1,
          taskId: 'task_none',
        ),
      ),
      throwsA(isA<IsolateSpawnTimeoutException>()),
    );
  });

  test('priority queue processes higher priority jobs first', () async {
    // A single-worker pool admits up to 2 concurrent jobs; the rest queue in
    // priority order. Slower jobs keep the worker busy so queued jobs run in
    // priority order as slots free up.
    final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
    final port = server.port;

    server.listen((HttpRequest request) async {
      final path = request.uri.path;
      if (path.startsWith('/slow')) {
        // Keep the first two slots busy so later jobs queue.
        await Future<void>.delayed(const Duration(milliseconds: 500));
      }
      request.response
        ..statusCode = 200
        ..headers.set('content-length', '10')
        ..add(List<int>.generate(10, (i) => i));
      await request.response.close();
    });

    final pool = DownloadIsolatePool(size: 1);
    await pool.init();

    // Fill the worker to capacity with slow jobs first.
    final slow1 = _runJob(pool, 'http://localhost:$port/slow1');
    final slow2 = _runJob(pool, 'http://localhost:$port/slow2');

    // These queue up with distinct priorities (submitted in random order).
    await Future<void>.delayed(const Duration(milliseconds: 100));
    final low = _runJob(pool, 'http://localhost:$port/fast1', priority: 1);
    final high = _runJob(pool, 'http://localhost:$port/fast2', priority: 5);
    final mid = _runJob(pool, 'http://localhost:$port/fast3', priority: 3);

    final results = await Future.wait([slow1, slow2, high, mid, low]);

    // The three queued jobs must complete in priority order: fast2 (5),
    // fast3 (3), then fast1 (1), after the two slow jobs free up slots.
    final fastOrder = results
        .where((r) => r.contains('/fast'))
        .map((r) => r.split('/').last)
        .toList();
    expect(fastOrder, ['fast2', 'fast3', 'fast1']);

    await pool.shutdown();
    await server.close();
  });

  test('powerAware pool size reduces at battery 15% and restores at 50%',
      () async {
    final pool = DownloadIsolatePool(size: 4, powerAware: true);
    await pool.init();
    expect(pool.workerCount, equals(4));

    PowerMonitor.setBatteryStateForTesting(BatteryState.discharging);
    PowerMonitor.setBatteryLevelForTesting(15);
    expect(pool.workerCount, equals(1));

    PowerMonitor.setBatteryLevelForTesting(50);
    // Note: restoring size doesn't automatically re-spawn killed isolates until needed or initialized,
    // but power status check recovers target capacity configuration
    expect(pool.maxJobsPerWorker, equals(2));

    await pool.shutdown();
    PowerMonitor.setBatteryLevelForTesting(100);
    PowerMonitor.setBatteryStateForTesting(BatteryState.unknown);
  });

  test('memory pressure reduces pool size', () async {
    final pool = DownloadIsolatePool(size: 4);
    await pool.init();
    expect(pool.workerCount, equals(4));

    pool.onMemoryPressure();
    expect(pool.workerCount, lessThan(4));

    await pool.shutdown();
  });

  test(
      'speed-limited download completes without hanging '
      '(regression: _cancellableDelay awaited whenCancel)', () async {
    // A low speed limit forces the governor to sleep between writes, which
    // previously hung forever because `_cancellableDelay` awaited the
    // cancel-token's `whenCancel` future that only resolves on cancel.
    const fileSize = 64 * 1024;
    final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
    final port = server.port;

    server.listen((HttpRequest request) async {
      request.response
        ..statusCode = 200
        ..headers.set('content-length', '$fileSize');
      final chunk = List<int>.generate(1024, (i) => i % 251);
      for (var sent = 0; sent < fileSize; sent += chunk.length) {
        request.response.add(chunk);
      }
      await request.response.close();
    });

    final pool = DownloadIsolatePool(size: 1);
    await pool.init();

    final n = _counter++;
    final command = DownloadCommand(
      url: 'http://localhost:$port/speed_limited.bin',
      punyUrl: 'http://localhost:$port/speed_limited.bin',
      tempFilePath:
          '${Directory.systemTemp.path}/dmx_pool_${n}_${DateTime.now().microsecondsSinceEpoch}.tmp',
      localFilePath:
          '${Directory.systemTemp.path}/dmx_pool_out_${n}_${DateTime.now().microsecondsSinceEpoch}.bin',
      knownFileSize: fileSize,
      supportsResume: false,
      threadCount: 1,
      isNameAutoGenerated: false,
      speedLimitKbps: 256, // 32 KB/s -> several governor sleeps over 64 KB
      activeCount: 1,
      taskId: 'task_speed_$n',
    );

    final completer = Completer<void>();
    final job = pool.submit(command);
    job.messages.listen((msg) {
      if (msg.type == EngineMessageType.done ||
          msg.type == EngineMessageType.error) {
        if (!completer.isCompleted) completer.complete();
      }
    });

    await completer.future
        .timeout(const Duration(seconds: 15), onTimeout: () {});
    expect(completer.isCompleted, isTrue,
        reason: 'speed-limited download must not hang');

    job.dispose();
    await pool.shutdown();
    await server.close();
  });
}
