import 'package:dio/dio.dart';
import 'package:dmx/core/domain/download_request.dart';
import 'package:dmx/core/domain/engine_types.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('DownloadRequest Value Object (P1-1)', () {
    test('instantiates with required and default parameters', () {
      final cancelToken = CancelToken();
      final request = DownloadRequest(
        taskId: 'task-123',
        url: 'https://example.com/file.zip',
        tempFilePath: '/tmp/file.zip.part',
        localFilePath: '/downloads/file.zip',
        knownFileSize: 1024 * 1024 * 10,
        supportsResume: true,
        cancelToken: cancelToken,
        onProgress: (_) {},
        speedLimitBytesPerSecond: () => 0,
        activeDownloadCount: () => 1,
      );

      expect(request.taskId, 'task-123');
      expect(request.url, 'https://example.com/file.zip');
      expect(request.knownFileSize, 1024 * 1024 * 10);
      expect(request.supportsResume, isTrue);
      expect(request.threadCount, 0);
      expect(request.isNameAutoGenerated, isFalse);
      expect(request.isRetry, isFalse);
      expect(request.speedLimitKbps, 0);
    });

    test('copyWith updates specified fields while preserving others', () {
      final cancelToken = CancelToken();
      final request = DownloadRequest(
        taskId: 'task-123',
        url: 'https://example.com/file.zip',
        tempFilePath: '/tmp/file.zip.part',
        localFilePath: '/downloads/file.zip',
        knownFileSize: 1000,
        supportsResume: true,
        cancelToken: cancelToken,
        onProgress: (_) {},
        speedLimitBytesPerSecond: () => 0,
        activeDownloadCount: () => 1,
      );

      final updated = request.copyWith(
        threadCount: 8,
        isRetry: true,
        customUserAgent: 'DMX/2.0',
      );

      expect(updated.taskId, 'task-123');
      expect(updated.threadCount, 8);
      expect(updated.isRetry, isTrue);
      expect(updated.customUserAgent, 'DMX/2.0');
      expect(updated.knownFileSize, 1000);
    });
  });
}
