import 'dart:async';
import 'package:dio/dio.dart';
import 'package:dmx/core/domain/engine_types.dart';
import 'package:dmx/core/interfaces/i_download_engine.dart';
import 'package:dmx/core/services/engine/engine_models.dart';

/// Scriptable test fake for [IDownloadEngine] satisfying Phase 0 test harness requirements.
class FakeIDownloadEngine implements IDownloadEngine {
  final List<DownloadRequest> recordedRequests = [];
  final List<String> recordedDownloadTaskIds = [];
  final List<String> pausedTasks = [];
  final List<String> forceCancelledTasks = [];
  final Map<String, CancelToken> activeCancelTokens = {};
  final Map<String, Completer<void>> pendingDownloads = {};

  bool simulateInstantCompletion = false;
  bool shouldThrowOnDownload = false;
  Object? downloadErrorToThrow;
  Duration simulatedDownloadDelay = Duration.zero;
  int simulatedChunkCount = 4;
  int simulatedFileSize = 10 * 1024 * 1024; // 10MB
  bool simulatedHasEnoughSpace = true;
  DownloadMetadata? defaultMetadata;

  @override
  Future<void> downloadRequest(DownloadRequest request) async {
    recordedRequests.add(request);
    await download(
      taskId: request.taskId,
      url: request.url,
      tempFilePath: request.tempFilePath,
      localFilePath: request.localFilePath,
      knownFileSize: request.knownFileSize,
      supportsResume: request.supportsResume,
      cancelToken: request.cancelToken,
      onProgress: request.onProgress,
      speedLimitBytesPerSecond: request.speedLimitBytesPerSecond,
      activeDownloadCount: request.activeDownloadCount,
      threadCount: request.threadCount,
      customUserAgent: request.customUserAgent,
      referer: request.referer,
      cookies: request.cookies,
      oauthToken: request.oauthToken,
      getTorrentFiles: request.getTorrentFiles,
      torrentId: request.torrentId,
      isNameAutoGenerated: request.isNameAutoGenerated,
      mirrorUrls: request.mirrorUrls,
      adaptiveThreads: request.adaptiveThreads,
      speedLimitKbps: request.speedLimitKbps,
      ytStreamKind: request.ytStreamKind,
      ytCounterpartSize: request.ytCounterpartSize,
      ytCounterpartDownloadedBytes: request.ytCounterpartDownloadedBytes,
      isRetry: request.isRetry,
      metadataTimeoutSeconds: request.metadataTimeoutSeconds,
    );
  }

  @override
  Future<void> download({
    required String taskId,
    required String url,
    required String tempFilePath,
    required String localFilePath,
    required int knownFileSize,
    required bool supportsResume,
    required CancelToken cancelToken,
    required ValueChangedProgress onProgress,
    required int Function() speedLimitBytesPerSecond,
    required int Function() activeDownloadCount,
    int threadCount = 0,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    List<Map<String, dynamic>>? Function()? getTorrentFiles,
    int? torrentId,
    bool isNameAutoGenerated = false,
    List<String>? mirrorUrls,
    bool adaptiveThreads = false,
    int speedLimitKbps = 0,
    YtStreamKind? ytStreamKind,
    int? ytCounterpartSize,
    int? ytCounterpartDownloadedBytes,
    bool isRetry = false,
    int? metadataTimeoutSeconds,
  }) async {
    recordedDownloadTaskIds.add(taskId);
    activeCancelTokens[taskId] = cancelToken;
    final completer = Completer<void>();
    pendingDownloads[taskId] = completer;

    if (shouldThrowOnDownload) {
      throw downloadErrorToThrow ?? Exception('Simulated download failure for $taskId');
    }

    final totalBytes = knownFileSize > 0 ? knownFileSize : simulatedFileSize;

    if (simulatedDownloadDelay > Duration.zero) {
      const steps = 10;
      final stepDelay = simulatedDownloadDelay ~/ steps;
      for (var i = 1; i <= steps; i++) {
        if (cancelToken.isCancelled) {
          throw DioException(
            requestOptions: RequestOptions(path: url),
            type: DioExceptionType.cancel,
            message: 'Task $taskId cancelled',
          );
        }
        await Future.delayed(stepDelay);
        final downloaded = (totalBytes * (i / steps)).round();
        onProgress(DownloadProgress(
          downloadedBytes: downloaded,
          fileSize: totalBytes,
          speed: (totalBytes / (simulatedDownloadDelay.inMilliseconds / 1000)).clamp(0, 100000000),
          eta: (simulatedDownloadDelay.inMilliseconds / 1000).round(),
          chunks: List.filled(simulatedChunkCount, i / steps),
        ));
      }
    } else if (simulateInstantCompletion) {
      onProgress(DownloadProgress(
        downloadedBytes: totalBytes,
        fileSize: totalBytes,
        speed: 1024 * 1024 * 5,
        eta: 0,
        chunks: List.filled(simulatedChunkCount, 1.0),
      ));
    }

    completer.complete();
  }

  /// Helper to simulate progress emission externally for a running task
  void emitProgress(
    String taskId,
    ValueChangedProgress onProgress, {
    required int downloadedBytes,
    required int totalBytes,
    double speed = 1024 * 1024,
    int? eta,
    List<double>? chunks,
  }) {
    final progressVal = totalBytes > 0 ? (downloadedBytes / totalBytes).clamp(0.0, 1.0) : 0.0;
    onProgress(DownloadProgress(
      downloadedBytes: downloadedBytes,
      fileSize: totalBytes,
      speed: speed,
      eta: eta,
      chunks: chunks ?? List.filled(simulatedChunkCount, progressVal),
    ));
  }

  @override
  Future<DownloadMetadata> resolveMetadata({
    required String url,
    String? requestedFileName,
    String? customUserAgent,
    String? referer,
    String? cookies,
    String? oauthToken,
    CancelToken? cancelToken,
  }) async {
    if (defaultMetadata != null) {
      return defaultMetadata!;
    }
    return DownloadMetadata(
      fileName: requestedFileName ?? url.split('/').last.split('?').first,
      category: 'other',
      fileSize: simulatedFileSize,
      supportsResume: true,
      etag: '"test-etag-123"',
    );
  }

  @override
  void forceCancelJob(String taskId) {
    forceCancelledTasks.add(taskId);
    final token = activeCancelTokens[taskId];
    if (token != null && !token.isCancelled) {
      token.cancel('Force cancelled by test');
    }
    final comp = pendingDownloads[taskId];
    if (comp != null && !comp.isCompleted) {
      comp.complete();
    }
  }

  @override
  Future<bool> hasEnoughDiskSpace(String targetDirectory, int requiredBytes) async {
    return simulatedHasEnoughSpace;
  }

  @override
  String buildTempFilePath(String savePath, String fileName) {
    return '$savePath/$fileName.dmxpart';
  }

  @override
  void updateSpeedLimit(int bytesPerSecond, int activeCount) {}

  @override
  Future<void> close() async {
    for (final token in activeCancelTokens.values) {
      if (!token.isCancelled) {
        token.cancel('Engine closed');
      }
    }
    for (final comp in pendingDownloads.values) {
      if (!comp.isCompleted) comp.complete();
    }
  }
}
